### ISSUE TITLE
Error with Nauvis Day

### ISSUE THREAD

**Issue by Sensei-Farm** [ReikaKalseki/Reika_FactorioMods_Issues#100]
Failed to load mods __NauvisDay__/data-final-fixes.lua:72: bad argument #1 to 'pairs' (table expected,got nil)
![factorio bug](https://user-images.githubusercontent.com/43001420/45091688-86de2300-b113-11e8-9727-1cd81fc29fa1.PNG)
After some testing it seems the issue is caused by the Omnipermutate mod by EmperorZelos.
Can you fix it or should I talk to him about that?

**Comment by ReikaKalseki** [comment]
Fixed.
