### ISSUE TITLE
AutoTrainDepot update confliction with PickerTweaks

### ISSUE THREAD

**Issue by Silvernova115** [ReikaKalseki/Reika_FactorioMods_Issues#101]
10.005 Loading mod upgrade-planner 1.5.3 (data.lua)
  10.168 Loading mod Vehicle Wagon 1.2.5 (data.lua)
  10.332 Loading mod vtk-cannon-turret 1.4.1 (data.lua)
  10.495 Loading mod Warehousing 0.1.3 (data.lua)
  10.660 Loading mod Waterfill_v15 0.1.3 (data.lua)
  10.824 Loading mod YARM 0.7.306 (data.lua)
  10.991 Loading mod yi_railway 0.6.21 (data.lua)
  11.171 Loading mod Yuoki 0.6.74 (data.lua)
  11.370 Loading mod Bio_Industries 2.6.11 (data.lua)
  11.577 Loading mod bobores 0.16.2 (data.lua)
  11.768 Loading mod bobtech 0.16.6 (data.lua)
  12.011 Loading mod bobvehicleequipment 0.16.2 (data.lua)
  12.215 Loading mod CW-hydrogen-power 0.2.0 (data.lua)
  12.413 Loading mod Diesel-Locomotive 0.1.6 (data.lua)
  12.627 Loading mod LogisticTrainNetwork 1.8.0 (data.lua)
  12.839 Loading mod nixie-tubes 0.16.4 (data.lua)
  13.052 Loading mod nuclear-fuel-cycle 0.1.0 (data.lua)
  13.263 Loading mod NuclearFurnace 0.0.5 (data.lua)
  13.473 Loading mod PickerTweaks 1.0.2 (data.lua)
  13.474 Error ModManager.cpp:1024: Failed to load mod "PickerTweaks": __PickerTweaks__/data.lua:1: __PickerTweaks__/prototypes/signals/lamp-colors.lua:34: attempt to index field 'order' (a nil value)
  13.477 Loading mod core 0.0.0 (data.lua)
  13.572 Checksum for core: 2304860305
  13.590 Error ModManager.cpp:1024: Error in assignID, recipe-category with name 'crafting' does not exist.

Source: enemy-base (noise-layer).
  13.695 Loaded shader file D:/Steam Client/Steam/steamapps/common/Factorio/data/core/graphics/shaders/game.cso
  13.695 Loaded shader file D:/Steam Client/Steam/steamapps/common/Factorio/data/core/graphics/shaders/zoom-to-world.cso
  13.695 Loaded shader file D:/Steam Client/Steam/steamapps/common/Factorio/data/core/graphics/shaders/alpha-mask.cso
  13.721 Initial atlas bitmap size is 16384
  13.721 Created atlas bitmap 192x5 [none]
  13.721 Created atlas bitmap 132x24 [no-crop, trilinear-filtering, icon, light]
  13.887 Sprites loaded
  13.887 Convert atlas 132x24 to: trilinear-filtering 
  13.898 Custom inputs active: 0
  13.904 Factorio initialised
  13.904 RivaTuner Statistics Server hook detected (rtsshooks64.dll)
  13.905 Mods to disable:Failed to load mods: __PickerTweaks__/data.lua:1: __PickerTweaks__/prototypes/signals/lamp-colors.lua:34: attempt to index field 'order' (a nil value)

Game loads with AutoTrainDepot removed

**Comment by ReikaKalseki** [comment]
I highly doubt this is my doing - noone should be deleting the "crafting" recipe category, as that is the fundamental type.

**Comment by Silvernova115** [comment]
I just report as I see it. It happened in the most recent update with train depot and the error didnt occure when the mod was removed

**Comment by ReikaKalseki** [comment]
Is there a link to the PickerTweaks source?

**Comment by Silvernova115** [comment]
https://mods.factorio.com/mod/PickerTweaks

**Comment by ReikaKalseki** [comment]
Fixed.
