### ISSUE TITLE
Auto Depot crash again...

### ISSUE THREAD

**Issue by Silvernova115** [ReikaKalseki/Reika_FactorioMods_Issues#102]
15.527 Loading mod nuclear-fuel-cycle 0.1.0 (data.lua)
  15.774 Loading mod NuclearFurnace 0.0.5 (data.lua)
  16.018 Loading mod PickerTweaks 1.0.2 (data.lua)
  16.019 Error ModManager.cpp:1024: Failed to load mod "PickerTweaks": __PickerTweaks__/data.lua:1: __PickerTweaks__/prototypes/signals/lamp-colors.lua:34: attempt to index field 'order' (a nil value)
  16.023 Loading mod core 0.0.0 (data.lua)
  16.129 Checksum for core: 2304860305
  16.151 Error ModManager.cpp:1024: Error in assignID, recipe-category with name 'crafting' does not exist.

Source: enemy-base (noise-layer).
  16.278 Loaded shader file D:/Steam Client/Steam/steamapps/common/Factorio/data/core/graphics/shaders/game.cso
  16.278 Loaded shader file D:/Steam Client/Steam/steamapps/common/Factorio/data/core/graphics/shaders/zoom-to-world.cso
  16.279 Loaded shader file D:/Steam Client/Steam/steamapps/common/Factorio/data/core/graphics/shaders/alpha-mask.cso
  16.299 Initial atlas bitmap size is 16384
  16.299 Created atlas bitmap 192x5 [none]
  16.299 Created atlas bitmap 132x24 [no-crop, trilinear-filtering, icon, light]
  16.466 Sprites loaded
  16.466 Convert atlas 132x24 to: trilinear-filtering 
  16.476 Custom inputs active: 0
  16.483 Factorio initialised
  16.483 RivaTuner Statistics Server hook detected (rtsshooks64.dll)
  16.483 Mods to disable:Failed to load mods: __PickerTweaks__/data.lua:1: __PickerTweaks__/prototypes/signals/lamp-colors.lua:34: attempt to index field 'order' (a nil value)

Mods to be disabled:
• PickerTweaks
  24.354 DSound: Stopping voice
  24.354 DSound: Joining thread
  24.356 DSound: Exit _dsound_update; tid=16704
  24.356 DSound: Waiting for voice to stop ... signaled
  24.356 DSound: Joined thread
  24.356 DSound: Destroying thread
  24.356 DSound: Thread destroyed
  24.356 DSound: Releasing buffer
  24.356 DSound: Voice stopped
  24.356 DSound: Deallocating voice
  24.356 DSound: Deallocated voice
  24.385 Steam API shutdown.
  24.421 Razer Chroma Controller un-initialized
  24.421 Goodbye

This time its a different error but still only seems to happen what auto depot is installed. starts up with auto depot disabled

**Comment by ReikaKalseki** [comment]
This is the exact same error as #101.
