### ISSUE TITLE
Nauvis Day on-tick Crash - Unexpected pollution...?

### ISSUE THREAD

**Issue by GaistH** [ReikaKalseki/Reika_FactorioMods_Issues#104]
This was out of nowhere, not sure what prompted it (mid multiplayer game)

![alvankz](https://user-images.githubusercontent.com/42808283/45400265-7cdb8900-b619-11e8-8e45-a1ccfa231209.png)

[factorio-current.log](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/2373454/factorio-current.log)

**Comment by ReikaKalseki** [comment]
Caches:32 concerns steam furnaces; some other script deleted the entity without notifying the game properly.
