### ISSUE TITLE
Nauvis Day crash on 'molten brass' spill

### ISSUE THREAD

**Issue by GaistH** [ReikaKalseki/Reika_FactorioMods_Issues#105]
Nobody expects the Spanish Inquisition--and it seems Nauvis Day didn't expect spilled-liquid-molten-brass-1!

![nm0ifol](https://user-images.githubusercontent.com/42808283/45404440-ee710280-b62c-11e8-9f41-335224093800.png)

[factorio-current.log](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/2373679/factorio-current.log)

**Comment by ReikaKalseki** [comment]
The fluid must be added after NVDay parses the list of fluids. I can move mine later.

**Comment by Exalus80** [comment]
How to add the liquids? I have the same problems with the liquids from the Omnimatter.

An alternative solution is to first delete the recipe from the machines.

**Comment by ReikaKalseki** [comment]
There is nothing you can do as an end user to add the other fluids short of editing the code yourself.

**Comment by Exalus80** [comment]
If you still want to implement the missing Liquid ID's. They all come from this additional mod for Omnimatter. https://mods.factorio.com/mod/OmniSea

**Comment by ReikaKalseki** [comment]
Done.
