### ISSUE TITLE
Problem with Endgame Combat 1.0.144 Game Version 0.16.x

### ISSUE THREAD

**Issue by Destro95** [ReikaKalseki/Reika_FactorioMods_Issues#106]
Hello,

I´ve download the mod and then it dousten work and this come....

![endgame combat](https://user-images.githubusercontent.com/43247601/45503065-0740fb80-b786-11e8-8cd9-963fab051203.png)

Pls help me then i really like this mod and have over 300hours of gaming on the map.....

**Comment by Destro95** [comment]
sorry but the problem is still there, is not fixed... what can i do?

**Comment by ReikaKalseki** [comment]
Fixed in code does not mean the fix is yet released.

**Comment by Destro95** [comment]
oh ok, thanks

**Comment by Destro95** [comment]
Sorry for the Questionm but when do you think that you releasing it? I don´t play until you releasing it

sorry for my bad english

**Comment by ReikaKalseki** [comment]
Done.

**Comment by Destro95** [comment]
thank you very much
