### ISSUE TITLE
FTweaks startup crash No such item 'solar-panel' in recipe!

### ISSUE THREAD

**Issue by GaistH** [ReikaKalseki/Reika_FactorioMods_Issues#107]
![93702e61e8](https://user-images.githubusercontent.com/42808283/45707357-a120f380-bb4c-11e8-8c3e-42e824098714.png)

[factorio-current.log](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/2394013/factorio-current.log)

Edit: Looks like it got bumped to previous, so here's that log:
[factorio-previous.log](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/2394049/factorio-previous.log)

**Comment by ReikaKalseki** [comment]
Fixed.
