### ISSUE TITLE
rubber belt seems have hr-version issue.

### ISSUE THREAD

**Issue by combow** [ReikaKalseki/Reika_FactorioMods_Issues#108]
As like shown in article name.(Crush on boot without high resolution mode.)

**Comment by Sounlee** [comment]
same for me. (nil value error on HR_crappybelt)

**Comment by ReikaKalseki** [comment]
I do not get this error.

**Comment by ReikaKalseki** [comment]
And this should have been made completely obsolete by the 0.17 update.
