### ISSUE TITLE
Old styled pumps

### ISSUE THREAD

**Issue by combow** [ReikaKalseki/Reika_FactorioMods_Issues#109]
Accelerated Pump has old style sprite and collision boxes.
Accelerated Offshore Pump has old style placing rule(Inside of shoreline than vanilla one).

**Comment by ReikaKalseki** [comment]
Does the AP still work?

**Comment by combow** [comment]
Both are works normally, so no matter in the point.
But, offshore pump is allowed anormally placing (Almost no matter, but not good).

**Comment by ReikaKalseki** [comment]
Fixed.
