### ISSUE TITLE
Endgame Combat - Turret Ammo Low Spam

### ISSUE THREAD

**Issue by fyretooth** [ReikaKalseki/Reika_FactorioMods_Issues#110]
I have a bunch of belt-fed gun turrets, which only loads 10 magazines into the turrets. I changed the threshold in the settings to 5, but the warnings don't go away. Mining and replacing the turret temporarily disables the alert, but it resumes as soon as it fires.

**Comment by ReikaKalseki** [comment]
Do you have "dynamic" alerts on? If so, what is your evolution factor and ammo type?

**Comment by fyretooth** [comment]
Yes, "0.4371 (Time 18%) (Pollution 78%) (Spawner Kills 4%)", and piercing rounds
the tooltip on dynamic alerts implies that i should upgrade the ammo type to disable the alert, i suppose

**Comment by ReikaKalseki** [comment]
Or decrease evo, or increase the amount of ammo kept in each turret, yes. It thinks you cannot kill many biters per ammo-load.

**Comment by fyretooth** [comment]
however, the dynamic alert is a startup setting, and can't be disabled in-game
i get that this doesn't count as a bug, so maybe a feature request? it's quite annoying having the alert constantly on when i can't do anything immediate to fix it
i also remember reading a method to disable the alert audio, but i can't find that thread again

**Comment by ReikaKalseki** [comment]
> however, the dynamic alert is a startup setting, and can't be disabled in-game

Save, exit to the main menu, and change it.

> it's quite annoying having the alert constantly on when i can't do anything immediate to fix it

You can adjust the ammo feed amount quite readily, and that is what it is trying to get you to do.

> i also remember reading a method to disable the alert audio, but i can't find that thread again

There is a command to mute the sounds for a user-specified length of time. /muteTurretAlerts <time><unit>.

**Comment by turok403** [comment]
> Save, exit to the main menu, and change it.

I have the same problem and i have already disabled the dynamic alerts on mod's settings but the "Turret Ammo Low" alert keeps spaming...  even if i use the "/mute Alerts" command

**Comment by ReikaKalseki** [comment]
Then you are not using the command properly. And the fact that you write it as "/mute Alerts" is consistent with that fact.
