### ISSUE TITLE
Commands not initializing on new save

### ISSUE THREAD

**Issue by OskarPepryk** [ReikaKalseki/Reika_FactorioMods_Issues#111]
There is no command such as "/findItem". I tried also "/c findItem" and "findItem". The command also doesn't appear when I type /h.

**Comment by ReikaKalseki** [comment]
/findItem <itemtype>.

In the current version, you need to install the mod, save the game, and load the save.

**Comment by OskarPepryk** [comment]
Yes, that was it. It would be a good idea to state that in mod description. Very useful mod. Thanks.

**Comment by ReikaKalseki** [comment]
Fixed.
