### ISSUE TITLE
Units tissue drop issue 

### ISSUE THREAD

**Issue by Praseody** [ReikaKalseki/Reika_FactorioMods_Issues#112]
The units tissue drop option, unchecked. But the bitter or spitter still drop tissues !!

 https://imgur.com/a/Y8JnvJM

**Comment by ReikaKalseki** [comment]
This does not happen for me, and the code is very simple and cannot be doing unexpected things. The drops are either from things like worms or spawners, or predate your changing the setting, or are being spawned by other mods.
