### ISSUE TITLE
Failed to load mod

### ISSUE THREAD

**Issue by Pekkape** [ReikaKalseki/Reika_FactorioMods_Issues#113]
Hello Reika

Just installed your mod and got the following error message while loading the game:

Failed to load mod: Error while loading technology prototype "depot-item-count-6! (technology): Difficulty normal: Ingridient with type item and name "science-pack-3" is registred twice in the technology

**Comment by ReikaKalseki** [comment]
I have already fixed this for release.

**Comment by Pekkape** [comment]
Nice.  :)  

Well done  :)

**Comment by ReikaKalseki** [comment]
Fixed once more.
