### ISSUE TITLE
The name "greenhouse" is easy to conflicts with other MOD.

### ISSUE THREAD

**Issue by combow** [ReikaKalseki/Reika_FactorioMods_Issues#114]
As like article name. (ex. food indsutly.)

**Comment by ReikaKalseki** [comment]
Changing it now will break worlds.

**Comment by combow** [comment]
You have to learn to code for migration (Just like author of food-industry did like so.).

**Comment by ReikaKalseki** [comment]
That will not help people jumping large version changes, or my own save which has very different version numbering.
