### ISSUE TITLE
NauvisDay crash on load refinery.lua attempt to index field '?'

### ISSUE THREAD

**Issue by GaistH** [ReikaKalseki/Reika_FactorioMods_Issues#115]
44.584 Error ModManager.cpp:1024: Failed to load mod "NauvisDay": __NauvisDay__/data-updates.lua:6: __NauvisDay__/prototypes/refinery.lua:101: attempt to index field '?' (a nil value)

![ndcrash](https://user-images.githubusercontent.com/42808283/46819061-c3272380-cd50-11e8-98a0-3ea54d08f8ce.png)

[factorio-current.log](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/2469783/factorio-current.log)

**Comment by Sounlee** [comment]
i get the same errror while trying to use darkstar utilities.

**Comment by ReikaKalseki** [comment]
Above [this line](https://github.com/ReikaKalseki/NauvisDay/blob/master/prototypes/refinery.lua#L101), put these two lines:
`log(pre)`
`log(serpent.block(data.raw.item[pre]))`

What is the console output?

**Comment by Bredo70** [comment]
Hi
I have the same issue. Is this what you need?

Loading mod NauvisDay 1.0.164 (data-updates.lua)
  47.868 Script @__NauvisDay__/prototypes/refinery.lua:111: Adding clean refinery clean-oil-refinery from oil-refinery Conversion/-
  47.869 Script @__NauvisDay__/prototypes/refinery.lua:101: nil
  47.869 Script @__NauvisDay__/prototypes/refinery.lua:102: nil
  47.869 Error ModManager.cpp:1024: Failed to load mod "NauvisDay": __NauvisDay__/data-updates.lua:6: __NauvisDay__/prototypes/refinery.lua:103: attempt to index field '?' (a nil value)
  47.872 Loading mod core 0.0.0 (data.lua)
  48.074 Checksum for core: 2304860305
  48.105 Error ModManager.cpp:1024: Error in assignID, recipe-category with name 'crafting' does not exist.

Source: enemy-base (noise-layer).

**Comment by ReikaKalseki** [comment]
OK, now replace the `log` lines with this:

	for name,proto in pairs(data.raw["assembling-machine"]) do
		if #proto.crafting_categories == 1 and proto.crafting_categories[1] == "oil-processing" then
			log("Found refinery " .. name)
			local recipe = data.raw.recipe[proto.minable.result]
			log("Found recipe " .. serpent.block(recipe))
		end
	end

**Comment by Bredo70** [comment]
Cut from logfile:

40.106 Loading mod NauvisDay 1.0.164 (data-updates.lua)
  40.110 Script @__NauvisDay__/prototypes/refinery.lua:118: Adding clean refinery clean-oil-refinery from oil-refinery Conversion/-
  40.110 Script @__NauvisDay__/prototypes/refinery.lua:104: Found refinery oil-refinery
  40.111 Script @__NauvisDay__/prototypes/refinery.lua:106: Found recipe {
  enabled = false,
  energy_required = 8,
  ingredients = {
    {
      amount = 15,
      name = "steel-plate",
      type = "item"
    },
    {
      amount = 10,
      name = "iron-gear-wheel",
      type = "item"
    },
    {
      amount = 10,
      name = "stone-brick",
      type = "item"
    },
    {
      amount = 10,
      name = "electronic-circuit",
      type = "item"
    },
    {
      amount = 10,
      name = "pipe",
      type = "item"
    }
  },
  name = "oil-refinery",
  result = "oil-refinery",
  type = "recipe"
}
  40.111 Script @__NauvisDay__/prototypes/refinery.lua:104: Found refinery oil-refinery-2
  40.111 Script @__NauvisDay__/prototypes/refinery.lua:106: Found recipe {
  enabled = false,
  energy_required = 5,
  ingredients = {
    {
      amount = 10,
      name = "oil-refinery",
      type = "item"
    },
    {
      amount = 5,
      name = "steel-bearing",
      type = "item"
    }
  },
  name = "oil-refinery-2",
  result = "oil-refinery-2",
  type = "recipe"
}
  40.111 Script @__NauvisDay__/prototypes/refinery.lua:104: Found refinery oil-refinery-3
  40.111 Script @__NauvisDay__/prototypes/refinery.lua:106: Found recipe {
  enabled = false,
  energy_required = 5,
  ingredients = {
    {
      amount = 1,
      name = "oil-refinery-2",
      type = "item"
    },
    {
      amount = 5,
      name = "titanium-bearing",
      type = "item"
    }
  },
  name = "oil-refinery-3",
  result = "oil-refinery-3",
  type = "recipe"
}
  40.111 Script @__NauvisDay__/prototypes/refinery.lua:104: Found refinery oil-refinery-4
  40.111 Script @__NauvisDay__/prototypes/refinery.lua:106: Found recipe {
  enabled = false,
  energy_required = 5,
  ingredients = {
    {
      amount = 1,
      name = "oil-refinery-3",
      type = "item"
    },
    {
      amount = 5,
      name = "nitinol-bearing",
      type = "item"
    }
  },
  name = "oil-refinery-4",
  result = "oil-refinery-4",
  type = "recipe"
}
  40.111 Error ModManager.cpp:1024: Failed to load mod "NauvisDay": __NauvisDay__/data-updates.lua:6: __NauvisDay__/prototypes/refinery.lua:110: attempt to index field '?' (a nil value)
  40.114 Loading mod core 0.0.0 (data.lua)
  40.302 Checksum for core: 2304860305
  40.330 Error ModManager.cpp:1024: Error in assignID, recipe-category with name 'crafting' does not exist.

Source: enemy-base (noise-layer).

**Comment by ReikaKalseki** [comment]
This really is not making sense, especially given that the data is the same as in my save, which loads fine...

One more output block to try:
Add the `log` lines seen in this block of code, into the appropriate places, as seen in this block of code.

	recipe2.name = refinery.name .. "-upgrade"
	log("Attempting " .. recipe2.name)
	for _,ing in pairs(recipe2.ingredients) do
		log("Checking " .. serpent.block(ing))
		if ing[1] and string.find(ing[1], "refinery") then
			ing[1] = "clean-" .. ing[1]
			pre = ing[1]
			log("Found " .. serpent.block(ing) .. " , results in " .. pre)
		end
	end
	log("Determined " .. pre .. " , has item? " .. (data.raw.item[pre] and "Yes" or "No"))
	recipe2.result = refinery.name
	recipe2.enabled = false
	recipe2.localised_name = {"clean-refinery.upgrade", data.raw.item[pre].localised_name, refinery.localised_name}

**Comment by Bredo70** [comment]
Just for your information, my solution to the problem is to roll back to NauvisDay_1.0.148 and the game runs just fine (can't manage without my daily dose of Factorio)

Cut from logfile:

43.159 Loading mod NauvisDay 1.0.164 (data-updates.lua)
  43.163 Script @__NauvisDay__/prototypes/refinery.lua:113: Adding clean refinery clean-oil-refinery from oil-refinery Conversion/-
  43.164 Script @__NauvisDay__/prototypes/refinery.lua:93: Attempting clean-oil-refinery-2-upgrade
  43.164 Script @__NauvisDay__/prototypes/refinery.lua:95: Checking {
  amount = 10,
  name = "oil-refinery",
  type = "item"
}
  43.164 Script @__NauvisDay__/prototypes/refinery.lua:95: Checking {
  amount = 5,
  name = "steel-bearing",
  type = "item"
}
  43.165 Error ModManager.cpp:1024: Failed to load mod "NauvisDay": __NauvisDay__/data-updates.lua:6: __NauvisDay__/prototypes/refinery.lua:102: attempt to concatenate local 'pre' (a nil value)
  43.168 Loading mod core 0.0.0 (data.lua)
  43.350 Checksum for core: 2304860305
  43.377 Error ModManager.cpp:1024: Error in assignID, recipe-category with name 'crafting' does not exist.

Source: enemy-base (noise-layer).

**Comment by ReikaKalseki** [comment]
Ohh, I know what is wrong. Fixed.
