### ISSUE TITLE
T-Re(e)plant healing trees

### ISSUE THREAD

**Issue by thedx4** [ReikaKalseki/Reika_FactorioMods_Issues#117]
By default, if a tree accumulates 3500 pollution it starts losing leaves and goes from stage 3 (full leaves) to stage 0 (no leaves) and never goes back.

Can you implement a way for trees to advance stages if pollution gets low again?

**Comment by ReikaKalseki** [comment]
Not "on their own", but the Tree Healing capsule can do this.

**Comment by thedx4** [comment]
Yeah, that's what I mean. Can you implement the trees to grow back their leaves (advance stages) on their own if the pollution is low?

**Comment by ReikaKalseki** [comment]
Not without a significant performance penalty. That said, I would request this on the forums - I have always wanted that to be part of the base game.
