### ISSUE TITLE
Endgame Combat loading error

### ISSUE THREAD

**Issue by Tobanyi** [ReikaKalseki/Reika_FactorioMods_Issues#118]
![1](https://user-images.githubusercontent.com/43660690/47017883-6b5a3500-d121-11e8-9a1c-5f04468e576f.JPG)

**Comment by vigonz06** [comment]
I have the same problem

**Comment by Destro95** [comment]
me too

**Comment by ReikaKalseki** [comment]
Fixed. For now, add `require "config"` to the top of projectiles.lua.

**Comment by vigonz06** [comment]
ok.. how do I do that, I cannot edit the file

**Comment by Tobanyi** [comment]
> 
> 
> ok.. how do I do that, I cannot edit the file

You'll need to remove the file from the ZIP, edit the file, then place it back in the ZIP.  Open the file with something like Notepad++ (regular notepad works fine).
