### ISSUE TITLE
More BP weirdness

### ISSUE THREAD

**Issue by DaveInTexas** [ReikaKalseki/Reika_FactorioMods_Issues#12]
i'm copying this guy (among the many who cannot read?) as he seems to know more about the situation than i do.. (you may have already fixed it, dunno).
<Quote>
☺/

Found a bug when making blueprints after starting to research turret upgrades.
After each research the turret gets a new name after placing, the problem is that the blueprint uses that new name instead of the original "gun turret" name/id.

Using blueprint upgrader to upgrade the blueprint from gun turret to turrets mk2 for example fails.
Taking an upgraded turret back into inventory reverts it back to a standard turret which is added to the stack.
</Quote>

I've noticed that when i have a BP containing a concussion turret bots won't place them.  I've progressed well beyond regular turrets but i'll do some testing there.

**Comment by ReikaKalseki** [comment]
Blueprints work fine for me, and have for more than two weeks. When range-boosted ghosts are placed, they are automatically converted.

**Comment by ReikaKalseki** [comment]
I just tested. They still work fine. That user must be using an old version. Which goes well with not following simple instructions.
