### ISSUE TITLE
[EndgameCombat] projectiles.lua:212

### ISSUE THREAD

**Issue by hasezoey** [ReikaKalseki/Reika_FactorioMods_Issues#121]
Hi Again, new Issue.
Failed to load mods: __EndgameCombat__/data.lua:5:__EndgameCombat__/prototypes/projectiles.lua:212: attempt to index global 'Config' (a nil value)
https://imgur.com/a/X5NjpIh

**Comment by ReikaKalseki** [comment]
Literally *the very last issue*! #118 #120

**Comment by hasezoey** [comment]
Ooops, did noticed it was a duplicate, sorry
