### ISSUE TITLE
extremely slow game

### ISSUE THREAD

**Issue by vigonz06** [ReikaKalseki/Reika_FactorioMods_Issues#122]
the mod makes my game go really slow (it is this mod, because I deactivate it, and the game goes back to work just perfect)

**Comment by ReikaKalseki** [comment]
Show me the timing data. You did not even say *what mod*.

**Comment by vigonz06** [comment]
lol, sorry, you are right, Endgame Combat (I forgot this repo was for all your mods, sorry)

**Comment by vigonz06** [comment]
and... where do I find the timing data?

**Comment by ReikaKalseki** [comment]
The debug menus will have it. I do not know what your keybinds are.
