### ISSUE TITLE
Hard dependencies on bobmods

### ISSUE THREAD

**Issue by LoLEngel** [ReikaKalseki/Reika_FactorioMods_Issues#123]
I prefer to only use bob's logistics, but for some reason, a relatively recent update to this mod has made its soft dependencies into hard dependencies. I tested uninstalling everything but this, bob's library, and bob's logistics, and I got an error at startup

Then I tested it with FTweaks, boblib, bobplate, and boblogistics

Got a different error

Then with boblibrary, boblogistics, bobplates, bobores, bobtech, and FTweaks

It worked

**Comment by ReikaKalseki** [comment]
I cannot do anything until you tell me what that error was.

**Comment by ReikaKalseki** [comment]
Hello?

**Comment by LoLEngel** [comment]
> Hello?

https://www.youtube.com/watch?v=QwGBr8Uutmg
(watching on 2x speed recommended) 

Error message is shown upon each failure to load (the first being at 0:23; each failure has an identical error message).. Don't know how to embed images on this site so I figured a quick video would be a bit more helpful than an imgur slideshow 

(Copy-paste from description):
____________________________________________________________________
0:00 First test: I tried to launch with my _entire load order._ **FAILED TO LOAD**

1:12 Second test: Launched with my _entire load order, minus the two bob mods_ I wanted to use. **LOADED SUCCESSFULLY**

2:06 Third test: Launched with _ONLY FTweaks and the two Bob Mods._ **FAILED TO LOAD**

4:04 Final test: Launched with _only FTweaks and ALL Bob Mods._ **LOADED SUCCESSFULLY**
____________________________________________________________________


I had described my process in the OP because I figured it was incredibly easy to reproduce in less than 5 minutes  ¯\\\_(ツ)_/¯

It seems to me to be an issue with  bob logistics making FTweaks want to require bobtech and bobplates

**Comment by ReikaKalseki** [comment]
No, it is not supposed to have any hard dependencies at all.

Fixed.

**Comment by LoLEngel** [comment]
Is there an ETA on the fix release? 👀 Love this mod

**Comment by ReikaKalseki** [comment]
I released this less than an hour after fixing it.

**Comment by LoLEngel** [comment]
So is there just a delay on mods.factorio.com, or...?
https://youtu.be/FSRWI05B_EA

____________
**Error loading mods**

Failed to load mods: \_\_FTweaks\_\_/data-final-fixes.lua:1:1 \_\_Ftweaks\_\_/functions.lua:177:No such item 'nitrol-gear-wheel' in recipe!
stack traceback:
\_\_FTweaks\_\_/functions.lua:177: in function 'changeIngredientInList'
\_\_FTweaks\_\_/functions.lua.186: in function 'replaceItemInRecipe'
\_\_FTweaks\_\_/prototypes/bridges.lua:275: in main chunk
[C]: in function 'require'
\_\_Ftweaks\_\_/data-final-fixes.lua:1: in main chunk

Mods to be disabled:
• FTweaks
____________

With only FTweaks, Bob's Library, and Bob's Logistics activated 

I said "hard dependency created when..." because this only happens when you have a bob's mod that isn't whatever has nitrol gear wheels and cobalt axes activated.

**Comment by ReikaKalseki** [comment]
Line 275 should only get called if the item exists:

![https://i.imgur.com/7IxEBG5.png](https://i.imgur.com/7IxEBG5.png)

**Comment by LoLEngel** [comment]
Alright so I guess it's a problem on bob's side?

**Comment by TheStaplergun** [comment]
Nitrol or nitinol?

Nitinol gear wheel is a thing. Nitrol gear wheel (referenced in the stack trace to error at line 177 in functions.lua) is not an item.

**Comment by mexmer** [comment]
> Line 275 should only get called if the item exists:
> 
> ![https://i.imgur.com/7IxEBG5.png](https://camo.githubusercontent.com/27924364d765d8718b9ffb7ef2619a8ff1575b54/68747470733a2f2f692e696d6775722e636f6d2f374978454247352e706e67)

reika, your code doesn't check for existence of nitinol-gear-wheel, hence why error pops.
either write your function, so it check if "items exists" during replace, or don't call replace, if there is not "nitinol-gear-wheel" present, ultimate belt recipe might not contain that item in recipe, while your replace function expects that it is always present.

```
if Config.cheaperBelts and data.raw.item["ultimate-transport-belt"] then
	replaceItemInRecipe("ultimate-transport-belt", "nitinol-gear-wheel", "nitinol-gear-wheel", 0.4)
	replaceItemInRecipe("ultimate-transport-belt", "nitinol-bearing", "nitinol-bearing", 0.4)
```

**Comment by mexmer** [comment]
@ReikaKalseki you marked this issue as fixed, but did you really fix it?

**Comment by ReikaKalseki** [comment]
> Nitrol or nitinol?

> Nitinol gear wheel is a thing. Nitrol gear wheel (referenced in the stack trace to error at line 177 in functions.lua) is not an item.

I have no mentions of "nitrol", and the actual error images he posted contained 'nitinol'. I assumed he just manually retyped the error and misspelled it as 'nitrol'.

> reika, your code doesn't check for existence of nitinol-gear-wheel, hence why error pops.

Did you *not look* at the image you quoted? Line 274.

**Comment by mexmer** [comment]
i'm talking about replaceItemInRecipe function.
just because there is ultimate-transport-belt, it doesn't mean it's from bobs mod, or that it does contain nitinol-gear-wheel

mind your function specifically says
No such item 'nitinol-gear-wheel' in recipe!
that means, ultimate-transport-belt in this mod combination doesn't contain nitinol-gear-wheel

simply saying, your assumption, that ultimate-transport-belt recipe will always have nitinol parts is wrong.

**Comment by mexmer** [comment]
you should add same test for nitinol parts, as you have here for cobalt
https://github.com/ReikaKalseki/FTweaks/blob/acb11cad55ab66e0afb6149a04f8bd4e538833f3/prototypes/bridges.lua#L280

**Comment by ReikaKalseki** [comment]
> i'm talking about replaceItemInRecipe function.
> just because there is ultimate-transport-belt, it doesn't mean it's from bobs mod, or that it does contain nitinol-gear-wheel

Again, the recipe change is only called if nitinol gear wheels *do* exist. See the image.

> you should add same test for nitinol parts, as you have here for cobalt
> ReikaKalseki/FTweaks:prototypes/bridges.lua@acb11ca#L280

I do! *Look at the image you quoted!*

**Comment by mexmer** [comment]
@ReikaKalseki then you need to modify your replaceItemInRecipe function, so it doesn't throw error, but simply do nothing when either replaced or replacement item (although they are same in your case) don't exists in recipe.

it's possible that ultimate belt recipe was modified before your mod touched it, and doesn't contain nitinol gear at all.

mind there is also possibility, that mod author might change actual recipe, so it will not match your assumption about it's content. or might have different recipe for normal and marathon.

it's your choice to make it into hard or soft error, but anyways problem is in your scripts, not elsewhere.

**Comment by ReikaKalseki** [comment]
> then you need to modify your replaceItemInRecipe function, so it doesn't throw error, but simply do nothing when either replaced or replacement item (although they are same in your case) don't exists in recipe.

The error is deliberate - I do not want silent failures that go unnoticed for six months.

**Comment by mexmer** [comment]
nothing to add then 👍

**Comment by ReikaKalseki** [comment]
Well, the fact that the error is getting thrown is significant - either something else has modified the recipe, which is possible, and if so, I need to add handling - or there is some other more subtle error, possibly on my end.

**Comment by LoLEngel** [comment]
https://www.youtube.com/watch?v=lRy6HwuH1f8

![20181216131212_1](https://user-images.githubusercontent.com/44330286/50057768-cb2a8780-0134-11e9-86d2-0184c77fac49.jpg)
![20181216131449_1](https://user-images.githubusercontent.com/44330286/50057770-cebe0e80-0134-11e9-9115-e56736e83e08.jpg)
![20181216131449_2](https://user-images.githubusercontent.com/44330286/50057771-cfef3b80-0134-11e9-8491-1ea005e4c798.jpg)
![20181216131450_1](https://user-images.githubusercontent.com/44330286/50057773-d1206880-0134-11e9-940c-84a5fc432961.jpg)
![20181216131450_2](https://user-images.githubusercontent.com/44330286/50057774-d2519580-0134-11e9-9f6a-ee091872cf01.jpg)
![20181216131502_1](https://user-images.githubusercontent.com/44330286/50057776-d2ea2c00-0134-11e9-94f9-8b71ca10c03c.jpg)
![20181216131502_2](https://user-images.githubusercontent.com/44330286/50057777-d41b5900-0134-11e9-997d-294df97d6989.jpg)
![20181216131503_1](https://user-images.githubusercontent.com/44330286/50057778-d4b3ef80-0134-11e9-9a3d-cf584a0c194d.jpg)
![20181216131506_1](https://user-images.githubusercontent.com/44330286/50057779-d54c8600-0134-11e9-8e50-1a938f27b536.jpg)
![20181216131506_2](https://user-images.githubusercontent.com/44330286/50057780-d5e51c80-0134-11e9-8165-396dddab5518.jpg)
![20181216131506_3](https://user-images.githubusercontent.com/44330286/50057782-d67db300-0134-11e9-9974-bb053b22facc.jpg)
![20181216131511_1](https://user-images.githubusercontent.com/44330286/50057783-d7164980-0134-11e9-9dcb-6f7f4028ff1a.jpg)
![20181216131512_1](https://user-images.githubusercontent.com/44330286/50057784-d7aee000-0134-11e9-91e4-834c20e294da.jpg)
![20181216131512_2](https://user-images.githubusercontent.com/44330286/50057785-d8477680-0134-11e9-8daf-2004fb3fb5fb.jpg)
![20181216131512_3](https://user-images.githubusercontent.com/44330286/50057786-d8e00d00-0134-11e9-8dd5-ee93531f6c2c.jpg)
![20181216131513_1](https://user-images.githubusercontent.com/44330286/50057787-d978a380-0134-11e9-81b9-ca20f15f66c8.jpg)
