### ISSUE TITLE
EndgameCombat Loading issue because of "f"

### ISSUE THREAD

**Issue by jodojodo** [ReikaKalseki/Reika_FactorioMods_Issues#124]
Hi Reika,

I cannot start the game since the last update and the problem seems to be in the Endgamecombat mod in the override.lua:

__EndgameCombat__/data-updates.lua:6: __EndgameCombat__/prototypes/overrides.lua:142: attempt to perform arithmetic on global 'f' (a nil value)

I've inspected the line and there are some calculations with "f" and I cannot find a definition of it.
After dissabling those lines with -- comments. The game starts normally.

**Comment by jamalabdullah** [comment]
same to. i have this problem. kindly advise on how to rectify it. thank you

**Comment by Jeltron** [comment]
I had this problem caused by the mod "Helicopters", specifically version 0.2.16. After I disabled said mod the error stopped appearing during game startup.

**Comment by ReikaKalseki** [comment]
Some code was copied from FTweaks and then modified to do what I wanted EGCombat to do...I in fact accidentally modified the *FTweaks* one instead.
