### ISSUE TITLE
TreePlant 1.0.148 fails when loaded with Dectorio 0.8.9 

### ISSUE THREAD

**Issue by WonderDog** [ReikaKalseki/Reika_FactorioMods_Issues#125]
During game startup Tree Plant fails with error
`  12.730 Error ModManager.cpp:1024: Failed to load mod "TreePlant": __TreePlant__/data-final-fixes.lua:3: __TreePlant__/prototypes/overrides.lua:8: bad argument #1 to 'insert' (table expected, got nil)
  12.733 Loading mod core 0.0.0 (data.lua)
  12.779 Checksum for core: 2304860305
  12.803 Error ModManager.cpp:1024: Error in assignID, recipe-category with name 'crafting' does not exist.`

No issue without Dectorio loaded

[Here is log of just Dectorio & Tree Plant](https://pastebin.com/YyLPE7ZW)

**Comment by ReikaKalseki** [comment]
Fixed.
