### ISSUE TITLE
Error loading AutoTrainDepot

### ISSUE THREAD

**Issue by Haggle1996** [ReikaKalseki/Reika_FactorioMods_Issues#128]
When trying to add AutoTrainDepot, I'm receiving the following:

![image](https://user-images.githubusercontent.com/11808184/47606988-be60a180-d9d7-11e8-927d-f08d052a0de2.png)

In the process of debugging, I disabled all mods except for AutoTrainDepot and still receive the error. This appears to be a duplicate of #113 which you previously marked as closed and fixed.

[Relevant Log](https://gist.github.com/Haggle1996/d4a4b9c75927cf5541549b9700231c9a)

**Comment by ReikaKalseki** [comment]
Then update the original issue - it has been reopened.
