### ISSUE TITLE
Crash on new game plus

### ISSUE THREAD

**Issue by Eind7286** [ReikaKalseki/Reika_FactorioMods_Issues#129]
Crashing when try to create new game from existing game usding new game plus mod. (https://mods.factorio.com/mod/NewGamePlus).
thanks.

![20181101180736_1](https://user-images.githubusercontent.com/42410353/47852766-595ddf00-de0f-11e8-9963-6db65c1fb2da.jpg)

**Comment by ReikaKalseki** [comment]
Neither of those mods are mine.
