### ISSUE TITLE
Geothermal Energy 2 is unresearchable

### ISSUE THREAD

**Issue by Ratgrot** [ReikaKalseki/Reika_FactorioMods_Issues#13]
(moved from factoriomod site discussion)

http://i.imgur.com/CwQEIsz.png
As you can see, I've completed all of the research that it wants me to but its still unavailable. If I mouse over a Geo-heat exchanger I see "Geothermal> Endgame Combat> Squeak Through" and am unsure how to check for any other conflicts that would not cause an outright error but still block research.
I've tried starting a new game with Endgame combat and Squeak through disabled but the same issue stands.
Am I missing some hidden requirement?

**Comment by ReikaKalseki** [comment]
I could not do this if I wanted to, and I have researched it before, including in my current map. Something else is wrong.

**Comment by ReikaKalseki** [comment]
Does it happen in a fresh map?

**Comment by Aubog007** [comment]
What other mods do you have? Because some mods completely hide technologies while other mods still rely on those technologies and they remain invisible and unable to be researched. Angels is notorious for this.

**Comment by Ratgrot** [comment]
It appears that Methane Processing (https://mods.factorio.com/mods/Pithlit/methane-processing) breaks certain oil based mods. and Geothermal needs Oil Processing and Advanced oil processing research (which methane seems to completely disable)

Removed Methane and started a new game with angels and all of bobs, works perfectly now.

**Comment by ReikaKalseki** [comment]
That is for him to fix, since breaking massive numbers of mods by simply removing a core game element with no replacement nor handling of its dependents is clearly neither prudent nor well-reasoned.
