### ISSUE TITLE
Radio Network causing error loading with Xander Mods.

### ISSUE THREAD

**Issue by morcup** [ReikaKalseki/Reika_FactorioMods_Issues#130]
I tried adding this mod in to the mods I am currently using (Xander and some QOL

Here is the error:

![unknown](https://user-images.githubusercontent.com/35850588/48484415-af516000-e7db-11e8-98fa-06a55b88dd28.png)

Here is my mods list:

![mods](https://user-images.githubusercontent.com/35850588/48484446-cabc6b00-e7db-11e8-991b-f70851376ed0.png)

I tried taking out the th-xm-hotfix mod (fixes some issues in Xander mod), but to no avail.  I'm not really sure what it could be, but let me know if I can provide any more useful information.

Thanks,
morcup

**Comment by ReikaKalseki** [comment]
One of the dependencies appears to not be conditional.

**Comment by morcup** [comment]
A guy on my discord took a look at it, and it looks like it checks if angel's or bob's is installed.  He changed what it checks to make it compatible for Xander Mod.  I was able to load the game and open up a save I had.  Unfortunately, we are not to blue science yet, so I have not researched/tried them out just yet.

Here is the modified file, if you would like to look at it:

[RadioNetwork_1.0.164.zip](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/2586184/RadioNetwork_1.0.164.zip)

Thanks for your help.

**Comment by ReikaKalseki** [comment]
Done.
