### ISSUE TITLE
FTweaks 	1.0.164 startup crash Error in assignID, recipe-category with name 'crafting' does not exist

### ISSUE THREAD

**Issue by GaistH** [ReikaKalseki/Reika_FactorioMods_Issues#131]
43.303 Error ModManager.cpp:1024: Failed to load mod "FTweaks": FTweaks/data-updates.lua:1: FTweaks/prototypes/overrides.lua:682: attempt to index field '?' (a nil value)
  43.305 Loading mod core 0.0.0 (data.lua)
  43.692 Checksum for core: 2304860305
  43.714 Error ModManager.cpp:1024: Error in assignID, recipe-category with name 'crafting' does not exist.

For reference, line 682 is:
data.raw.ammo["flamethrower-ammo"].ammo_type[2].action = data.raw.ammo["flamethrower-ammo"].ammo_type[1].action --because it was nerfed to garbage

[factorio-current.log](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/2587163/factorio-current.log)

**Comment by ReikaKalseki** [comment]
This does not happen for me - what other mods do you have?

**Comment by GaistH** [comment]
Here's the modlist:
[mod-list.txt](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/2596716/mod-list.txt)

**Comment by ReikaKalseki** [comment]
That is a huge list - you will need to try removing mods to see which is triggering it.
