### ISSUE TITLE
Error in starting a new world

### ISSUE THREAD

**Issue by Tealc-1** [ReikaKalseki/Reika_FactorioMods_Issues#134]
Error in starting a new world:

__EasyCreative__/control.lua:52: attempt to call global 'addCommands' (a nil value)

**Comment by ReikaKalseki** [comment]
[This makes no sense](https://i.imgur.com/n4G6KMj.png). What is in line 52 of the file for you?

**Comment by Tealc-1** [comment]
Yeah, I don't know why it doesn't make sense...

Tried downloading and reinstalling.

I will add that I am trying with version 1.0.180. Have tried with other mods installed and no other mods installed, gets the same error each time.

I took a screenshot of the code for you around that line, hope that helps?

https://imgur.com/a/gUvkiwz

If not let me know what other details you may need to help.

Thanks

EDIT/Update. Okay, so I just noticed the link for your SS, compared it to mine and seems that there is a rogue line in there. I have removed this and the game now loads with the mod installed, no errors. Im not sure yet if the mod is doing what it is meant to though...

Final Update: The mod is definitely loading now with no error but when starting a new world its not removing all the trees, rocks etc... Have messed around trying a few different things but unless I am missing something it doesn't seem to be working for me.

**Comment by ReikaKalseki** [comment]
> EDIT/Update. Okay, so I just noticed the link for your SS, compared it to mine and seems that there is a rogue line in there.

You are either using an old version - somehow - or that file was edited.

> Final Update: The mod is definitely loading now with no error but when starting a new world its not removing all the trees, rocks etc... Have messed around trying a few different things but unless I am missing something it doesn't seem to be working for me.

You have to use the commands.

**Comment by PhilBeaudoin** [comment]
Just downloaded the mod today and had the same error. My line 52 was:

addCommands()

Removing it worked. Maybe a bad version got uploaded to the mod server?

**Comment by ReikaKalseki** [comment]
Possibly.

**Comment by Tealc-1** [comment]
> Just downloaded the mod today and had the same error. My line 52 was:

Glad to see I am not he only one who had the issue.

> You are either using an old version - somehow - or that file was edited.

Definitely not an old version and it wasn't previously edited.

> You have to use the commands.

Please excuse my ignorance, but what are the commands? There are none listed on the download page, that I can see?

**Comment by ReikaKalseki** [comment]
> Please excuse my ignorance, but what are the commands? There are none listed on the download page, that I can see?

`initCreative`.
