### ISSUE TITLE
[Endgame Combat] "Turret Alert" audio ignore audio settings

### ISSUE THREAD

**Issue by JanDornbusch** [ReikaKalseki/Reika_FactorioMods_Issues#135]
Well the alert sounds seems to ignore all game audio settings and play much loud/annoying any chance to fix it? Or at least exchange the warning sounds with something more decent?

**Comment by ReikaKalseki** [comment]
> Well the alert sounds seems to ignore all game audio settings

I doubt I could make sounds ignore the game's settings if I wanted to.


And the alerts are supposed to be attention-grabbing; that is the point of an alert.

**Comment by PrestonTaylor** [comment]
Weather or not you think you can if you want to, it's done. What JanDornbusch says is correct. Your alerts are not abiding by the alert volume slider in audio settings. The new turret alerts have made the mod unplayable, I personally tried turning off repeat alerts and it's now made my save game alert on low ammo every time a turret fires or aims or tries to fire..... It's enough to make ears bleed. even after changing the repeat setting back I still get the alerts every action. /muteAlerts 9999 does nothing


Also all alert settings should not be startup settings. They should be per player settings.

**Comment by ReikaKalseki** [comment]
> Weather or not you think you can if you want to, it's done. What JanDornbusch says is correct. Your alerts are not abiding by the alert volume slider in audio settings.

Again, I am dubious that such a thing is even possible, and given that there are a number of other potential, far more likely explanations - such as perceived and actual volume not being identical - I am not inclined to accept this claim.

`/muteAlerts 9999 does nothing`

Probably because that is not a valid way to use that command. Things tend to not work when used incorrectly.

> Also all alert settings should not be startup settings. They should be per player settings.

This is a valid point.

**Comment by JanDornbusch** [comment]
I've gone a little bit more in detail too. It seems the audio setting not beeing ignored completely but they are applied in an unexpected way. All play_sounds commandy seems to map to game-effects. 

In my case the base is huge and mostly runs at 10 UPS (biters eating up my ups). Now you can imagine how many attacks comming in and how many sounds (not much as a second is stretched to 6secs already) are played per second. My alert audio level is as ~25% while my effects are at ~60% comparing base alerts with the one of this mod was the reason to guess they ignore audio settings. 


Further more I've asked in factorio forum if an extension of modding api could be possible (adding a type to play_sounds command - [Forum](https://forums.factorio.com/viewtopic.php?f=28&t=64335)). I'm not sure if they not wanted to understand me or if they just think different - it seems to be preferred to bring in own audio settings for each mod - something like: `play_sounds(... volume_modifier=(factor * soundlevel_for_alerts / 100))` where your mod options give the soundlevel_for_*.

They mentioned the type of audi setting to be used is stored in the prototype but I guess that will not help much here.

**Comment by ReikaKalseki** [comment]
> My alert audio level is as ~25% while my effects are at ~60% comparing base alerts with the one of this mod was the reason to guess they ignore audio settings.

That almost sounds like 'sound stacking', which is another potential explanation for perceived audio volume inflexibility.
