### ISSUE TITLE
0.17

### ISSUE THREAD

**Issue by PaladinFallen** [ReikaKalseki/Reika_FactorioMods_Issues#136]
Are you going to be updating any of your mods to 0.17? Just wondering cause i use several of them and I would seem lost without them.

**Comment by moon6969** [comment]
I've made a 0.17 version of this for another Factorian as discussed here...
https://forums.factorio.com/viewtopic.php?f=25&t=67664

You can download the updated version here: (Link expires in one month)...
https://filebin.net/sslxa1m1iyywx364

**Comment by ReikaKalseki** [comment]
On what basis did you think it would be acceptable to take the mod, update it yourself with no contact with the real author whatsoever, and then encourage people to use that in place of the real version?
