### ISSUE TITLE
Thaumaturgic Machination crash on startup

### ISSUE THREAD

**Issue by mineblow** [ReikaKalseki/Reika_FactorioMods_Issues#137]
Logfile is To long for me to paste
[factorio-previous.log](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/2964368/factorio-previous.log)

**Comment by ReikaKalseki** [comment]
`1615.328 Error ModManager.cpp:1263: Error while loading recipe prototype "artillery-targeting-remote-aspect-extraction" (recipe): Value must be a string in property tree at ROOT.recipe.artillery-targeting-remote-aspect-extraction.icons[1].icon`

This looks very much like an error on their end.

**Comment by mineblow** [comment]
when the crash happens it tells me that Thaumaturgic Machination has errored, loads up fine with it removed can you tell me what mod is causing it? not very good with error logs on factorio

**Comment by ReikaKalseki** [comment]
It looks like he is not correctly parsing item icons - specifically handling icon arrays - and some mods add such items.
