### ISSUE TITLE
Dewpoint Aggregator 0.17 pollution 4000/sec, too much water generation

### ISSUE THREAD

**Issue by redzefyr** [ReikaKalseki/Reika_FactorioMods_Issues#139]
I waited for this update so much, I applied it right away.
It seems something goes wrong with "emissions" part change.
pollution is too high (4000/sec) and water generation is faster than I remembered.
( I use this with your geothermal mod. )

**Comment by ReikaKalseki** [comment]
Does it only affect the DPA?

**Comment by ReikaKalseki** [comment]
Fixed.
