### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TheSAguy** [ReikaKalseki/Reika_FactorioMods_Issues#14]
Got this error on startup.
[ERROR](http://i.imgur.com/EVtpBOH.png)
Worked when removing this mod.

**Comment by ReikaKalseki** [comment]
A result with a nil name? I suspect that is a bug on the other mod's end. Try removing other mods - in particular 5Dim and BioIndustries - to see the cause.

**Comment by zqr95518** [comment]
Have the same error. Use TreePlant_0.0.12 don't have this error. The latest seems conflict wIth his Bio_Industries_1.8.5.

**Comment by ReikaKalseki** [comment]
How does Bio Industries modify trees? Is the developer on GitHub?

**Comment by TheSAguy** [comment]
It does this:
"
	
	--- Trees Give Random 1 - 6 Raw Wood.
	for _,tree in pairs(data.raw["tree"]) do
		tree.collision_box = {{-0.05, -0.05}, {0.05, 0.05}}	
		if not (tree.name =="dead-tree" or tree.name == "dry-tree" or tree.name == "green-coral" or tree.name == "dead-grey-trunk" or tree.name == "dry-hairy-tree" or tree.name == "dead-dry-hairy-tree") then  
		tree.minable = 	{mining_particle = "wooden-particle", mining_time = 1.5, results = {{type = "item", name = "raw-wood", amount_min = 1, amount_max = 6},}}
		end
	end
	

"

**Comment by ReikaKalseki** [comment]
Oh, it has `results` instead of `result`. That can easily be handled, but why is it acting like only the `name` field of `result` was nulled out?

**Comment by ReikaKalseki** [comment]
So it does have a name, then. However, that ending comma - with no entry after it - makes me somewhat suspicious that it may be creating an unintentional second entry (with all-nil values). Can you try removing it?

`{mining_particle = "wooden-particle", mining_time = 1.5, results = {{type = "item", name = "raw-wood", amount_min = 1, amount_max = 6} --> , <-- }}`

**Comment by TheSAguy** [comment]
I'll give it a try tonight.

**Comment by TheSAguy** [comment]
Same crash after removing it.
[https://github.com/TheSAguy/Bio_Industries](url)

**Comment by ReikaKalseki** [comment]
OK, I clearly need to put some handling in on my end.

**Comment by ReikaKalseki** [comment]
Try 1.0.20.

**Comment by zqr95518** [comment]
It looks OK. Don't come out any error.
