### ISSUE TITLE
startup error due to coal being borked (dirty mining)

### ISSUE THREAD

**Issue by SpaceCat-Chan** [ReikaKalseki/Reika_FactorioMods_Issues#140]
When you start up it crashes,
it seems that this is because dirty-ore-coal is borked

adding 
`	item.fuel_emissions_multiplier = nil` to line 140 in ore.lua fixes this

![image](https://user-images.githubusercontent.com/49094338/55275456-ae325280-52e6-11e9-8cdb-7705c61d7cfe.png)

**Comment by PaladinFallen** [comment]
This issue can be closed, your version [ DirtyMining_1.17.6 ] fixed this.
