### ISSUE TITLE
DirtyMining conflict with Creative Mod

### ISSUE THREAD

**Issue by VoidPhantom** [ReikaKalseki/Reika_FactorioMods_Issues#141]
When DirtyMining and [Creative Mod](https://mods.factorio.com/mod/creative-mod) are both enabled, Factorio displays the following error on startup:
![screenshot](https://user-images.githubusercontent.com/8202373/55634997-5acd7200-57c8-11e9-9948-ac331e8d268a.png)

Log contents: https://gist.github.com/VoidPhantom/f6ff0f11d319c7b5eac86d8e605ea5bb

(The error does not occur with only one of these mods enabled.)

**Comment by ReikaKalseki** [comment]
Is he modifying recipes or adding stone to ores' drops?

**Comment by PaladinFallen** [comment]
This issue can be closed, Creative Mod has been updated and I can't reproduce the error with just those two mods running.
