### ISSUE TITLE
Isue due world Generation with mod "Orevehaul" in PVP Scenario.

### ISSUE THREAD

**Issue by SirWillam** [ReikaKalseki/Reika_FactorioMods_Issues#144]
Hey Reika,

me and my friends planning to play a round with your mod "Orevehaul" and some bobmods. But we want Factions and splittet Technology and own starter area. As you think ... PVP Scenario. But as good as it works in normal multiplayer and singleplayer with your mod, as bad is it in PVP. In Singleplayer all ressources spawn as they are supposed to do. But in PVP there are tungsten patches with 30G and more in spawn and huge nests. Can you help us to support pvp in factorio with your mod?

**Comment by ReikaKalseki** [comment]
So you need the ability to specify multiple "origins"?

**Comment by SirWillam** [comment]
If this isnt possible maybe is there a way to start an normal mp sessions(there your mod work), and make teams and seperate technology? (If there is no other way we can ignore the factor, that we all have the same spawn/origin)

**Comment by SirWillam** [comment]
And we play in Factorio Version 0.16.51 and Oreverhaul_1.0.112

**Comment by ReikaKalseki** [comment]
> And we play in Factorio Version 0.16.51 and Oreverhaul_1.0.112

I have already updated to 0.17 - this feature will not be backported.

**Comment by SirWillam** [comment]
We managed to make an normal mp round with pvp settings(via commandline). If you can do it for 0.17, okay. But i think we can play without your fix. We dont wanna update now.

**Comment by ReikaKalseki** [comment]
Thinking about this, there is no performant way to do it, because you need to now calculate distance from *every* origin for every ore tile, not just once. These checks are expensive.
