### ISSUE TITLE
Geothermal with uranium byproduct not working properly.

### ISSUE THREAD

**Issue by Goldobsidian** [ReikaKalseki/Reika_FactorioMods_Issues#147]
This is my current Geothermal set up for a Geothermal vent with Uranium Ore by product. The Miner does not recognize or change the fluid output to be correct, which is preventing the pipe from being connected to the heat exchanger. The Miner is also not outputing anything no matter how much water or electricity is supplied. I have tested the standard geothermal vents with no byproducts and they seem to be working properly. I havent found any other byproduct vents in my world so I cannot test those for you.

I removed any mods that effected the Geothermal vent and miner (Bobs Ores and Bobs Miners where the only two listed). It might be a conflict with another mod still as I have not disabled all mods and tested.

![geotherm](https://user-images.githubusercontent.com/18736937/55722930-7dc07780-59bc-11e9-8361-100888a7668b.png)

**Comment by ReikaKalseki** [comment]
Does it not produce heated water at all - as claimed in #143 - or just produce "plain" water?

**Comment by Goldobsidian** [comment]
The well is not outputting any heated water, fluid, or material at all. Its also not recognizing the "colored" water as in claim #143 for a byproduct, As you can see in the image the out pipe has a different symbol then the heat exchangers input.

I apologize for making a duplicate post to 143 if this was the issue they where speaking of. I was not sure what they ment with their post.

**Comment by Tiefkuehlpizze** [comment]
I can confirm that the coloured patches don't work.
Their output is not the expected chemical impure water and the machine's status is just "No minable resources". The red patches are working fine and produce pure hot water.

Tested with only Geothermal and Alien Biomes enabled.

![factorio](https://user-images.githubusercontent.com/5569743/56528820-1411a300-6550-11e9-99b5-418a39aebd81.jpg)

 
> "But it costs nothing consumable except for water, **and pollutes very little.**"

I think 16k/m is not the intended value. :smile:

**Comment by ReikaKalseki** [comment]
Fixed.
