### ISSUE TITLE
Geothermal is not compatible with Squeak Trough

### ISSUE THREAD

**Issue by OmegaPhi115** [ReikaKalseki/Reika_FactorioMods_Issues#148]
When I load the game with Squeak Trough I get this error message:
![rfvqwvdvsdfw](https://user-images.githubusercontent.com/45884990/56051731-ee1a2080-5d4f-11e9-8ee1-dc6c6e1d6a5d.PNG)

**Comment by ReikaKalseki** [comment]
This only happens with SqueakThrough installed?

**Comment by Goldobsidian** [comment]
Im running Geo and Squeak with no issues at all. I think it was an issue with the game version.

**Comment by KyuubiYoru** [comment]
I got the same Error with only Geothermal installed, Game version 0.17.34

![grafik](https://user-images.githubusercontent.com/33806787/56851041-c0fe6e00-690a-11e9-8f94-318d61a409e4.png)

**Comment by ReikaKalseki** [comment]
In which case #138
