### ISSUE TITLE
Factor-I/O BUG

### ISSUE THREAD

**Issue by JaJe92** [ReikaKalseki/Reika_FactorioMods_Issues#149]
Hello Reika,
Using a Nearby Enemy count detector with a programmable speaker is not working. 
Basically the Nearby enemy count detector has an output once enemy bitters are nearby but the speaker won't recognize anything. Works very well with other logistics such as power switch.

**Comment by PaladinFallen** [comment]
I also can confirm this, I have tried everything that I could for a work around and I couldn't do anything in the game.

**Comment by ReikaKalseki** [comment]
I have no idea why I tagged this with "bug"; I do not have that level of control over the circuit network, only the ability to set signals. Either you have your connections/settings wrong on the speaker or there is something different about the programmable speaker in the base game.
