### ISSUE TITLE
When I used this mod target item in the game, I got an error.

### ISSUE THREAD

**Issue by GimoXagros** [ReikaKalseki/Reika_FactorioMods_Issues#15]
Error while runnung event
EndgameCombat::on_tick(ID 0)
EndgameCombat/orbital-strikes.lua:82:attempt to call global 'getDistance'(a nil value)

And I have two question. First, Is this mod compatible with Orbital Ion Cannon_1.5.2 mod?
Seconds, Is shield dome still in trouble?

![Orbital Ion Cannon](https://user-images.githubusercontent.com/30635204/29387650-f5e15bd6-831b-11e7-8869-5b1e2ea07a72.JPG)

![Dome](https://user-images.githubusercontent.com/30635204/29387645-eeda01da-831b-11e7-887d-81edc4801480.JPG)

**Comment by ReikaKalseki** [comment]
It should be compatible with Ion Cannon, though it would make it redundant.

**Comment by GimoXagros** [comment]
Oh, thank you. It is a satisfactory answer.

**Comment by ReikaKalseki** [comment]
Both are fixed.
