### ISSUE TITLE
Endgame Combat .17

### ISSUE THREAD

**Issue by timer67** [ReikaKalseki/Reika_FactorioMods_Issues#150]
I decided to piece together the errors which are preventing Endgame Combat from loading in .17

Unfortunately, they are more than I can handle as the Sprite Code is beyond my understanding of Factorios code.

If I complied the errors as I came to them, would that help you in updating the mod?

**Comment by ReikaKalseki** [comment]
Yes, it would.

**Comment by timer67** [comment]
**rangeturrets.lua -Line 30: flag ""hide-from-bonus-gui" no longer exists.**
**Flags "goes-to-quickbar" and "goes-to-main-inventory" need removing from these files.**
EndgameCombat_1.0.180\prototypes\orbital.lua (4 hits)
	Line 8:     flags = {"goes-to-quickbar"},
	Line 19:     flags = {"goes-to-main-inventory"},
	Line 29:     flags = {"goes-to-quickbar"},
	Line 40:     flags = {"goes-to-quickbar"},
EndgameCombat_1.0.180\prototypes\radar.lua (1 hit)
	Line 8:     flags = {"goes-to-quickbar"},
EndgameCombat_1.0.180\prototypes\rangeturrets.lua (1 hit)
	Line 84: 			flags = {"goes-to-main-inventory"},
  EndgameCombat_1.0.180\prototypes\tank.lua (3 hits)
	Line 94:     flags = {"goes-to-quickbar"},
	Line 106:     flags = {"goes-to-main-inventory"},
	Line 139:     flags = {"goes-to-main-inventory", "hidden"},
  EndgameCombat_1.0.180\prototypes\turrets.lua (9 hits)
	Line 54:     flags = {"goes-to-quickbar"},
	Line 65:     flags = {"goes-to-quickbar"},
	Line 76:     flags = {"goes-to-quickbar"},
	Line 87:     flags = {"goes-to-quickbar"},
	Line 98:     flags = {"goes-to-quickbar"},
	Line 109:     flags = {"goes-to-quickbar"},
	Line 120:     flags = {"goes-to-quickbar"},
	Line 131:     flags = {"goes-to-quickbar"},
	Line 142:     flags = {"goes-to-quickbar"},
  EndgameCombat_1.0.180\prototypes\walls.lua (4 hits)
	Line 8:     flags = {"goes-to-quickbar"},
	Line 19:     flags = {"goes-to-quickbar"},
	Line 30:     flags = {"goes-to-quickbar"},
	Line 41:     flags = {"goes-to-quickbar"},
EndgameCombat_1.0.180\prototypes\item\biter-flesh.lua (2 hits)
	Line 10:     flags = {"goes-to-main-inventory"},
	Line 23:     flags = {"goes-to-quickbar"},
EndgameCombat_1.0.180\prototypes\item\cannon-turret-ammo.lua (4 hits)
	Line 20:     flags = {"goes-to-main-inventory"},
	Line 55:     flags = {"goes-to-main-inventory"},
	Line 90:     flags = {"goes-to-main-inventory"},
	Line 125:     flags = {"goes-to-main-inventory"},
EndgameCombat_1.0.180\prototypes\item\flamethrower2.lua (1 hit)
	Line 8:     flags = {"goes-to-main-inventory"},
EndgameCombat_1.0.180\prototypes\ammo.lua (11 hits)
	Line 8:     flags = {"goes-to-main-inventory"},
	Line 65:     flags = {"goes-to-main-inventory"},
	Line 104:     flags = {"goes-to-main-inventory"},
	Line 148:     flags = {"goes-to-main-inventory"},
	Line 181:     flags = {"goes-to-main-inventory"},
	Line 214:     flags = {"goes-to-main-inventory"},
	Line 247:     flags = {"goes-to-main-inventory"},
	Line 279:     flags = {"goes-to-main-inventory"},
	Line 312:     flags = {"goes-to-main-inventory"},
	Line 345:     flags = {"goes-to-quickbar"},
	Line 383:     flags = {"goes-to-quickbar"},
EndgameCombat_1.0.180\prototypes\armor.lua (3 hits)
	Line 38:     flags = {"goes-to-main-inventory"},
	Line 150:     flags = {"goes-to-main-inventory"},
	Line 196:     flags = {"goes-to-main-inventory"},
EndgameCombat_1.0.180\prototypes\dome.lua (1 hit)
	Line 167: flags = {"goes-to-quickbar"},
  EndgameCombat_1.0.180\prototypes\misc.lua (1 hit)
	Line 49: flags = {"goes-to-quickbar"},
**Error while loading entity prototype "tough-gate" (gate): Key "width" not found in property tree at ROOT.gate.tough-gate.wall_patch**

**Comment by timer67** [comment]
[prototypes.zip](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/3099638/prototypes.zip)
All the fixes I've made so far to get to the current error

The last "width" error has stumped me. I will keep trying to work on it. 
If you solve it before I can continue going after applying the fix

**Comment by ReikaKalseki** [comment]
0.17 completely changed wall sprites; I need to redo them.

**Comment by timer67** [comment]
I fixed the walls error, still encountering other errors so i will continue to work.

**Comment by timer67** [comment]
raw-wood changed to wood

prototypes\recipe\recipe-updates.lua (2 hits)
Line 55: table.insert(data.raw.recipe["sticky-cheap"].ingredients, {type = "item", name = "raw-wood", amount = 1})
Line 56: table.insert(data.raw.recipe["sticky-expensive"].ingredients, {type = "item", name = "raw-wood", amount = 2})

science-pack-1 Changed to automation-science-pack
science-pack-2 Changed to logistic-science-pack
science-pack-3 Changed to chemical-science-pack
high-tech-science-pack -> utility-science-pack
191 changed, will link changed.

Technology with name "flamethrower-damage-3" does not exist 
Flamethrower2.lua line 14
Commented out the prerequistie for now, unsure of errors source. 

Technology with name 'electric-energy-accumulators-1' does not exist.
recipe-updates.lua line 138
Changed to electric-energy-accumulators

 File not found "acid-projectile-purple-shadow.png"
File changed to ""__base__/graphics/entity/acid-projectile/hr-acid-projectile-shadow.png"

**Comment by timer67** [comment]
That will be my last update, i have hit an error i cannot solve as its far beyond me.

I hope my efforts have helped you update this mod quicker.
I look forward to reinstalling it in .17

Timer.
![Capture](https://user-images.githubusercontent.com/11606694/56545593-f7856300-656f-11e9-9b62-e7bbdd592c31.JPG)

**Comment by timer67** [comment]
Ignore my deleted comment.
I fixed all the bugs, just need to test it but your mod should be updated to .17
[prototypes.zip](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/3105556/prototypes.zip)

**Comment by timer67** [comment]
![Capture](https://user-images.githubusercontent.com/11606694/56549289-49cb8180-657a-11e9-80a9-8ec1f2635a77.JPG)

Bug on launch

**Comment by timer67** [comment]
Looks like the Launch.Lua code was referencing two dead commands in its for loop at line 420.

[control.zip](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/3105581/control.zip)

**Comment by timer67** [comment]
The mod now runs with no errors :)

**Comment by shadoxxhd** [comment]
Using your 2nd prototypes.zip and control.zip I got issues with the power-armor technology - apparently, the "power-armor-2" research was renamed to "power-armor-mk2".

**Comment by shadoxxhd** [comment]
When using the manual orbital strike designator, the game (soft-)crashes due to a reference to defines.inventory_player_main instead of defines.inventory.character_main (control.lua:523).

**Comment by ReikaKalseki** [comment]
Done.
