### ISSUE TITLE
[Fast Furnaces] Failed to load mod after changing modOption - Prod5 module collision

### ISSUE THREAD

**Issue by shadoxxhd** [ReikaKalseki/Reika_FactorioMods_Issues#151]
"Failed to load mods: Error in assignID, technology with name 'effectivity-module-5' does not exist.
Source: fast-drills (technology).
Mods to be disabled: FastFurnaces

In prototype/recipe/drill-recipe-updates.lua you only check whether the **item** effectivity-module-5 exists, and if it does add a requirement for the effectivity-module-5 **technology**.
Since the Darkstar Utilities mod adds the item without adding a technology with this name, this results in inter mod incompatability.

**Comment by ReikaKalseki** [comment]
Fixed.
