### ISSUE TITLE
Biolumnescence plants do not glow (in 0.17?)

### ISSUE THREAD

**Issue by DaleStan** [ReikaKalseki/Reika_FactorioMods_Issues#153]
When I start a new game and wait for nighttime, the plants from Bioluminescence do not glow, as seen here.
![image](https://user-images.githubusercontent.com/21223975/57053821-75c3c280-6c5e-11e9-92eb-eeebfd30e8b2.png)

I expected to see a glow akin to the glows in https://i.imgur.com/bRAFlmP.jpg

Speculation: My current guess is that something changed in 0.17 that broke this. The glow appears as expected in 0.16.51, but neither 0.17.34 (latest) nor 0.17.20 (oldest 0.17 available) show glows.

**Comment by ReikaKalseki** [comment]
Yes, game systems changed and Bioluminescence needs to be updated to account for this.

**Comment by Orriss** [comment]
any news? =(  this mod really add lots of atmosphere to the night alien world, thx for the work!

**Comment by ReikaKalseki** [comment]
I am working on the 0.17 update right now, and have been for a few days. It should not be much longer.

**Comment by ReikaKalseki** [comment]
![https://i.imgur.com/PJ85RYf.jpg](https://i.imgur.com/PJ85RYf.jpg)
