### ISSUE TITLE
[Geothermal] Insane pollution

### ISSUE THREAD

**Issue by KyraDragoness** [ReikaKalseki/Reika_FactorioMods_Issues#155]
Greetings,

I came here to report an issue.
Despite the mod being up to date, a Geothermal Well will generate 16000 pollution/min, which is way, way higher than my whole factory.

I took a glance at its pollution formula and saw 
`emissions_per_second_per_watt = 0.1 / 1.5`
It is indeed the root of the problem as a Geothermal Well needs 240 kW and explains why such amounts are reach.
Of course, I only had to tweak the value to a more decent amount to solve the problem, yet it may be of use to update the mod so any player who downloaded it can benefit the fix.

Regards

**Comment by ReikaKalseki** [comment]
I am waiting on the game versions to stabilize first.

**Comment by PaladinFallen** [comment]
@KyraDragoness what was the values that you ended up using, cause a reference would be awesome.

**Comment by KyraDragoness** [comment]
@PaladinFallen I used this value

> emissions_per_second_per_watt = 0.1 / 1500

So the Geothermal Well generates 16 pollution/min which is more decent. I don't know if it's balanced but at least it doesn't generates as much as 4 whole factories.

**Comment by ghost** [comment]
I'm seeing pollution values of 32,000 / m from the geothermal station, which makes it basically unusable due to the effects on evolution and biter attacks.

**Comment by PaladinFallen** [comment]
@Edge-Walker 

[Look at this](https://github.com/ReikaKalseki/Geothermal/pull/4/commits/171a607ae1b195644cea06e9946a3328e7bc8899), this will be your best fix until he has time to revise his code. Foe reference look towards the end of #147 and you'll see Tiefkuehlpizze already came up with a solution.

**Comment by ReikaKalseki** [comment]
Fixed.
