### ISSUE TITLE
Dirty Mining (Issue with "dirty-ore-coal")

### ISSUE THREAD

**Issue by PaladinFallen** [ReikaKalseki/Reika_FactorioMods_Issues#156]
This happen when Bio Industries updated....

> 
> Version: 0.17.20
> Date: 5. 20. 2019
> 
> Features:
> - Updated "fuel_emissions_multiplier" of common items with a fuel value
> - Angels Charcoal must be made in a Cokery
> 
> Bugfix:
> - Compatibility with FARL updated. added "defines.events.script_raised_built" & "defines.events.script_raised_destroy"

 ______________________________________________________________

[Picture Reference Here](https://i.ibb.co/41FgxsZ/20190520165551-1.jpg)

_______________________________________________________________

I got in touch with the creator of Bio Industries this is what he stated,

> Can you please report this to DirtyMining. I tried to fix this, but not getting it to work
> 
> a quick fix if you want to just the latest version is to comma out line 298 of: \prototypes\Bio_Farm\compatible_recipes.lua
> So add "--" tot the front of
> "BI_Functions.lib.fuel_emissions_multiplier_update("coal", 2.00)"

**Comment by TheSAguy** [comment]
I've tried to add the below, but it does not seem to fix this issue. I added it to "data.lua",  "data-updates.lua" & "data-final-fixes.lua" Unsure how to resolve.

"
if mods["DirtyMining"] then
	data.raw.item["coal"].fuel_category = "chemical"
	data.raw.item["coal"].fuel_value = "4MJ"
	if data.raw.item["dirty-ore-coal"] then
		data.raw.item["dirty-ore-coal"].fuel_category = "chemical"
		data.raw.item["dirty-ore-coal"].fuel_value = "4MJ"
		data.raw.item["dirty-ore-coal"].fuel_emissions_multiplier = 2.00
	end
	
end
"

Please let me know how I can fix it.
Thanks.

**Comment by PaladinFallen** [comment]
#140 @TheSAguy 

Found the problem in another issue request. I add the code into the ores.lua at line 140 and now the Bio Industries mod works perfect now; not on your end bro.
