### ISSUE TITLE
DirtyMining incompatibility with Space Exploration

### ISSUE THREAD

**Issue by XenoLupus** [ReikaKalseki/Reika_FactorioMods_Issues#157]
When starting DirtyMining with Space Exploration I get the following error:
Failed to load mods: The given sprite rectangle (left_top=0x0, right_bottom=64x 64) is outside the actual sprite size (left_top=0x0, right_bottom=32x32), Sprite name: __DirtyMining__/graphics/icons/dirty_overlay.png
If this is being used as an icon you may need to define the icon_size property.: __DirtyMining__/graphics/icons/dirty_overlay.png

**Comment by ReikaKalseki** [comment]
Already fixed.

**Comment by XenoLupus** [comment]
Confirm fix.

**Comment by ReikaKalseki** [comment]
What?

**Comment by XenoLupus** [comment]
I can confirm that the fix works. :-)
