### ISSUE TITLE
Geothermal and Angels Refining Load bug

### ISSUE THREAD

**Issue by DofD10** [ReikaKalseki/Reika_FactorioMods_Issues#158]
When loading the most current versions of Geothermal and Angels Refining this error cancels the loading process :
![factorio_FLlo1GUFFw](https://user-images.githubusercontent.com/18647086/58755178-7b6f2b00-84de-11e9-8dc6-f1f648479dcb.png)

Hope this is fixable as i love both mods!

Thanks for your time!

**Comment by Saevon** [comment]
This is more of a bug on Angel's Refining, it assumes liquids have only a "icon" but Geothermal uses a second one as an overlay.

I'm reporting the same issue on Angel's Refining with a fix ;)

**Comment by Saevon** [comment]
In fact it should already be fixed by angel (https://forums.factorio.com/viewtopic.php?f=185&t=25468&p=433752&hilit=geothermal#p433752)

**Comment by DofD10** [comment]
Thank you! :D
