### ISSUE TITLE
Endgame Combat crash on loading map

### ISSUE THREAD

**Issue by PlatinumFrog** [ReikaKalseki/Reika_FactorioMods_Issues#159]
While I was waiting for this mod to be 0.17 compatible I was using Rampant Arsenal, but now that this is updated, so I uninstalled Rampant Arsenal, and the installed the latest version of this, and Dragon Industries from this GitHub (I couldn't find it in the in-game mod menu), then I loaded my save and the game gave me this non recoverable error:

```
Error while running event EndgameCombat::on_tick (ID 0)
real number expected got nil.
stack traceback:
	__EndgameCombat__/control.lua:420: in function <__EndgameCombat__/control.lua:277>
stack traceback:
	[C]: in function 'get_inventory'
	__EndgameCombat__/control.lua:420: in function <__EndgameCombat__/control.lua:277>
```

**Comment by Ideachan** [comment]
![QQ截图20190607195118](https://user-images.githubusercontent.com/51479321/59099632-fa44e780-8966-11e9-99ce-b3a05439cc96.png)

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by numbernegative** [comment]
Still getting this error on latest version
