### ISSUE TITLE
ı got this error randomly after I placed some shield domes

### ISSUE THREAD

**Issue by sader22** [ReikaKalseki/Reika_FactorioMods_Issues#16]
http://imgur.com/a/Oel7x pls help

**Comment by zqr95518** [comment]
Have the same error when worm attach the shield.

**Comment by zqr95518** [comment]
Error while running event EndgameCombat::on_tick (ID 0)
__EndgameCombat__/shield-domes.lua:91: attempt to call global 'getDistance' (a nil value)

**Comment by ReikaKalseki** [comment]
#15
