### ISSUE TITLE
Bioluminecence incompatible.

### ISSUE THREAD

**Issue by Fr-Dae** [ReikaKalseki/Reika_FactorioMods_Issues#160]
Hello, you mod are pretty cool, but,

he are incompatible with some other mods.
**factorio** `0.17.35 b45219 Linux x64`
**ramplant,:** bitter don't glow, normal bitter spawn (he shouldn't)
**regeneratTerrain** crash https://image.noelshack.com/fichiers/2019/23/4/1559856011-2019-06-06-212725-1920x1080-scrot.png

and .. some other bugs
https://image.noelshack.com/fichiers/2019/23/4/1559855944-2019-06-06-230538-1920x1080-scrot.png
https://image.noelshack.com/fichiers/2019/23/4/1559855944-2019-06-06-230545-1920x1080-scrot.png

**Comment by Daebis** [comment]
> Hello, you mod are pretty cool, but,
> 
> he are incompatible with some other mods.
> **factorio** `0.17.35 b45219 Linux x64`
> **ramplant,:** bitter don't glow, normal bitter spawn (he shouldn't)
> **regeneratTerrain** crash https://image.noelshack.com/fichiers/2019/23/4/1559856011-2019-06-06-212725-1920x1080-scrot.png
> 
> and .. some other bugs
> https://image.noelshack.com/fichiers/2019/23/4/1559855944-2019-06-06-230538-1920x1080-scrot.png
> https://image.noelshack.com/fichiers/2019/23/4/1559855944-2019-06-06-230545-1920x1080-scrot.png

**Comment by Daebis** [comment]
> Hello, you mod are pretty cool, but,
> 
> he are incompatible with some other mods.
> **factorio** `0.17.35 b45219 Linux x64`
> **ramplant,:** bitter don't glow, normal bitter spawn (he shouldn't)
> **regeneratTerrain** crash https://image.noelshack.com/fichiers/2019/23/4/1559856011-2019-06-06-212725-1920x1080-scrot.png
> 
> and .. some other bugs
> https://image.noelshack.com/fichiers/2019/23/4/1559855944-2019-06-06-230538-1920x1080-scrot.png
> https://image.noelshack.com/fichiers/2019/23/4/1559855944-2019-06-06-230545-1920x1080-scrot.png

**Comment by Fr-Dae** [comment]
![2019-06-06-232840_1920x1080_scrot](https://user-images.githubusercontent.com/23202421/59067846-eb046200-88b2-11e9-91f6-6da289f9bae0.png)

**Comment by Fr-Dae** [comment]
if i desable only your mods, all works fine

**Comment by ReikaKalseki** [comment]
Bioluminescence does not change how biters work nor anything about terrain; those are not my issues. As for biters not glowing with Rampant installed, they probably have custom entity names which I need to add compatibility for.

**Comment by ReikaKalseki** [comment]
That compatibility has been added.
