### ISSUE TITLE
[End Game Combat] non-recoverable error

### ISSUE THREAD

**Issue by Ideachan** [ReikaKalseki/Reika_FactorioMods_Issues#161]
Just updated to the latest version of EGC today and installed the Dragon Industry but after enter the world for about 5 seconds this message popped up and it took me to menu after clicking confirm.
![QQ截图20190607195118](https://user-images.githubusercontent.com/51479321/59099236-eea4f100-8965-11e9-9fd6-68877409e16a.png)

**Comment by Ideachan** [comment]
Issue was previously addressed. Closing this one down.

**Comment by ReikaKalseki** [comment]
#159
