### ISSUE TITLE
[Endgame Combat] Startup Error: "No such technology titanium-processing"

### ISSUE THREAD

**Issue by hasezoey** [ReikaKalseki/Reika_FactorioMods_Issues#163]
```
Mods to disable:Failed to load mods: __EndgameCombat__/data-updates.lua:4: __EndgameCombat__/prototypes/recipe/recipe-updates.lua:17: No such technology titanium-processing!
stack traceback:
	[C]: in function 'error'
	__EndgameCombat__/prototypes/recipe/recipe-updates.lua:17: in function 'addPlateToTurret'
	__EndgameCombat__/prototypes/recipe/recipe-updates.lua:23: in main chunk
	[C]: in function 'require'
	__EndgameCombat__/data-updates.lua:4: in main chunk
stack traceback:
	[C]: in function 'require'
	__EndgameCombat__/data-updates.lua:4: in main chunk
```

[installed mods](https://gist.github.com/hasezoey/9db5954352fd5e62417ea311c56923d0)

(using version from mods.factorio)
Factorio Version: 0.17.45

**Comment by ReikaKalseki** [comment]
I take it you have some other non-bob mod adding titanium?

**Comment by hasezoey** [comment]
yes, All `Py-` mods

**Comment by ReikaKalseki** [comment]
Do they add a tech for titanium or is it just a plain smeltable ore?

**Comment by hasezoey** [comment]
Ore, Plates and Intermediates

**Comment by ReikaKalseki** [comment]
That does not even approach being an answer to the question.

**Comment by hasezoey** [comment]
sorry, then i dont know what you mean, 
py's mods add titanium ore, what can be refined to be plates

do you mean lua names?

**Comment by ReikaKalseki** [comment]
I specifically asked about technologies.

**Comment by hasezoey** [comment]
yes it does have technologies, but i think they are spread across 2 of these mods.
and what do you want to know? names of these technoloiges? a screenshot? lua names?

otherwise i dont understand it, anyway, here a screen shot
![image](https://i.imgur.com/y4FxuFj.png)
(opened is the first garde, wich will unlock the basic refining of titanium)

**Comment by ReikaKalseki** [comment]
That does answer the question, yes. If you happen to know their lua names, that would be helpful.

**Comment by hasezoey** [comment]
for titanium technologies: 
mod: "pyrawores"
technologies: "titanium-mk01" to "titanium-mk04"

**Comment by ReikaKalseki** [comment]
Fixed.
