### ISSUE TITLE
[Oreverhaul] Error on generating big worm turret

### ISSUE THREAD

**Issue by Funketime** [ReikaKalseki/Reika_FactorioMods_Issues#169]
Error while running event Oreverhaul::on_chunk_generated(ID 12) Unknown entity name: big-worm-turret, behemoth-worm-turret

I have found an error in functions.lua: 
function buildWormList()
	global.oreverhaul.availableWorms = {"small-worm-turret", "medium-worm-turret", "big-worm-turret, behemoth-worm-turret"}
end

There is a set of missing double quotes separating big and behemoth.  Game crashes on first encountering big worms.

**Comment by ReikaKalseki** [comment]
Fixed.
