### ISSUE TITLE
graphic bug

### ISSUE THREAD

**Issue by sader22** [ReikaKalseki/Reika_FactorioMods_Issues#17]
http://imgur.com/a/AiB7I

**Comment by ReikaKalseki** [comment]
Does it affect only the small dome, or all three?

**Comment by ReikaKalseki** [comment]
Everything is working as normal for me. How did this happen?

**Comment by sader22** [comment]
I think its just a random one because after reloading its gone and yes it
was affecting all three

2017-08-18 3:25 GMT+03:00 Reika <notifications@github.com>:

**Comment by zqr95518** [comment]
I see this once when I first update this mod. And become normal when second load game.

**Comment by zqr95518** [comment]
I see this again when update to .44. Maybe there's some bug?

**Comment by ReikaKalseki** [comment]
Then use the option.

**Comment by ReikaKalseki** [comment]
It has never happened for me.
