### ISSUE TITLE
[Bioluminescence] Missing setting name plant-density

### ISSUE THREAD

**Issue by Funketime** [ReikaKalseki/Reika_FactorioMods_Issues#170]
In Bioluminescence_1.17.6\locale\en\en.cfg there is a missing line for plant-density

[mod-setting-name]
glow-plants=Generate glowing plants
glow-biters=Make biters glow in the dark

I added this to test and was successful (I just used my understanding of this variable.
plant-density=Density of plants (1 = default density)

![Bioluminescence](https://user-images.githubusercontent.com/51725096/59471691-0f9f9300-8df9-11e9-8efd-4d97c6536a4a.png)

**Comment by ReikaKalseki** [comment]
Fixed.
