### ISSUE TITLE
[Choke Point] Stuttering

### ISSUE THREAD

**Issue by stucker9** [ReikaKalseki/Reika_FactorioMods_Issues#173]
**Issue:**
Whilst playing the game with the Choke Point mod enabled, stuttering is noticeable approximately every other second. Easier to notice when walking. Stuttering is more frequent if game speed is turned up.
**Evidence:**
Current.log - https://pastebin.com/WDUyS0HE
Screenshot of debug time usage - http://prntscr.com/o2xl65
SaveGame - https://drive.google.com/open?id=1BTxbwI-mnV7OmCgz0vUiZDRxI3UQTKDD
**Comments**
Hello, I love this mod! Its understandable that the extra math in map generation will add some lag but it seems particularly more resource heavy than any other mod I have. Its an unfortunate side effect and I don't know how you could even fix this but figure I point it out.

**Comment by ReikaKalseki** [comment]
Someone else found this a long time ago; it is due to worldgen that is going on outside the loaded area, and will eventually stop. 

Due to API limitations, I cannot make the algorithm any more performant.
