### ISSUE TITLE
get inventory error

### ISSUE THREAD

**Issue by Silvernova115** [ReikaKalseki/Reika_FactorioMods_Issues#176]
239.669 Error MainLoop.cpp:1183: Exception at tick 6064029: The mod Endgame Combat caused a non-recoverable error.
Please report this error to the mod author.

Error while running event EndgameCombat::on_tick (ID 0)
real number expected got nil.
stack traceback:
	__EndgameCombat__/control.lua:349: in function <__EndgameCombat__/control.lua:280>
stack traceback:
	[C]: in function 'get_inventory'
	__EndgameCombat__/control.lua:349: in function <__EndgameCombat__/control.lua:280>
 248.204 Quitting: user-quit.
 250.351 DSound: Stopping voice
 250.351 DSound: Joining thread
 250.355 DSound: Exit _dsound_update; tid=20004
 250.355 DSound: Waiting for voice to stop ... signaled
 250.356 DSound: Joined thread
 250.356 DSound: Destroying thread
 250.356 DSound: Thread destroyed
 250.356 DSound: Releasing buffer
 250.356 DSound: Voice stopped
 250.356 DSound: Deallocating voice
 250.356 DSound: Deallocated voice
 250.469 Steam API shutdown.
 250.482 Goodbye

**Comment by ReikaKalseki** [comment]
#174
