### ISSUE TITLE
[0.17.50] Nauvis Day balance - scaling too fast

### ISSUE THREAD

**Issue by doktorstick** [ReikaKalseki/Reika_FactorioMods_Issues#177]
/evolution
    Evolution factor: 0.8731. (Time -2%) (Pollution 102%) (Spawner kills 0%).

Time playing ~80 minutes. Pollution overlay is nearly invisible. If you squint and turn your head you can see a very light pink. 

Playing w/ Rampant 10 levels + 10 variations. Everything else is defaults save water size.  

Wave of about 10 spitters, including mediums and a "titan" wiped my base. Seemingly impossible to defend at this stage, with walls, turret upgrade 1 and bullet upgrade 1, standard ammo. Haven't had time for more.

**Comment by doktorstick** [comment]
I've attached my savegame. It has many mods, so thank goodness for "sync". If there's something I can do to help figure out where the problem is, please let me know. I enjoyed NVDay back in the day and am looking forward to playing it again.

[overrun.zip](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/3303914/overrun.zip)

**Comment by ReikaKalseki** [comment]
You mention the *current* pollution level being very low; what about over time? Was a massive quantity emitted at some point in the past?

**Comment by doktorstick** [comment]
I've barely progressed. I don't see how it could have spiked in such a way to cause 87% evolution in 80 minutes of gameplay.  For reference, it is 14K (and change, maybe 16K) at peak, which is about 6-8x my two larger factory saves w/o NV Day, but I have no concept of how much pollution translates to evolution in NVDay. 

When I load those w/ NVDay enabled, the 5s graph jumps over 30K from 2-3K. The increase isn't unexpected given that NVDay is a heavier pollution hitter, but only 2x of what a 3MW factory has as compared to one launching rockets every 10 minutes or so?

The scaling most definitely feels off. A dozen burner-miners, a handful of assemblers, 20-30 electric miners, two radars, two greenhouses, three boilers, six steam engines and a 24-furnace stack causes 87% evolution is unbalanced. As I mentioned, it's only 80 minutes of gameplay and 3MW of power.

Another person on the Factorio forums posted a similar problem, FWIW.

![image](https://user-images.githubusercontent.com/1571413/59808181-c059d680-92c0-11e9-967c-261e1bebcd51.png)

**Comment by ReikaKalseki** [comment]
NVDay only slightly increases the evo-per-pollution amount; you still need large quantities - far more than you have claimed and shown - to create large evo increases.

**Comment by ReikaKalseki** [comment]
Someone else has reported this, and I am getting the feeling that 0.17 has changed the pollution-evo interaction somehow.

**Comment by n8crafter** [comment]
yeah, my save has had a lot of scaling issues with biter evolution as well, though much less drastically than yours, likely due to intervention via reika's other mod, Loss Prevention. currently cappred at 50% evolution after ~13 hourst total playtime, at mid-green science level techs. it's also impossible to see any pollution in the map view, although  it is most definitely prevalent as seen through debugging.

**Comment by ReikaKalseki** [comment]
Try the newest download, which has a (hopefully temporary) /60 on the evo-from-pollution value.

**Comment by ReikaKalseki** [comment]
So...

**Comment by n8crafter** [comment]
If I recall correctly from my most recent playthrough (a few months ago), the change was a bit too much, as biter evolution would sit at 0% unless I went on a biter genocide spree

**Comment by ReikaKalseki** [comment]
Try again with the next version.

**Comment by ReikaKalseki** [comment]
I just redid the balance again.
