### ISSUE TITLE
bioluminescence crash fix

### ISSUE THREAD

**Issue by wchristian** [ReikaKalseki/Reika_FactorioMods_Issues#178]
Just realized you have a specific issues repo. Might wanna add something to the bioluminescence repo that points at this one if people try to make issues there.

In any case, i put in a crash fix pull request: https://github.com/ReikaKalseki/Bioluminescence/pull/3

**Comment by ReikaKalseki** [comment]
As  per the thread. https://forums.factorio.com/viewtopic.php?p=438202#p438202
