### ISSUE TITLE
Placing flamethrowers with blueprints is broken

### ISSUE THREAD

**Issue by PhatzDomino** [ReikaKalseki/Reika_FactorioMods_Issues#18]
Hello again Reika

Found another big with blueprints, when placing a blueprint with flamethrowers, they alway place facing upwards. This happens with base and modded flamethrowers that have been upgraded with the range boost.

Thanks again

Will.

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by PhatzDomino** [comment]
Coolio that was fast, will the new version be up soon?

cheers once again :)

**Comment by ReikaKalseki** [comment]
I am redoing some internal cache work first.

**Comment by PhatzDomino** [comment]
Roger that boss :)
