### ISSUE TITLE
Startup error (mod incompatibility related)

### ISSUE THREAD

**Issue by stucker9** [ReikaKalseki/Reika_FactorioMods_Issues#180]
https://pastebin.com/uXD6xPJu - Current.log
https://www.dropbox.com/s/i2v7ibkkvg28ewd/GENERIC_MODLIST.zip?dl=0 - Game save for modlist duplication

**Comment by ReikaKalseki** [comment]
Just tell me what mods you have, in particular anything involving Bobmods or other major overhauls.
