### ISSUE TITLE
[Endgame Combat] Typo in en.cfg

### ISSUE THREAD

**Issue by Funketime** [ReikaKalseki/Reika_FactorioMods_Issues#181]
In Endgame Combat, the tier 3 powered armour tool tip shows as missing name.  I have fixed error by correcting the typo by changing the following in:
EndgameCombat_1.17.12.zip\EndgameCombat_1.17.12\locale\en\en.cfg
Line 37:
power-armor-3=Tier-3 Power Armor

![unknown key](https://user-images.githubusercontent.com/51725096/59969093-22a21980-9503-11e9-8995-4c885035d736.jpg)
should be
power-armor-mk3=Tier-3 Power Armor
![Corrected name](https://user-images.githubusercontent.com/51725096/59969104-59782f80-9503-11e9-871a-26504eeb8d8a.png)

**Comment by ReikaKalseki** [comment]
Fixed.
