### ISSUE TITLE
[FastFurnaces] Failed to load mod after attempt to index field 'refinery'

### ISSUE THREAD

**Issue by n8crafter** [ReikaKalseki/Reika_FactorioMods_Issues#183]
I received the following error message while attempting to launch after changing a mod option for Fast Furnaces:

Mods to disable:Failed to load mods: __FastFurnaces__/data.lua:12: __FastFurnaces__/prototypes/refinery.lua:54: attempt to index field 'refinery' (a nil value)
stack traceback:
	__FastFurnaces__/prototypes/refinery.lua:54: in main chunk
	[C]: in function 'require'
	__FastFurnaces__/data.lua:12: in main chunk
stack traceback:
	[C]: in function 'require'
	__FastFurnaces__/data.lua:12: in main chunk

I am running Factorio version 0.17.52 and fast furnaces version 1.17.12

Edit: the setting that was changed was the "enable fast refinery" mod setting, which I toggled on.

**Comment by ReikaKalseki** [comment]
Fixed.
