### ISSUE TITLE
[Endgame combat] Exclude a turret from range upgrades

### ISSUE THREAD

**Issue by numbernegative** [ReikaKalseki/Reika_FactorioMods_Issues#184]
Requesting a way to blacklist specific modded turret types from the range upgrade.
I'm using the experimental Space Exploration mod and when range upgrades are applied, they break the meteor defense cannons. A way to blacklist those turrets from the upgrades would likely be the easiest solution to the problem.

**Comment by ReikaKalseki** [comment]
I already have such a blacklist internally. Tell me the (internal lua) names of those turrets and I will add them.

**Comment by numbernegative** [comment]
Oh, that's excellent. I'm no expert at digging though the zip files but if I'm reading this right the lua names are 'se-meteor-defence-container' and 'se-meteor-point-defence-container'.

**Comment by ReikaKalseki** [comment]
Done.
