### ISSUE TITLE
Error loading Mod

### ISSUE THREAD

**Issue by bcsmyway** [ReikaKalseki/Reika_FactorioMods_Issues#185]
![factorio-geothermal](https://user-images.githubusercontent.com/52382348/60400281-9b2a5b00-9b3f-11e9-97e7-3759016ad1c1.PNG)

Didn't see this anywhere else yet.

**Comment by PaladinFallen** [comment]
This is for Geothermal Vents not Geothermal, haha. Yea, they are two different mods from two different creators. However he said that he would be working on the mod soon, here is his link so you can watch the mod. [Geothermal Vents](https://mods.factorio.com/mod/Geothermal-Vents)

Reika, this is issue is non-mod, issue closed.

**Comment by ReikaKalseki** [comment]
I knew that label would see some use. :P
