### ISSUE TITLE
[Endgame Combat] Gun turret will spam the "low ammo" alert when mildly damaged

### ISSUE THREAD

**Issue by n8crafter** [ReikaKalseki/Reika_FactorioMods_Issues#186]
this issue became apparent to me after accidentally bumping a gun turret (with a full stack of ammo inside) with my car. the "low turret ammo" alert will then begin to play regardless of whether the turret is subsequently repaired, or if ammo is removed and replaced. the only method of stopping the alerts is to pick up and replace the turret itself.

**Comment by ReikaKalseki** [comment]
The issue has nothing to do with health or repair, but that it is marking it for low ammo when you feel it should not.

Which makes this #110 or this: ![https://i.imgur.com/Sevc0qt.png](https://i.imgur.com/Sevc0qt.png)
