### ISSUE TITLE
Power satisfaction meter not working? [Factor-IO]

### ISSUE THREAD

**Issue by bfosqueUC** [ReikaKalseki/Reika_FactorioMods_Issues#187]
The power satisfaction meter doesn't seem to output anything? Is there some special way I need to set it up to use it? The production and consumption meters both work, but of course they both output the same value.

**Comment by ReikaKalseki** [comment]
Does it have its own dedicated power supply? It will not work correctly if its power supply falters.

**Comment by bfosqueUC** [comment]
I just tried using it with a dedicated power supply (solar panel and accumulator), and only connected it to the network I was trying to measure via a green wire. I still see no signal output at all. Am I doing something wrong?

**Comment by ReikaKalseki** [comment]
No, that sounds correct. Can I see a screenshot?

**Comment by ReikaKalseki** [comment]
OK, so they changed how power poles work in 0.17. I have no idea how to fix this yet. For now, you can connect it to accumulators and jury-rig some connection switching.

**Comment by ReikaKalseki** [comment]
It is fixed in 0.18, I think.
