### ISSUE TITLE
Factor-I/O: crash using loader filter actuator on non-filterable loader

### ISSUE THREAD

**Issue by slippycheeze** [ReikaKalseki/Reika_FactorioMods_Issues#188]
Reproduction:
1. Place a non-filterable loader.  (eg: stack inserter, not filter stack inserter.)
2. Place the filter actuator next to it.
3. Feed it a signal with an item.

I mean, the action is nonsense, but it would be nicer to get some feedback that I used the wrong inserter type other than a crash. :)

Result:

The mod Factor-I/O caused a non-recoverable error.
Please report this error to the mod author.

Error while running event FactorIO::on_tick (ID 0)
Callable only on entities that have filters.
stack traceback:
	__FactorIO__/calls.lua:55: in function <__FactorIO__/calls.lua:47>
	(...tail calls...)
	__FactorIO__/functions.lua:159: in function 'tickCombinator'
	__FactorIO__/control.lua:39: in function <__FactorIO__/control.lua:34>
stack traceback:
	[C]: in function 'set_filter'
	__FactorIO__/calls.lua:55: in function <__FactorIO__/calls.lua:47>
	(...tail calls...)
	__FactorIO__/functions.lua:159: in function 'tickCombinator'
	__FactorIO__/control.lua:39: in function <__FactorIO__/control.lua:34>

**Comment by ReikaKalseki** [comment]
Fixed.
