### ISSUE TITLE
[Nauvis Day] recipe for Filtered Coal Liquefaction uses half as much coal as it ought to

### ISSUE THREAD

**Issue by n8crafter** [ReikaKalseki/Reika_FactorioMods_Issues#189]
the recipe for Filtered Coal Liquefaction uses only 10 coal when it should use 20, when compared to the inputs and outputs of normal coal liquefaction. the current recipe essentially gives twice as much heavy oil, light oil, and methane gas for each unit of coal used.

Edit:
The Filtered Oil Refinery usually uses twice as many input resources (in addition to an air filter and some water) and puts out twice as many outputs per operation. 

the  recipe for normal coal liquefaction is 5s + 10  coal + 25 heavy oil + 50 steam, which produces 90 heavy oil + 20 light oil + 10 petroleum 

the recipe for filtered coal liquefaction is 5s + 10 coal + 1 air filter + 60 water + 50 heavy oil +100 steam, which produces 1 air filter casing + 180 heavy oil + 40 light oil +20 petroleum + 60 polluted sludge. 

as stated previously, the filtered coal recipe should be using 20 coal.

**Comment by PaladinFallen** [comment]
Did you do research on this at all and/or what mod are you talking about? The base game literally stats it _**USES**_ 
> 5 sec + **10 coal** + 25 heavy oil + 50 steam
 to produce 
> 90 heavy oil + 20 light oil + 10 petroleum.

 Please refer to https://wiki.factorio.com/Oil_processing for more details. So if you are wanting to change the **_base_** formula on something go to another mod that changes that AND/OR refer to what mod you are using. Cause what you just spewed out makes no sense.

**Comment by n8crafter** [comment]
oh, my mistake. I'll edit some more details into the post

**Comment by ReikaKalseki** [comment]
Fixed.
