### ISSUE TITLE
Attempt to index field 'animation' (a nil value) - NauvisDay 1.0.22

### ISSUE THREAD

**Issue by randiskhan** [ReikaKalseki/Reika_FactorioMods_Issues#19]
Error occurs when loading NauvisDay 1.0.22 with bobgreenhouse 0.15.2 and its dependency boblibrary 0.15.8.

From log:
0.995 Error ModManager.cpp:957: Failed to load mod "NauvisDay": __NauvisDay__/data-updates.lua:161: attempt to index field 'animation' (a nil value)

Thanks for all your hard work!

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by randiskhan** [comment]
Thanks!
