### ISSUE TITLE
BiterBias problem

### ISSUE THREAD

**Issue by amosis12** [ReikaKalseki/Reika_FactorioMods_Issues#190]
So it seems like the mod creates a file named "data-updates.lua" which stops the mod from loading properly. Deleting this file solves this problem.

**Comment by ReikaKalseki** [comment]
That file you deleted contains the entire content of the mod, thus you have made the mod do nothing. Moreover, the mod loads just fine.

**Comment by amosis12** [comment]
On my way this file contained just one string which refers to "overrides.lua", this is what I get when I restore the "data-updates.lua" file:
![Снимок](https://user-images.githubusercontent.com/52885285/61372563-2e81c100-a8a0-11e9-83ba-1303cf7629a5.PNG)

**Comment by ReikaKalseki** [comment]
You have configured the mods incorrectly, with invalid settings.
