### ISSUE TITLE
[Ftweaks] Harder Silos setting causes automation of Utility Science to take up several times more space

### ISSUE THREAD

**Issue by n8crafter** [ReikaKalseki/Reika_FactorioMods_Issues#191]
the stated setting is intended to make rocket construction more difficult, but now that Low Density Structures are required in the Utility Science pack recipe, it also makes technological progression far more difficult as well. The changes to craft time for Low Density Structures have the most profound effect, increasing the ratio of LDS assemblers to USP assemblers from 20 : 7 to 80 : 7.

**Comment by ReikaKalseki** [comment]
Adjusted.
