### ISSUE TITLE
Endgame combat mod

### ISSUE THREAD

**Issue by Crazus89** [ReikaKalseki/Reika_FactorioMods_Issues#193]
Hi

Firstly I love this mod but when you get attacked you get hundreds of high volume alarms from each turret but the vanilla sound settings don't affect the volume when turned down. So basically want to be able to turn the alarm sounds down/off if this is possible or during late the game is unplayable due constant hundreds of alarms when your  get attacked.

I was wondering if this is something you  can add as only figured out how to turn alarms sounds off in mod settings for low ammo alarm. 

Many thanks

**Comment by ReikaKalseki** [comment]
#135

**Comment by Crazus89** [comment]
I was wondering I could make request for private use to DL source code to edit the turret attack alarm to lower amount. As atm makes the deafing. And it ignores the base game vanilla sound settings for alarms

**Comment by ReikaKalseki** [comment]
For personal use, you are free to make whatever modifications you like. And like I said in the linked issue, it would be *impossible* for me to make a sound that did not adhere to the volume settings.
