### ISSUE TITLE
[ItemFinder]Crash when running command

### ISSUE THREAD

**Issue by minyan** [ReikaKalseki/Reika_FactorioMods_Issues#194]
Log :

 131.838 Error MainLoop.cpp:1184: Exception at tick 32611054: Error while running command "findItem": Unknown utility sound: "alert_construction".
stack traceback:
	__ItemFinder__/control.lua:106: in function <__ItemFinder__/control.lua:85>
stack traceback:
	[C]: in function 'play_sound'
	__ItemFinder__/control.lua:106: in function <__ItemFinder__/control.lua:85>

**Comment by ReikaKalseki** [comment]
This is with the newest version?

**Comment by minyan** [comment]
Sorry for late rely, yes it's with newest version.
By the time i write this, i play with Factorio 0.17.63
ItemFinder Version 1.17.12
DragonIndustries 1.17.18

**Comment by ReikaKalseki** [comment]
Fixed.
