### ISSUE TITLE
[factor-io] enemy detector: handle more forces than just "enemy" -- mod compatibility-ish more than a bug

### ISSUE THREAD

**Issue by slippycheeze** [ReikaKalseki/Reika_FactorioMods_Issues#195]
The "Enemy Detector" device checks for entities with `force == "enemy"` via the find_entities_filtered function.  This is fine in the vanilla game, but also incompatible with mods that use additional forces that are still in the "enemy" bucket:

**[Will-o'-the-Wisps updated](https://mods.factorio.com/mod/Will-o-the-Wisps_updated)**: this uses two forces, `wisp`, and `wisp_attack`, for the creatures that are neutral, and hostile, but are not bugs.

**[Biter Factions](https://mods.factorio.com/mod/biter_factions)**: this creates extra forces, and assigns the biters to them.  these forces are hostile to each other -- `biter_faction_%d` for 1 through 5.   (by default; there is a lua-only constant that can change this, but I doubt most people do.)

One possible strategy is to simple find anything where `entity.force ~= scanner.force`, if you forgive the pseudocode.  That would detect living things in the `neutral` faction as hostile, too, which I think is maybe fish?  I'm not even sure.

Obviously, this is mod integration territory, but I feel that it is probably generic enough a feature request to be worth doing.  

As an alternative, a second virtual signal to emit "enemy count" and also " other entity count" would solve my personal problem nicely.  

In fact, anything that'd make it possible to use the sensor to react to those hostile factions mentioned above would be fine for me. :)

**Comment by ReikaKalseki** [comment]
` That would detect living things in the neutral faction as hostile, too, which I think is maybe fish?` That would detect everything from worldgen, as well as nonhostile player factions. This is not an option.

**Comment by ReikaKalseki** [comment]
Done.
