### ISSUE TITLE
[Nauvis Day] Conflict with Schall Machine Scaling

### ISSUE THREAD

**Issue by 1avek1** [ReikaKalseki/Reika_FactorioMods_Issues#196]
Found on Factorio 0.17.55 and later. The game doesn't get to the main menu, it errors on load.

[factorio-current.log](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/3445435/factorio-current.log)

**Comment by ReikaKalseki** [comment]
Can you pastebin it?

**Comment by 1avek1** [comment]
> Can you pastebin it?

https://pastebin.com/2xT4Mag5

**Comment by ReikaKalseki** [comment]
```Failed to load mods: Error while loading entity prototype "clean-oil-refinery-MS-1" (assembling-machine): Invalid pipe connections specification for offset {-3.0000000000, 0.0000000000}. The offset must be outside of the entity bounding-box```

Does he add custom refineries?

**Comment by 1avek1** [comment]
> Does he add custom refineries?

Yes, obviously. I've noticed they're missing from the description at mods.factorio.com/mod/SchallMachineScaling , but they're there in the game, can be researched and used.

They're larger than normal. The one causing the error is 2 times larger than vanilla in each dimension, and each of its connection is doubled (2 pipe attachments for each liquid right next to each other). There's one more, it's 3 times larger than vanilla, and each connection is tripled on it.

**Comment by ReikaKalseki** [comment]
That would do it.

This is...not a trivial fix.

**Comment by ReikaKalseki** [comment]
My only idea is blacklisting his entity types. What are their internal names?

**Comment by 1avek1** [comment]
> My only idea is blacklisting his entity types. What are their internal names?

They are "oil-refinery-MS-_N_" where _N_ is a tier number. The exact range of the tier numbers is configurable. Schall's mod has evolved, it provides up to 6 tiers now, and there's a mod setting to choose how many.

Unchecking "Enable Filtered Refinery" allows the game to work, so there's a workaround.

**Comment by ReikaKalseki** [comment]
Is there a maximum allowed on that config?

**Comment by 1avek1** [comment]
> Is there a maximum allowed on that config?

There is, but please don't hardcode it. It has changed before and can change again.

**Comment by ReikaKalseki** [comment]
What I was planning was to iterate from 1 upwards until that index of machine did not exist; this could safely be assumed to be the maximum tier (as the tier list is not likely to have "gaps"). However, that iteration needs an upper bound, ideally not Int.MAX.

**Comment by 1avek1** [comment]
> What I was planning was to iterate from 1 upwards until that index of machine did not exist

prototypes/refinery.lua already iterates through all preexisting refinery prototypes. It would be better, I think, to filter out all the problematic ones without extra iteration. Maybe by a Lua pattern. Something like `if not string.find(refinery.name, "^oil%-refinery%-MS%-%d+$") then`.

**Comment by ReikaKalseki** [comment]
I have no idea what that regex means.

**Comment by 1avek1** [comment]
> I have no idea what that regex means.

It's a [Lua pattern](https://www.lua.org/pil/20.2.html).

`^` and `$` mean that entire `refinery.name` must match, not just some substring. Letters mean that this exact subsequence of letters must be in `refinery.name`. `%d+` before `$` means that 1 or more digits must be at the end of `refinery-name`. `%-` simply means `-`, it's escaping of the control character `-`.

It's easy to check a pattern [here](https://www.lua.org/demo.html) by running a snippet like this:
```lua
if string.find("oil-refinery-MS-3", "^oil%-refinery%-MS%-%d+$") then
  io.write("YES!")
else
  io.write("no :(((")
end
```

**Comment by ReikaKalseki** [comment]
Is that reasonably performant?

**Comment by 1avek1** [comment]
> Is that reasonably performant?

I made a quick test (with mostly real data from Schall's mod and Factorio base). It's 14 times _faster_ than checking number suffixes for 9 tiers in a subloop. While being simpler and more universal. And only 5 times slower than comparing with a constant string. So I'd say yes, reasonably performant.

My subloop is probably somewhat dumb and optimizable, but why even bother...

Test code: https://pastebin.com/nj8vmvVD (has been run under standalone lua interpreter, not within Factorio)

**Comment by ReikaKalseki** [comment]
Fair enough; I will do this for the next release.

**Comment by ReikaKalseki** [comment]
Done.

    local function isValidRefinery(name, refinery)
    	if string.find(name, "^oil%-refinery%-MS%-%d+$") then
    		return false
    	return true
    end

    for name,refinery in pairs(data.raw["assembling-machine"]) do
    	if #refinery.crafting_categories == 1 and refinery.crafting_categories[1] == "oil-    processing" and isValidRefinery(name, refinery) then
    		createRefinery(refinery)
    	end
    end
