### ISSUE TITLE
data-final-fixes bug

### ISSUE THREAD

**Issue by othocaes** [ReikaKalseki/Reika_FactorioMods_Issues#198]
Bug on line 5 in data-final-fixes. bad argument #1 of 3 to "insert" (nil where a table should be). Can't tell what's up because it looks like the github repository doesn't have the code yet.

**Comment by ReikaKalseki** [comment]
Someone added a tech that uses green science but has no prerequisites. While this should not crash, that is semantically wrong.

For now, you can fix it by adding `if not tech.prerequisites then tech.prerequisites = {} end` before each `table.insert` in DragonIndustries' `data-final-fixes`.

**Comment by hasezoey** [comment]
still happening in .18 since .16 (mod version)

**Comment by ReikaKalseki** [comment]
It has not been released yet.

**Comment by awdwyn** [comment]
Confirming that this error pops up when Dragon Industries is active alongside Industrial Revolution.  Your suggested fix (if not tech.prerequisites then tech.prerequisites = {} end) _does_ work to get them both playing nice.

**Comment by nightwing2369** [comment]
So I'm trying to get Geothermal running and I tried to do the fix but its still giving me the same error. Did I do it right?
![data-final-fixes](https://user-images.githubusercontent.com/55862782/65735636-b56fc880-e09d-11e9-88e4-2f318e1b0cdd.PNG)

**Comment by ReikaKalseki** [comment]
Just delete the entire iteration; I did.

**Comment by nightwing2369** [comment]
Delete what? the "table.insert" stuff?

**Comment by ReikaKalseki** [comment]
The entire block.
