### ISSUE TITLE
crash when trying to recover turret

### ISSUE THREAD

**Issue by SkullKidDanzen** [ReikaKalseki/Reika_FactorioMods_Issues#2]
when trying to recover any turret, i get this and get kicked to the menu
**Error while running event EndgameCombat::on_robot_mined_entity (id64)
EndgameCombat/control.lua:398:attempt to index field'?' (a nil value)**
[factorio-current.log.txt](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/1192491/factorio-current.log.txt)

**Comment by ReikaKalseki** [comment]
Fixed.
