### ISSUE TITLE
Error while loading entity prototype "dead-greenhouse" (assembling-machine): Crafting speed has to be positive. NauvisDay 1.0.26

### ISSUE THREAD

**Issue by randiskhan** [ReikaKalseki/Reika_FactorioMods_Issues#20]
Sorry Reika.
Factorio log: https://pastebin.com/MWGFa69q

Same mods as issue #19, although newer NauvisDay. No error when loading NauvisDay alone.
boblibrary 0.15.8
bobgreenhouse 0.15.2
NauvisDay 1.0.26

**Comment by ReikaKalseki** [comment]
I have fixed it for the next compile, but cannot upload it at this time; for now, you can just edit the data-updates file yourself (pick something like 0.001).

**Comment by randiskhan** [comment]
Cool. Thanks!

**Comment by TinkerWorX** [comment]
I tried updating it manually but got another error about a missing order string. Any ETA on the release of the fix?
