### ISSUE TITLE
Endgame combat loading error action_delivery

### ISSUE THREAD

**Issue by JusMave** [ReikaKalseki/Reika_FactorioMods_Issues#201]
![微信截图_20190806174232](https://user-images.githubusercontent.com/31798536/62529787-e425ab80-b871-11e9-8602-c00711579f6a.png)

**Comment by ReikaKalseki** [comment]
I have never seen this before, and it does not happen to me. Do you have a mod changing one of the vanilla capsules?

**Comment by JusMave** [comment]
I have "space exploration" and "Expanded Rocket Payloads". But I still have the problem without them. Could u tell me the meaning of the error message? Maybe I can fix it.

Expanded Rocket Payloads: https://mods.factorio.com/mod/expanded-rocket-payloads

**Comment by JusMave** [comment]
OK, I find that this mod conflicts to Bob's warfare. Maybe u can have a try.

**Comment by ReikaKalseki** [comment]
Does that mod add custom capsules, or change vanilla ones?

**Comment by JusMave** [comment]
Yes, it has some new capsules

**Comment by ReikaKalseki** [comment]
Does it change the vanilla poison capsule?

**Comment by ReikaKalseki** [comment]
Hello?

**Comment by JusMave** [comment]
I‘m not sure about that. I didn't play pure vanilla version for a long time. Actually, the error was fixed after reloading all the mods.
