### ISSUE TITLE
[DragonIndustries] Crash on startup

### ISSUE THREAD

**Issue by maevii** [ReikaKalseki/Reika_FactorioMods_Issues#202]
When I start Factorio, this pops up
![image](https://user-images.githubusercontent.com/41077433/62612791-75dff800-b908-11e9-8cf3-bdd14347bdd7.png)
[my mod list here](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/3476336/mod-list.txt)

**Comment by ReikaKalseki** [comment]
I think you have a circular tech dependency. Try disabling DragonIndustries; you should still crash, as the game itself detects such circularities.

**Comment by maevii** [comment]
When DI is disabled, the game loads fine. I should also add that when only DI is loaded without other mods, it loads fine. I also tried to test DI with every separate mod I have to see what crashes, but it loaded everytime. So it is propably a problem with my specific mod combination. When I get on my PC I will test some more to see what mods it could be.

**Comment by Darkehart** [comment]
I get this error with only Dragon Industries and TurmOil loaded.

EDIT: should probably say that I'm running 0.17.68.
EDIT2: and I just noticed a slight difference, mine says data-final-fixes.lua:13 instead of 7 on the last line, but the top line is the same.

**Comment by ReikaKalseki** [comment]
See #209.
