### ISSUE TITLE
Geothermal Patches not spawning?

### ISSUE THREAD

**Issue by James-Fire** [ReikaKalseki/Reika_FactorioMods_Issues#203]
I haven't seen any in 2 generated games.

Or I just don't know what to look for on the map.

**Comment by ReikaKalseki** [comment]
By default they are biome-restricted; check your settings.

**Comment by James-Fire** [comment]
It looks like it has "everywhere" as allowed.

**Comment by ReikaKalseki** [comment]
And you have gone a minimum distance from spawn (they only spawn farther away)?

**Comment by James-Fire** [comment]
[image: 20190810004356_1.jpg]

Pretty far.

**Comment by ReikaKalseki** [comment]
You only attached the name of the image file, but fair enough.

They *were* generating, but absurdly rarely; I have tweaked the values.
