### ISSUE TITLE
[NauvisDay] Issue with Factorio Experimental .17.60

### ISSUE THREAD

**Issue by Gwilt** [ReikaKalseki/Reika_FactorioMods_Issues#204]
Issue found with latest Factorio experimental (.17.62) and latest Dragon Industries / Nauvis Day with no other mods installed.

During Factorio start it reports 'Failed ot load mods: Error while laoding recipe prototype "clean-basic-oil-processing" (recipe): Can't mix ingredient input fluid box indexing of automatic and custom'

Mods load fine if Factorio is set back to .17.59

I suspect this is related to one of these changes for .17.60

Basic oil processing produces only Petroleum gas, for more streamlined oil setup in the beginning.
Basic oil processing keeps some of the refinery input/output slots unused, so it is more clear which ones will be used by Advanced oil processing.

https://wiki.factorio.com/Version_history/0.17.0

**Comment by Gwilt** [comment]
I've had another poke at attempting to update, however its still failing.

Error log can be found here - https://pastebin.com/RTNWC5U2

Specific error is 
4.440 Error ModManager.cpp:1323: Error while loading recipe prototype "clean-basic-oil-processing" (recipe): Difficulty normal: Can't mix ingredient input fluid box indexing of automatic and custom.
Modifications: Nauvis Day

I've taken a look at the recipe files but I'm not able to work out where the error is.

**Comment by ReikaKalseki** [comment]
I have already fixed this.
