### ISSUE TITLE
[Rubber belt] issue with 17.65 (compatibility with AAI industries maybe)

### ISSUE THREAD

**Issue by cbtendo** [ReikaKalseki/Reika_FactorioMods_Issues#205]
Hi, 
 I can't load the mod because there's this error:
Mods to disable:Failed to load mods: __RubberBelts__/data-updates.lua:26: bad argument #1 of 3 to 'insert' (table expected, got nil)
stack traceback:
	[C]: in function 'insert'
	__RubberBelts__/data-updates.lua:26: in main chunk

Mods to be disabled:
• RubberBelts

it seems that there's an compatibility issue with the latest AAI Industries?

**Comment by ReikaKalseki** [comment]
Did AAI change again? I fixed an incompatibility back in 0.16...

**Comment by ReikaKalseki** [comment]
Fixed.
