### ISSUE TITLE
Problem with Library data-final-fixes

### ISSUE THREAD

**Issue by James-Fire** [ReikaKalseki/Reika_FactorioMods_Issues#206]
43.147 Mods to disable:Failed to load mods: __DragonIndustries__/data-final-fixes.lua:5: bad argument #1 of 3 to 'insert' (table expected, got nil)
stack traceback:
	[C]: in function 'insert'
	__DragonIndustries__/data-final-fixes.lua:5: in main chunk

I checked the file, and it is adding the recipes of the science packs to the science techs, when they are already in there in vanilla, so I'm wondering what the point is.

**Comment by ReikaKalseki** [comment]
#198
