### ISSUE TITLE
[Geothermal, 0.17.67] Crash on loadup due to missing texture from base game

### ISSUE THREAD

**Issue by Notawallplan** [ReikaKalseki/Reika_FactorioMods_Issues#208]
![Crash info from 0.17.68](https://user-images.githubusercontent.com/13065770/64423506-b43a1580-d074-11e9-8c5e-77b87ce04e0e.png)

This is due to the recent change to the look of the vanilla chemical plant, which apparently many mods rely on for some reason. (Probably pragmatical)

An easy (afaik) fix would be to include the file in Geothermal or Dragon Industries and point the green patch code there.

Edit: if this is a duplicate, i didn't see the original issue probably because someone didn't title it right.

**Comment by PaladinFallen** [comment]
#207
