### ISSUE TITLE
Random Error at Gamestart

### ISSUE THREAD

**Issue by Fenrir10** [ReikaKalseki/Reika_FactorioMods_Issues#209]
![Desktop Screenshot 2019 09 07 - 02 47 56 25](https://user-images.githubusercontent.com/35500719/64467580-1dc02f80-d11a-11e9-8ec6-d846e8cbbe90.png)
No idea what happend, updatet it to the latest version(running the latest experimental version of factorio), and using some other mods.
What can i do?

**Comment by Fenrir10** [comment]
the German parts mean: Error while loading mods,
and that i have to deactivate your mod

**Comment by ReikaKalseki** [comment]
Someone did something odd, but the affected feature has since been removed.
