### ISSUE TITLE
Error on load NauvisDay_1.0.26

### ISSUE THREAD

**Issue by zqr95518** [ReikaKalseki/Reika_FactorioMods_Issues#21]
20.396 Mods to disable:模组加载失败：Error while loading entity prototype "dead-bio-farm" (assembling-machine): Crafting speed has to be positive.
Modifications: Nauvis Day

下列模组需禁用：
• NauvisDay

the NauvisDay_1.0.0 can normal use.

**Comment by ReikaKalseki** [comment]
#20
