### ISSUE TITLE
Geothermal 1.17.12 crashes on load

### ISSUE THREAD

**Issue by tuetenk0pp** [ReikaKalseki/Reika_FactorioMods_Issues#210]
As already known from #207 and #208 
Game Version 0.17.69
Mod Version 1.17.12 (latest I could find in the portal)

Tried to fix it myself (#207) but wont work unfortunately

![grafik](https://user-images.githubusercontent.com/55783419/65580277-a263d800-df79-11e9-855c-57c9a617c212.png)

**Comment by tuetenk0pp** [comment]
no other mods enabled than Dragon Industries

**Comment by PaladinFallen** [comment]
he's fixed the problem but hasn't released the updated version yet... probably wait for the stable release.

**Comment by ReikaKalseki** [comment]
#198
