### ISSUE TITLE
[Endgame Combat] Random crash during play.

### ISSUE THREAD

**Issue by numbernegative** [ReikaKalseki/Reika_FactorioMods_Issues#211]
![image](https://user-images.githubusercontent.com/11063321/65998677-6f31b500-e461-11e9-83a2-9f7ff8f672db.png)

I'm getting a random crash from Endgame Combat during normal play in my heavily modded game. It happens without making any changes to turrets, no enemy is entering a range, I have a save file and no matter what I do it crashes with this same error at the same moment each time.

**Comment by ReikaKalseki** [comment]
Do you have anything unusual happening in relation to research?

**Comment by numbernegative** [comment]
> Do you have anything unusual happening in relation to research?

Just checked the save again, yes it did crash at the exact moment your Range Boost 3 completed.
in the meantime I did load an older autosave, ran around and picked up all turrets, let the research complete/the time it was crashing pass, then place them again to get around the crash.

**Comment by numbernegative** [comment]
Additionally, I just completed Range Boost 4 without a hiccup.

**Comment by ReikaKalseki** [comment]
No, I mean do you have a weird setup, or mods interfering with the research process.

**Comment by numbernegative** [comment]
My research setup is pretty standard. I don't think I have anything that changes the research process: Obviously stuff that adds more, some addition stuff that increases speed, disco science, etc.
Here's my mods folder, not all of these are currently enabled but a majority are.
![image](https://user-images.githubusercontent.com/11063321/66014958-58598580-e496-11e9-9cac-a3090dcad9fd.png)

**Comment by ReikaKalseki** [comment]
Fixed.

https://forums.factorio.com/viewtopic.php?f=30&t=76360&p=459947#p459947
