### ISSUE TITLE
geothermal wells don't spawn 

### ISSUE THREAD

**Issue by the-clorax** [ReikaKalseki/Reika_FactorioMods_Issues#212]
geothermal wells will not spawn anywhere i go, ive tried deleting and redownloading but nothing seems to work. i am using the newest available version of everything. i have everything on default settings, i don't know if im the only person with this issue.
![image](https://user-images.githubusercontent.com/38145280/66008566-0e1bd880-e485-11e9-933f-cff09f11ef22.png)

![image](https://user-images.githubusercontent.com/38145280/66008395-2e976300-e484-11e9-871f-b4e1e20105a0.png)
![image](https://user-images.githubusercontent.com/38145280/66008468-9352bd80-e484-11e9-9bdd-ed0bb92a54c7.png)

**Comment by ReikaKalseki** [comment]
They do not spawn near the center of the map. Find a volcanic biome at least 500 tiles out.

**Comment by ReikaKalseki** [comment]
And they are spawning fine for me.
