### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by Lgk2** [ReikaKalseki/Reika_FactorioMods_Issues#213]
![image](https://user-images.githubusercontent.com/7945495/66150177-e8253e00-e614-11e9-89a4-3c446fd7f325.png)

![image](https://user-images.githubusercontent.com/7945495/66149907-5e757080-e614-11e9-8167-93a1cad6abad.png)

**Comment by Lgk2** [comment]
![image](https://user-images.githubusercontent.com/7945495/66150422-73063880-e615-11e9-8624-9b6e91f08ea2.png)

Maybe one causes the next.

**Comment by ReikaKalseki** [comment]
Do you have mods adding or modifying refineries or their recipes?

**Comment by Lgk2** [comment]
Yeah i think so I have angelbob, pyanodons, madclown and more.

**Comment by ReikaKalseki** [comment]
Try removing them one by one.

**Comment by Lgk2** [comment]
Well problem is that it's a lot of mods and it takes a long time for my computer to load the game.

**Comment by ReikaKalseki** [comment]
You only need to try with the mods that change refineries.

**Comment by Uplinkpro** [comment]
I have the same issue and it's caused by Angel's PetroChem.

**Comment by Delta4Phoenix** [comment]
Well, I also get this, but without Angel's PetroChem. Can you maybe do something about the incompatibilities? I'll try to isolate the mod that causes it on my end.

**Comment by Delta4Phoenix** [comment]
My logfile: https://pastebin.com/y2EMTNc6

**Comment by Delta4Phoenix** [comment]
It seemed to be 5dim's automatization 0.17.3,

**Comment by ReikaKalseki** [comment]
In both cases this is because those mods have not finished properly updating to 0.17; they are using an outdated pollution parameter.

**Comment by ReikaKalseki** [comment]
Is this still an issue in 0.18?
