### ISSUE TITLE
[Fast Furnaces] Accelerated Offshore Pump placement

### ISSUE THREAD

**Issue by kaedys** [ReikaKalseki/Reika_FactorioMods_Issues#214]
The Accelerated Offshore Pump doesn't seem to be flagged as a water-placeable structure.  It cannot be placed anywhere in the water (shoreline or otherwise), and doesn't trigger the green placement squares along the shoreline that normal pumps do when placing.  It _can_, however, be placed anywhere on dry land, and _does_ provide water from such a placement.

<img width="217" alt="factorio_mdMFFW83Y1" src="https://user-images.githubusercontent.com/9020449/66449355-ccf66c00-ea22-11e9-82c9-89614841386e.png">
<img width="257" alt="factorio_RXnwnZo8Ip" src="https://user-images.githubusercontent.com/9020449/66449360-cff15c80-ea22-11e9-8802-a4bbe136a8f7.png">
<img width="145" alt="factorio_x9ws4yJF6O" src="https://user-images.githubusercontent.com/9020449/66449367-d54ea700-ea22-11e9-90c9-553c928c6223.png">

Needless to say, this rather significantly changes the balance of the structures.

**Comment by ReikaKalseki** [comment]
Hopefully fixed.
