### ISSUE TITLE
Mod incompatibility with Nauvis Day

### ISSUE THREAD

**Issue by DeadlyKitten37** [ReikaKalseki/Reika_FactorioMods_Issues#215]
Game crashes with Nauvis day and the mod Good Burner Things (https://mods.factorio.com/mod/GoodBurnerThings) loaded at the same time. I tried but was not able to copy and paste the error message itself. 
the important  part (I think?) is that it "attmpted to preform arithmetic on field 'emissions_per_minute" (a nil value)" ... " in function 'createRefinery' ".

**Comment by ReikaKalseki** [comment]
This is the same as #213.
