### ISSUE TITLE
Crash on startup (Bioluminescense)

### ISSUE THREAD

**Issue by Delta4Phoenix** [ReikaKalseki/Reika_FactorioMods_Issues#216]
It crashes on startup, probably due to one of the 5dim mods.
https://pastebin.com/mkViV8Wv

**Comment by ReikaKalseki** [comment]
Does he do anything with biters?

**Comment by Delta4Phoenix** [comment]
Yes, one of them adds biters.

**Comment by ReikaKalseki** [comment]
And what is special about them?

**Comment by Delta4Phoenix** [comment]
It adds Climber biters, Suicide biters, Laser Biters, Swimmer Biters, and an Experimental spawner, which, if memory serves me right, is a GIANT biter, which has way too many hit points.

**Comment by ReikaKalseki** [comment]
Do all of these have tint colors?

**Comment by ReikaKalseki** [comment]
It seems that these biters have no color parameters on their animation layers.

I will make that default to a white glow.
