### ISSUE TITLE
Geothermal error when loading with AlienBiomes

### ISSUE THREAD

**Issue by jvaler1** [ReikaKalseki/Reika_FactorioMods_Issues#217]
I have the Geothermal mod installed along with alien biomes, and this error comes up when I try to make a world.
![image](https://user-images.githubusercontent.com/51203862/67136173-a38eca80-f1f0-11e9-89b1-c9aef34f2edd.png)
I suspect it has to do with alien biomes and not any other mods, but just to be sure I attached the mod list. I'm not asking for help, just putting this out to let you know.

Attached is the mod list used
[mods.txt](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/3746106/mods.txt)

**Comment by ReikaKalseki** [comment]
It works fine for me, with AlienBiomes.

**Comment by jvaler1** [comment]
This was a long time ago, something may have changed. I had exchanged all
the details I had with the mod author last year.
