### ISSUE TITLE
[Endgame combat] More turrets need blacklist from range upgrades.

### ISSUE THREAD

**Issue by numbernegative** [ReikaKalseki/Reika_FactorioMods_Issues#219]
A few of the turrets from the Additional Turrets mod completely break when range upgrades are applied.
The internal Lua names should be:
"at_CR_b"
"at_CR_s1"
"at_CR_s2"
"at_A1_b"
"at_A1_b"
"at_A2_b"

**Comment by ReikaKalseki** [comment]
Done.
