### ISSUE TITLE
FTweaks mod conflict with textplates

### ISSUE THREAD

**Issue by SeanStoves** [ReikaKalseki/Reika_FactorioMods_Issues#22]
FTweaks will not work with the mod textplates installed

https://mods.factorio.com/mods/Earendel/textplates

**Comment by ReikaKalseki** [comment]
That is nowhere near enough information.

**Comment by ReikaKalseki** [comment]
Hello?

**Comment by ReikaKalseki** [comment]
For what it is worth, I saw this issue myself, and the cause is on his end. He has not replied to any attempt at contact.
