### ISSUE TITLE
Missing dependancy

### ISSUE THREAD

**Issue by pixelwhipped** [ReikaKalseki/Reika_FactorioMods_Issues#220]
Cannot add items if they don't exist

  15.774 Mods to disable:Failed to load mods: __EndgameCombat__/data-updates.lua:4: __EndgameCombat__/prototypes/recipe/recipe-updates.lua:20: No technology for plate titanium!
stack traceback:
	[C]: in function 'error'
	__EndgameCombat__/prototypes/recipe/recipe-updates.lua:20: in function 'addPlateToTurret'
	__EndgameCombat__/prototypes/recipe/recipe-updates.lua:26: in main chunk
	[C]: in function 'require'
	__EndgameCombat__/data-updates.lua:4: in main chunk
stack traceback:
	[C]: in function 'require'
	__EndgameCombat__/data-updates.lua:4: in main chunk

**Comment by ReikaKalseki** [comment]
What mods do you have that add titanium?

**Comment by pixelwhipped** [comment]
None, it's build into modmash.

**Comment by pixelwhipped** [comment]
I will look into regardless though

**Comment by ReikaKalseki** [comment]
It loads just fine both with and without titanium for me.
