### ISSUE TITLE
Mod Settings "Unknown Key"

### ISSUE THREAD

**Issue by VasVadum** [ReikaKalseki/Reika_FactorioMods_Issues#224]
I believe you forgot to type up a part of the settings here for a specific entry, "mod-setting-name.movable-rocks".

![image](https://user-images.githubusercontent.com/1490797/68847238-f34b9f00-0693-11ea-9c1b-8cd46f1d67ab.png)

**Comment by ReikaKalseki** [comment]
I fixed all their locale recently.
