### ISSUE TITLE
Nauvis Day Unlosable.

### ISSUE THREAD

**Issue by VasVadum** [ReikaKalseki/Reika_FactorioMods_Issues#227]
I keep getting this in the game;
NauvisDay: Re-setting enemy_evolution.time_factor to -2.5e-05 (was -2.5625e-05)

Which keeps resetting evolution to 0.0000%.

I can't produce pollution, no matter how much I try. I've burned down entire forests, I've blown up nests, and this mod keeps reducing evolution to zero.

It sets the absorption modifier to 200%, Attack cost modifier to 100%, Minimum damage to trees 9999, absorbed by tree 1000, diffuse ratio 5%.

Base game is 100%, 100%, 60, 10, 2%...

This means that, pollution is absorbed 2x faster so that it disappears far sooner.
Trees can't be damaged by pollution till it reaches extreme super mega uber factory levels.
Trees will only be damaged by the time it gets to that uber super factory level.
And while diffuse makes it spread further, your absorption factor makes the pollution disappear far sooner.

Here I am pumping out 5 times the pollution I normally do in a game, and my landscape is pristine and clean. I can't get hit by biters because there is no pollution. The mod keeps resetting evolution to some negative number preventing it from going positive.

I mean, normally I try to produce as little pollution as possible, and its practically impossible. In your mod here, its easy, I can spam coal burning factories everywhere and not worry about enemies or pollution, I don't even need your tree farm, which sorta looks a little out of place for the game but its still rather well done anyway. :P Though, it consumes an abnormally high volume of water and I'd like to turn down how fast it produces wood, personally, but eh anyway. (I ended up making a mod for bobs greenhouse that adds a setting to lower tree production rate, might do the same for Nauvis Day if it gets fixed up)

I'll disable the mod for the time being and wait to see what happens next.

Game version by the way is 0.17.74

p.s. I'm not sure how rubber floors are pollution free and how they would make you walk faster... You ever tried to walk on a rubber floor with rubber bottomed shoes...? Its also a toxic chemical in its self, prevents plants from growing up through it, and practically never decomposes.

**Comment by ReikaKalseki** [comment]
Related to #177, and fixed all the same.
