### ISSUE TITLE
NauvisDay Mod Conflicts with Bio_Industries

### ISSUE THREAD

**Issue by SeanStoves** [ReikaKalseki/Reika_FactorioMods_Issues#23]
NauvisDay has a Mod Conflict with Bio_Industries

https://mods.factorio.com/mods/TheSAguy/Bio_Industries

**Comment by SeanStoves** [comment]
![image](https://user-images.githubusercontent.com/6910352/29476600-c2149d14-8432-11e7-9082-c0d2b6d5c38b.png)

This was attached by another user experiencing the same problem.

**Comment by SeanStoves** [comment]
Attempted the fix on Issue#20, however, that did not resolve the issue.

**Comment by sinooko** [comment]
I added
`dead.order = "x[dead]-a[dead_bio_farm]"`
`dead.place_result = "dead_bio_farm"`

to lines 143 and 144 in data-updates.lua that got the game to load, 
but there was a null error on line 47 of pollutionfx.lua.

`if pollution > 40000 and math.random(40000, 120000) < pollution then`

**Comment by ReikaKalseki** [comment]
All of these are duplicates and on top of that have already been fixed.
