### ISSUE TITLE
Crash on_entity_spawned 

### ISSUE THREAD

**Issue by M3wM3w** [ReikaKalseki/Reika_FactorioMods_Issues#232]
737.572 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "The mod Bioluminescence caused a non-recoverable error.
Please report this error to the mod author.
Error while running event Bioluminescence::on_entity_spawned (ID 129)
__Bioluminescence__/prototypes/colorkeys.lua:17: attempt to index local 'item' (a nil value)
stack traceback:
__Bioluminescence__/prototypes/colorkeys.lua:17: in function 'getColor'
__Bioluminescence__/control.lua:115: in function <__Bioluminescence__/control.lua:100>"

Happened when placing a christmas tree from: https://mods.factorio.com/mod/elka

**Comment by ReikaKalseki** [comment]
Probably related to #216, and fixed in the same way.
