### ISSUE TITLE
Mod compatibilaty issue

### ISSUE THREAD

**Issue by DeadlyKitten37** [ReikaKalseki/Reika_FactorioMods_Issues#235]
the early game protection fails if the nightfall mod is enabled
https://mods.factorio.com/mod/Nightfall

**Comment by ReikaKalseki** [comment]
I need an error, and information on what mods are involved.

**Comment by DeadlyKitten37** [comment]
the bug is not an error message but unexpected behavior, The mods involved in my testing were nauvis day and nightfall. (+infinity mod for ease of testing)
Nauvis day stops bitter attacks in the early game, nightfall byepasses this and forces the bitters to attack every night. the bug is that the attacks come before they are allowed to.

**Comment by ReikaKalseki** [comment]
I cannot prevent that.
