### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BelZeqihr** [ReikaKalseki/Reika_FactorioMods_Issues#237]
The mod Endgame Combat caused a non-recoverable error.
Please report this error to the mod author.

Error while running event EndgameCombat::on_built_entity (ID 6)
The mod Mass Driver caused a non-recoverable error.
Please report this error to the mod author.

Error while running event mass-driver::script_raised_built (ID 77)
__mass-driver__/script/mass-driver.lua:282: attempt to index field 'entity' (a nil value)
stack traceback:
	__mass-driver__/script/mass-driver.lua:282: in function <__mass-driver__/script/mass-driver.lua:281>
stack traceback:
	__EndgameCombat__/control.lua:500: in function <__EndgameCombat__/control.lua:472>
stack traceback:
	[C]: in function 'raise_event'
	__EndgameCombat__/control.lua:500: in function <__EndgameCombat__/control.lua:472>

**Comment by calcwizard** [comment]
The error has been fixed on my end.

**Comment by ReikaKalseki** [comment]
I am pretty sure I fixed this.

**Comment by calcwizard** [comment]
I took another look at it. Based on the API page for [script_raised_built](https://lua-api.factorio.com/latest/events.html#script_raised_built), I had expected the entity to be `event.entity` and didn't properly nil check it.  Looking at the [calling function](https://github.com/ReikaKalseki/EndgameCombat/blob/master/control.lua#L500), EndgameCombat provides the entity as `event.created_entity`.

**Comment by ReikaKalseki** [comment]
`event.created_entity` *is* correct...or did that change?

**Comment by calcwizard** [comment]
`script_raised_built` is entity, it's `on_built_entity` and `on_robot_built_entity` that uses created_entity

**Comment by ReikaKalseki** [comment]
Ah.
