### ISSUE TITLE
NauvisDay: nil value loading error

### ISSUE THREAD

**Issue by Sensei-Farm** [ReikaKalseki/Reika_FactorioMods_Issues#238]
![Nauvis Day Error](https://user-images.githubusercontent.com/43001420/73503808-8fe92780-43cd-11ea-885e-e032404cf310.PNG)
It seems to have something to do with https://mods.factorio.com/mod/apm_power

**Comment by Yifei15** [comment]
> ![Nauvis Day Error](https://user-images.githubusercontent.com/43001420/73503808-8fe92780-43cd-11ea-885e-e032404cf310.PNG)
> It seems to have something to do with https://mods.factorio.com/mod/apm_power

You may check https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/issues/168, maybe similar problems?

**Comment by ReikaKalseki** [comment]
No, it is entirely unrelated.

**Comment by ReikaKalseki** [comment]
Fixed with #252.
