### ISSUE TITLE
Incorrect filepath in data-updates.lua - NauvisDay 1.0.30

### ISSUE THREAD

**Issue by randiskhan** [ReikaKalseki/Reika_FactorioMods_Issues#24]
data-updates.lua
Line 141: 	dead.working_visualisations.animation.filename ="\_\_NauvisDay\_\_/graphics/entity/biofarm/dead-biofarm-active.png"
Line 163: 	dead.working_visualisations[1].animation.filename ="\_\_NauvisDay\_\_/graphics/entity/biofarm/dead-greenhouse-active.png"

These two .png files are in "graphics/entity/treefarm/". Changing the above two filepaths ("biofarm" to "treefarm") worked for me.

**Comment by ReikaKalseki** [comment]
Derp.
