### ISSUE TITLE
Pheromones !

### ISSUE THREAD

**Issue by aa88aa88** [ReikaKalseki/Reika_FactorioMods_Issues#241]
Hi. The game crashes when this building is broken.
The idea is beautiful, but inconvenient.
It is necessary to make rockets, grenades, mines, as well as the ability to pour into barrels, otherwise it is very inconvenient to deliver. Otherwise, fashion does not make much sense. But the idea is super! I met similar in other mods. And make a description for each impact.
Waiting for updates. Good luck

**Comment by ReikaKalseki** [comment]
I need to know what the error is.

**Comment by ReikaKalseki** [comment]
It does not crash for me, and you never supplied your issue.
