### ISSUE TITLE
RADIATION LIFETIME FROM NEUTRON BOMB and ALERTS

### ISSUE THREAD

**Issue by Steff1234XD** [ReikaKalseki/Reika_FactorioMods_Issues#243]
Radiation lifetime from neutron bomb stayed unchanged for my whole playtrough (15) and i thought that it was safe to give the bomb to AAI programmable modded jet , and i was wrong...

So basically , neutron bomb blew up VERY CLOSE to my base and it destroyed some turrets and walls and also   bugged my signals (turret ammo warning) and it's constantly playing itself over and over again non stop, so i want to die every time i spent more than 15minutes in my modded factorio , idk what is happening because my whole turret system have automatic bullet refill so it's 100%amoo lvl  all the time but there are still alerts that I miss ammo...i would love to see the bar where player could set alert lengh, sound and attenuate because those fake alerts are driving me mad.  

Now this radiation lifetime, i thought when unchanged from basic value will make lifetime of 1 whole radiation field from neutron bomb last 15 seconds, sooooo i fired 3 of them at biters 3h ago in my saves and radiation still lasts, and now i blew up one close to my base and it's still lasts after 30 minutes , soooooo, what am  I not understanding ? is the basic value of 15 meaning something else than 15 seconds ? or is my game bugged? 

plz halp because your mod has made my game almost unplayable because of those alerts

**Comment by ReikaKalseki** [comment]
The radiation lifetime setting will not retroactively apply to pre-existing radiation; that is like expecting changes to world generation settings to retroactively change previously generated chunks. You will need to use commands to clear the radiation.

**Comment by Steff1234XD** [comment]
how to clear radiation with commands? after typing /h i don't see any commands that are for clearing the radiation

**Comment by ReikaKalseki** [comment]
This has to be a code command (which the game console can do); iterate over `surface.find_entities_filtered` for name 'radiation-cloud'. Call .destroy() on each entity.
