### ISSUE TITLE
don't know why it keeps failing

### ISSUE THREAD

**Issue by godliikekyle** [ReikaKalseki/Reika_FactorioMods_Issues#246]
<img width="718" alt="fact" src="https://user-images.githubusercontent.com/61916207/76148131-557c4580-6071-11ea-8d6b-fe75672d9248.png">
i've tried even the mods that you don't need. can someone help?

**Comment by godliikekyle** [comment]
nevermind

**Comment by ReikaKalseki** [comment]
#242
