### ISSUE TITLE
Failed to load mods: ... attempt to call global 'registerObjectArray' (a nil value)

### ISSUE THREAD

**Issue by Yifei15** [ReikaKalseki/Reika_FactorioMods_Issues#249]
NauvisDay 1.18.1, Factorio 0.18.28, with ABC and SE mods among others
<img width="899" alt="Screen Shot 2020-06-01 at 11 35 54" src="https://user-images.githubusercontent.com/35277919/83373827-59173280-a3fc-11ea-8afb-267a71e14d61.png">

**Comment by ReikaKalseki** [comment]
Fixed. For now, you can temp fix it by importing "registration" from DragonIndustries, like that file already imports "cloning".
