### ISSUE TITLE
The shield dome reduce too much fps.

### ISSUE THREAD

**Issue by zqr95518** [ReikaKalseki/Reika_FactorioMods_Issues#25]
The shield dome reduce too much fps, especially the big one.
How about add an option to close the fancy animation?

**Comment by ReikaKalseki** [comment]
They all have the same effects - just scaled differently - so they should not have differing FPS impacts. Try editing the shield-domes.lua to reduce the effect spawning and to see if that even changes anything.

**Comment by zqr95518** [comment]
Its code makes me dizzy. How about add somethink like press R to replace the effect to a single circle?

**Comment by ReikaKalseki** [comment]
?

**Comment by zqr95518** [comment]
I see some mods have function to press R to change action. How about use R as a switch. (Move the mouse over the item and press R)

**Comment by ReikaKalseki** [comment]
I just had an idea for a "low graphics settings" option, akin to Minecraft's particle settings or Fast/Fancy graphics. How does that sound?

**Comment by zqr95518** [comment]
Sound good. I try to place 4 shield dome. And.... where I'm I. (ಥ _ ಥ)

**Comment by zqr95518** [comment]
By the way, sometimes worms can pass through the shield if cause too much damage. The shield is not zero that time. And become normal a few later. Is it because of the shoot speed of the shield?

**Comment by ReikaKalseki** [comment]
Worm projectiles are the same as spitter ones, I believe, and *those* are stopped by shields.

**Comment by zqr95518** [comment]
When worm spawn in the shield, the shield will not work. But I sometimes can see worm pass through it, is it my illusion?

**Comment by ReikaKalseki** [comment]
...Anything already inside the shield is not protected against.

**Comment by ReikaKalseki** [comment]
The setting has been implemented in the latest version.

**Comment by zqr95518** [comment]
When I turn the option to 1, I can't see any different with 3. I still can't see anything when 4 shield charging together.

**Comment by ReikaKalseki** [comment]
That is one big texture, and is not affected by the option.

**Comment by zqr95518** [comment]
How about add an option to close it? A circle as an alternative.

**Comment by ReikaKalseki** [comment]
One texture is not causing you FPS issues.

**Comment by zqr95518** [comment]
But 4 shield charging together make center all white, can't see anything until charge complete.

**Comment by ReikaKalseki** [comment]
OK? Then let it charge. It is supposed to be a very large visual.
