### ISSUE TITLE
wishlist: geothermal mod should use 0.18 resource-autoplace tool

### ISSUE THREAD

**Issue by slippycheeze** [ReikaKalseki/Reika_FactorioMods_Issues#250]
It'd be great if the geothermal mod used [`resource_autoplace_settings`](https://github.com/wube/factorio-data/blob/master/core/lualib/resource-autoplace.lua#L78) from the `resource-autoplace.lua` library rather than custom code when a chunk is generated.

That'd be useful for map generator preview, as well as avoiding overlaps with existing resources.  It should be able to enforce all the current rules about placement correctly, as well as the probabilities.  

Unfortunately the license on the code and American employment law mean I can't contribute this myself, but I'd ask you to consider it.  

Thank you very much for the mod either way!

**Comment by ReikaKalseki** [comment]
No, the autoplace system does not offer anywhere near the flexibility and controllability custom script does, for example tile- (aka biome-)specific spawn rates and generating pairs of entities together. Geothermal will never use it, as to do so would mean scrapping features.
