### ISSUE TITLE
Conflict with Schall Alien Tech

### ISSUE THREAD

**Issue by tynmishoe22** [ReikaKalseki/Reika_FactorioMods_Issues#251]
Game crashes with only alientech, alienloot(dependency) and your mod enabled.   

2.746 Mods to disable:Failed to load mods: __EndgameCombat__/data-updates.lua:8: __EndgameCombat__/prototypes/rangeturrets.lua:45: attempt to index field 'ammo_type' (a nil value)
stack traceback:
	__EndgameCombat__/prototypes/rangeturrets.lua:45: in main chunk
	[C]: in function 'require'
	__EndgameCombat__/data-updates.lua:8: in main chunk
stack traceback:
	[C]: in function 'require'
	__EndgameCombat__/data-updates.lua:8: in main chunk

Mods to be disabled:
• EndgameCombat (1.18.1)
   5.119 Quitting: user-quit.
   5.153 Steam API shutdown.
   5.156 Goodbye

**Comment by ReikaKalseki** [comment]
...What kind of beam turret has an attack with no beam parameters?
