### ISSUE TITLE
Error: Attempt to index field 'result' (a nil value) | Full error in post

### ISSUE THREAD

**Issue by obj-obj** [ReikaKalseki/Reika_FactorioMods_Issues#252]
Whenever this mod is loaded, I get this bug. Could you please fix this?

Full error:
![image](https://user-images.githubusercontent.com/57120300/84290069-163e1480-aaf8-11ea-9e2e-8a0af6afecf3.png)

Edit: Forgot to add flair and can't edit the post, sorry

**Comment by ReikaKalseki** [comment]
The upcoming steam furnace rewrite should fix this.
