### ISSUE TITLE
[TurmOil] Chemical pack self-dependency

### ISSUE THREAD

**Issue by AssasinAsha** [ReikaKalseki/Reika_FactorioMods_Issues#253]
Hello!

Setting oil processing mode to anything other than "Pre-change recipes and technologies" results in the chemical science pack being unobtainable due to both lubricant and electric engine requiring chemical science pack in their research.

Factorio version 0.18.31
Dragon Industries 1.18.3
TurmOil 1.18.2

Have a good day!

**Comment by ReikaKalseki** [comment]
I noticed this earlier this week, and the lack of reports until now says something about how many people use this mod.

The new release uploading right now fixes it.
