### ISSUE TITLE
Bioluminescence error when placed entity

### ISSUE THREAD

**Issue by Oceanel51** [ReikaKalseki/Reika_FactorioMods_Issues#254]
1213.538 Error MainLoop.cpp:1204: Exception at tick 4117895: The mod Bioluminescence (1.18.5) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Bioluminescence::on_entity_spawned (ID 132)
__Bioluminescence__/prototypes/colorkeys.lua:17: attempt to index local 'item' (a nil value)
stack traceback:
	__Bioluminescence__/prototypes/colorkeys.lua:17: in function 'getColor'
	__Bioluminescence__/control.lua:122: in function <__Bioluminescence__/control.lua:107>

**Comment by Oceanel51** [comment]
279.496 Error MainLoop.cpp:1204: Exception at tick 4085166: The mod Bioluminescence (1.18.6) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Bioluminescence::on_entity_spawned (ID 132)
__Bioluminescence__/prototypes/colorkeys.lua:17: Bitername 'cattle-calf' refs to 'biter-color-reference-cattle-calf', which returned null!
stack traceback:
	[C]: in function 'error'
	__Bioluminescence__/prototypes/colorkeys.lua:17: in function 'getColor'
	__Bioluminescence__/functions.lua:122: in function 'createBiterLight'
	__Bioluminescence__/control.lua:128: in function <__Bioluminescence__/control.lua:113>

**Comment by Oceanel51** [comment]
> 279.496 Error MainLoop.cpp:1204: Exception at tick 4085166: The mod Bioluminescence (1.18.6) caused a non-recoverable error.

This happens when I place a ["cattle-spawner"](https://github.com/Oceanel51/FoodIndustry/blob/cbb64a14b9462e1176500feac20b445f1dae9fcf/prototypes/cattle/cattle.lua#L140), wich spawns ["cattle-calf"](https://github.com/Oceanel51/FoodIndustry/blob/cbb64a14b9462e1176500feac20b445f1dae9fcf/prototypes/cattle/cattle.lua#L63)s from the [FoodIndustry](https://mods.factorio.com/mod/FoodIndustry) mod.

I love the Bioluminescence and appreciate your work on it! I wanted to do something similar, but when I saw your work, I realized that I was still weak in programming (:

**Comment by ReikaKalseki** [comment]
This is fixed in the next version.
