### ISSUE TITLE
Failed to load mods: ... No such item 'water' in recipe

### ISSUE THREAD

**Issue by FadingFog** [ReikaKalseki/Reika_FactorioMods_Issues#255]
Factorio 0.18.31, FTweaks 1.18.6, mod list in .log file
![Screenshot_1](https://user-images.githubusercontent.com/10418075/84656636-aa0a4900-af1b-11ea-8bb5-a7e7d1ff8a71.png)
[factorio-current.log](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/4780150/factorio-current.log)
https://pastebin.com/qhJrYXFF

**Comment by ReikaKalseki** [comment]
This is fixed for the next version.
