### ISSUE TITLE
Endgame combat turrent range boost seems to be frozen at level 1

### ISSUE THREAD

**Issue by SirMishaa** [ReikaKalseki/Reika_FactorioMods_Issues#256]
Hello, 

First, thank you for your work, I love it ! 

I've unlocked the search for the Level 1 turret range boost and it works good.

But once you get to the level 2 or even level 3 upgrade and even removing the turrets, this one seems to stay at the level 1 range boost level.

I use various mods but this also happens with normal turrets.

Factorio version : 0.18.30
Endgame Combat version : 1.18.6

GIF (bad quality) can be found here : [https://i.ibb.co/sg7Hnvn/Factorio-Endgame.gif](https://i.ibb.co/sg7Hnvn/Factorio-Endgame.gif)
Video can be found here (better quality) : [https://send.firefox.com/download/...](https://send.firefox.com/download/3d867d7d07dbb860/#qELBWNHcNEdirify8U8owA)

Save if needed : [https://send.firefox.com/download/...](https://send.firefox.com/download/e6f8cf0b40182ac2/#MRSs9TG0kthO9U4G2mrIgQ)

Links expire in 24 hours.
Thank you !

**Comment by ReikaKalseki** [comment]
It works fine for me. Try removing other mods.

**Comment by SirMishaa** [comment]
Ok so I guess that apart from the mod support, the support of other mods as well as possible problems is not supported?

Anyway, that's all right, thank you, although I would have liked a slightly deeper investigation instead of this boat sentence.

**Comment by ReikaKalseki** [comment]
What do you expect me to do? Every indication I have from my testing is that it works fine, and there is a functionally infinite number of things that could be breaking it for you.

**Comment by ReikaKalseki** [comment]
It just started happening for me. It is almost like it only starts happening at a certain tech level or something.

**Comment by ReikaKalseki** [comment]
Fixed.
