### ISSUE TITLE
RubberBelts crashes on start - Can't find "__FTweaks__/graphics/icons/conversion_overlay.png"

### ISSUE THREAD

**Issue by DarkShadow44** [ReikaKalseki/Reika_FactorioMods_Issues#258]
As it says in the title. Without FTweaks, it still references that picture, because it's hardcoded in DragonIndustries.

Just have RubberBelts and DragonIndustries installed, no other mods. Using factorio 0.18.32.

**Comment by ReikaKalseki** [comment]
This is an old bug that I just discovered myself the other day when modifying some code. How it has gone unreported until now is beyond me.
