### ISSUE TITLE
Failed to load mods: ... attempt to call global 'changeRecipeTime' (a nil value)

### ISSUE THREAD

**Issue by FadingFog** [ReikaKalseki/Reika_FactorioMods_Issues#259]
Factorio 0.18.32, FTweaks 0.0.3 (Github version), mod list in .log file
![image](https://user-images.githubusercontent.com/10418075/85301839-0687de00-b4b1-11ea-9cd9-76c2bed2dc4a.png)
https://pastebin.com/bfzbgjeF

**Comment by ReikaKalseki** [comment]
That strongly implies you have a DI/FTweaks version mismatch.

And your logs *do* list FTweaks as version 0.0.3: `Loading mod FTweaks 0.0.3 (data.lua)`

**Comment by FadingFog** [comment]
Then how to use the github version of the mod?

**Comment by ReikaKalseki** [comment]
You do not need the GitHub version, just matching versions.
