### ISSUE TITLE
How about add an advanced portable fusion reactor

### ISSUE THREAD

**Issue by zqr95518** [ReikaKalseki/Reika_FactorioMods_Issues#26]
I add Armageddon_1.0.14 and 5dim_battlefield_0.15.9. And because of this, I can't defence the the huge worms. It has 7w HP and 90% laser defence. Well it's a good challege. You can have try Armageddon_1.0.14, perhaps you will like it.

**Comment by ReikaKalseki** [comment]
Huge meaning Oreverhaul's behemoth (green)? Or some other-mod equivalent?

I do not want to add more tiers of fusion reactor, given that they are just magic power spawners.

**Comment by zqr95518** [comment]
Behemoth is not the largest one the biggest I saw have 10w HP. Armageddon_1.0.14 add some types of experienced worm, and 5dim add some more type of worms like laser worm have 90% laser defence.
So I use hit and run, but my home can't run. Once I use the rocket silo I nearly lose my home.

**Comment by zqr95518** [comment]
You can have a try to test the balence with there equipment by use there mods.☺

**Comment by ReikaKalseki** [comment]
> Once I use the rocket silo I nearly lose my home.

This is what EndgameCombat is for, but more power armor equipment will not help defend your base.

**Comment by zqr95518** [comment]
Emmmm, maybe I should add more lazer tower and more reactor.
