### ISSUE TITLE
Just a naming issue (something small)

### ISSUE THREAD

**Issue by PaladinFallen** [ReikaKalseki/Reika_FactorioMods_Issues#260]
![2_1](https://user-images.githubusercontent.com/43867049/85637452-3e2d8c00-b651-11ea-9a7f-30c69c5db02d.jpg)

May need to add in the locale\en\names.cfg file under [technology-name] or line 34: insulated-wagon=Insulated Fluid Wagon

**Comment by ReikaKalseki** [comment]
I fixed this a couple days ago, which was just released.
