### ISSUE TITLE
0.18.34 Bad Argument

### ISSUE THREAD

**Issue by yofreak** [ReikaKalseki/Reika_FactorioMods_Issues#261]
hey,

i got an error with version 0.18.34.

![Endgame](https://user-images.githubusercontent.com/253581/86024365-3133e280-ba2d-11ea-87dc-4ce135d5b480.PNG)

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by Glendening** [comment]
Error appears to still be occurring? Was the update released?

```
Failed to load mods: __EndgameCombat__/data-updates.lua:6: __DragonIndustries__/entities.lua:27: bad argument #2 of 3 to 'max' (number expected, got nil)
stack traceback:
	[C]: in function 'max'
	__DragonIndustries__/entities.lua:27: in function 'addResistance'
	__EndgameCombat__/prototypes/overrides.lua:74: in main chunk
	[C]: in function 'require'
	__EndgameCombat__/data-updates.lua:6: in main chunk
stack traceback:
	[C]: in function 'require'
	__EndgameCombat__/data-updates.lua:6: in main chunk

Mods to be disabled:
• EndgameCombat (1.18.10)
```

**Comment by yofreak** [comment]
> 
> 
> Error appears to still be occurring? Was the update released?
> 
> ```
> Failed to load mods: __EndgameCombat__/data-updates.lua:6: __DragonIndustries__/entities.lua:27: bad argument #2 of 3 to 'max' (number expected, got nil)
> stack traceback:
> 	[C]: in function 'max'
> 	__DragonIndustries__/entities.lua:27: in function 'addResistance'
> 	__EndgameCombat__/prototypes/overrides.lua:74: in main chunk
> 	[C]: in function 'require'
> 	__EndgameCombat__/data-updates.lua:6: in main chunk
> stack traceback:
> 	[C]: in function 'require'
> 	__EndgameCombat__/data-updates.lua:6: in main chunk
> 
> Mods to be disabled:
> • EndgameCombat (1.18.10)
> ```

No still 0.18.10 with this error. Maybe at his next update.
