### ISSUE TITLE
DI fluid recipes not usable? No Angels petro or other conversion?

### ISSUE THREAD

**Issue by Glendening** [ReikaKalseki/Reika_FactorioMods_Issues#263]
I don't see a conversion recipe in angels petro chem or any other mod I have for most of the fluids created by Dragon Industries to convert them into the usable gas-"name" fluids. This makes them unusable if crafted. Am I missing something?

**Comment by ReikaKalseki** [comment]
They are producible if and only if their ingredients exist (all Bob fluids). They are only there for mod compat.

**Comment by Glendening** [comment]
I understand for mod compatibility. But which mod are they being generated to be compatible for? Because in their current form I don't see what mod, Bob, Angels, Etc can actually use them?

**Comment by ReikaKalseki** [comment]
My mod Pheromones.
