### ISSUE TITLE
high resolution support?

### ISSUE THREAD

**Issue by combow** [ReikaKalseki/Reika_FactorioMods_Issues#267]
146.616 Mods to disable:Failed to load mods: File not found: __NauvisDay__/graphics/terrain/stone-path/hr-stone-path-o.png

Mods to be disabled:
窶｢ NauvisDay (1.18.12)

**Comment by combow** [comment]
Simply because there was no folder called stone-path in the path shown, 
I solved it by copying a folder of the same name from base.

**Comment by ReikaKalseki** [comment]
NVDay does not add stone path...

**Comment by combow** [comment]
I tested it.
As a result, we were able to confirm that the aforementioned error occurs when used in conjunction with Platform MOD.

In other words, we will only let you know the results of the test.
Report the actual problem on the part of the mod in question.

**Comment by ReikaKalseki** [comment]
I use platforms alongside NVDay without issue.

**Comment by combow** [comment]
I report the author of Platforms MOD have fixed this problem.
Actually, the problem was gone.
