### ISSUE TITLE
Error on boot in createRefinery.

### ISSUE THREAD

**Issue by combow** [ReikaKalseki/Reika_FactorioMods_Issues#268]
70.276 Error ModManager.cpp:1514: Failed to load mod "NauvisDay": __NauvisDay__/data-updates.lua:6: __NauvisDay__/prototypes/refinery.lua:26: attempt to perform arithmetic on field 'emissions_per_minute' (a nil value)
stack traceback:
	__NauvisDay__/prototypes/refinery.lua:26: in function 'createRefinery'
	__NauvisDay__/prototypes/refinery.lua:135: in main chunk
	[C]: in function 'require'
	__NauvisDay__/data-updates.lua:6: in main chunk
stack traceback:
	[C]: in function 'require'
	__NauvisDay__/data-updates.lua:6: in main chunk
  70.279 Loading mod core 0.0.0 (data.lua)
  70.790 Checksum for core: 3495353602
  70.864 Error ModManager.cpp:1514: Error in assignID: recipe-category with name 'crafting' does not exist.

Source: default (utility-sprites).
  70.948 Initial atlas bitmap size is 16384
  70.949 Created atlas bitmap 2048x544 [icon, not-compressed, mipmap, linear-minification, linear-magnification, linear-mip-level]
  70.955 Texture processor created (2048). GPU accelerated compression Supported: yes, Enabled: yes/yes. Test passed. YCoCgDXT PSNR: 35.83, BC3 PSNR: 33.82
  70.970 Parallel Sprite Loader initialized (threads: 15)
  71.020 Sprites loaded
  71.032 Generated mipmaps (5) for atlas [0] of size 2048x544   
  71.032 Custom mipmaps uploaded.
  71.037 Factorio initialised
  71.042 Mods to disable:Failed to load mods: __NauvisDay__/data-updates.lua:6: __NauvisDay__/prototypes/refinery.lua:26: attempt to perform arithmetic on field 'emissions_per_minute' (a nil value)
stack traceback:
	__NauvisDay__/prototypes/refinery.lua:26: in function 'createRefinery'
	__NauvisDay__/prototypes/refinery.lua:135: in main chunk
	[C]: in function 'require'
	__NauvisDay__/data-updates.lua:6: in main chunk
stack traceback:
	[C]: in function 'require'
	__NauvisDay__/data-updates.lua:6: in main chunk

Mods to be disabled:
窶｢ NauvisDay (1.18.12)

Exception handling should be implemented assuming entities that do not have a value such as emissions_per_minute, 
which is a refinery for convenience.

**Comment by combow** [comment]
In addition, I started the game with an additional exception handling.

**Comment by ReikaKalseki** [comment]
#215 #213 #168
