### ISSUE TITLE
Productivity module

### ISSUE THREAD

**Issue by combow** [ReikaKalseki/Reika_FactorioMods_Issues#270]
Filtered refinery with productivity module will increase Air Filter Casing infinitery.

If not being able to use the productivity module is the normal state of this mod, 
then I'd have to say it's a design that ruins one of the directions of the challenge.

So, the recipe for making the filter reusable, and the filter itself, 
can be used in the refinery's Incorporate the changes into the recipe, 
such as preventing the refinery from draining the filter (You may want to consider it.)

**Comment by ReikaKalseki** [comment]
As of 0.17, I believe ingredients can be made into "catalysts" that are not affected by productivity, so that this can be fixed properly.

**Comment by combow** [comment]
I see.
I'm looking forward to it.
