### ISSUE TITLE
Cant start game

### ISSUE THREAD

**Issue by UmbraSicario** [ReikaKalseki/Reika_FactorioMods_Issues#272]
Hey there, I have been using your mod for a while now and love the many new ways to defend myself against the biters! However The last couple of times I have tried to boot up factorio, it crashes and throws the attached error message. I have a good amount of mods installed but it was working fine up until a week ago, at least thats when I first tried to boot up the game and had it fail. Please let me know if you need any more information, Id be happy to provide it! Thank you for a great mod! 
![20200719082113_1](https://user-images.githubusercontent.com/36134748/87875775-413e4280-c999-11ea-9995-31f429db1c02.jpg)

**Comment by ReikaKalseki** [comment]
This is related to the most recent game update, and is already fixed.
