### ISSUE TITLE
Failed to load mods: ... __DragonIndustries__/recipe.lua:213: No such item 'tungsten-plate' in recipe!

### ISSUE THREAD

**Issue by FadingFog** [ReikaKalseki/Reika_FactorioMods_Issues#273]
Factorio latest beta 0.18.x, latest FTweaks, mod list in .log file
![image](https://user-images.githubusercontent.com/10418075/87932887-f144a600-ca94-11ea-8bd7-cdb213fd6745.png)
https://pastebin.com/qT77WpsZ   <-- factorio.log

**Comment by ReikaKalseki** [comment]
What is the normal recipe for the T3 electrolyzer now?

**Comment by FadingFog** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/10418075/88390845-b9559f80-cdc1-11ea-813d-a5e227386bd4.png)

**Comment by ReikaKalseki** [comment]
Oh, it natively uses aluminum. Convenient.
