### ISSUE TITLE
Bug 0.18.47

### ISSUE THREAD

**Issue by yofreak** [ReikaKalseki/Reika_FactorioMods_Issues#276]
![Endgame](https://user-images.githubusercontent.com/253581/89917330-f78ff300-dbf8-11ea-91a9-c9db9aa8af7f.JPG)

I got this bug starting with 0.18.47

**Comment by ReikaKalseki** [comment]
What mods do you have that add locomotives?

**Comment by yofreak** [comment]
> 
> 
> What mods do you have that add locomotives?

ElectricTrain_0.18.1 is the only one

**Comment by vizthex123** [comment]
I noticed you closed my issue, but after reading this one wanted to add that I have [Fusion Train](https://mods.factorio.com/mod/FusionTrain) (version 0.18.1) installed.

Disabling the mod makes Endgame Combat work fine.

**Comment by Mapellicane** [comment]
Able to work around this error by removing lines 85-100 in the file specified by the startup error; thus removing the train penetration feature.  Not sure if its stable but the game loads.
