### ISSUE TITLE
[Endgame Combat] Turret Logistic Chests are invincible, and aren't selectable.

### ISSUE THREAD

**Issue by PlatinumFrog** [ReikaKalseki/Reika_FactorioMods_Issues#277]
Hello. I ran into some problems while building a turret wall.
The ammo requester chests on turrets are not selectable to adjust logistics; Only the actual turret is.
The ammo requester chests on regular vanilla turrets do not get removed from the world when the respective turret is mined or destroyed by weapons, enemies, and/or vehicles.
The ammo requester chests on regular vanilla turrets, after their respective turret has been destroyed, cannot be damaged by anything, or mined by the player.
Here is a picture to give you more of an idea.
![Turret](https://user-images.githubusercontent.com/4785824/90094506-1e831d80-dcfc-11ea-8cda-ed70d531ce90.png)
UPDATE: I Loaded up a save and tried mining the regular turrets, and the Turret Logistic chests seem to be getting removed along with the turret. So the second problem might be solved... I think. (Would you mind maybe checking for what might have caused it in the first place?) The first and third problems are still happening. Another thing I noticed is that when I use an upgrade planner to try and upgrade gun turrets to concussion turrets, The gun turrets do not get selected for upgrade with the planner.

**Comment by PlatinumFrog** [comment]
UPDATE: I Loaded up a save and tried mining the regular turrets, and the Turret Logistic chests seem to be getting removed along with the turret. So the second problem solved I think. The first and third problems are still happening.

**Comment by ReikaKalseki** [comment]
I have already fixed this for the next release.

**Comment by PlatinumFrog** [comment]
Oh ok sorry.
