### ISSUE TITLE
Crashes on new game start (v1.0.0 + "Dana: crafting tree" mod)

### ISSUE THREAD

**Issue by safronov-nikolai** [ReikaKalseki/Reika_FactorioMods_Issues#279]
https://mods.factorio.com/mod/dana/discussion/5f38a575532359df0888b9fa

Game ver 1.0.0, "Dragon Industries - Nauvis Division" + "Nauvis Day" + "Dana: crafting tree" = Crash
When you click "Play" to start a game new.

The mod Dana: crafting tree/graph explorer (0.2.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event dana::on_init()
dana/lua/model/BoilerTransform.lua:82: attempt to index global 'Logger' (a nil value)
stack traceback:
dana/lua/model/BoilerTransform.lua:82: in function 'tryMake'
dana/lua/model/TransformsDatabase.lua:116: in function 'rebuild'
dana/lua/model/PrototypeDatabase.lua:82: in function 'rebuild'
dana/lua/model/PrototypeDatabase.lua:54: in function 'new'
dana/lua/Dana.lua:54: in function 'new'
dana/lua/EventController.lua:38: in function <dana/lua/EventController.lua:33>

Thank you for the great mods! Keep it up ^_^

**Comment by ReikaKalseki** [comment]
This is not my doing.
