### ISSUE TITLE
Endgame Combat incompatible with mod Ammo Box: crash on load

### ISSUE THREAD

**Issue by sapid** [ReikaKalseki/Reika_FactorioMods_Issues#28]
Factorio version: 0.15.33 (build 30852, win64, steam) (latest as of today)
Endgame Combat version: 1.0.24 (latest as of today)
[Ammo Box](https://mods.factorio.com/mods/Afforess/AmmoBox) version: 1.1.0 (latest as of today)

I narrowed it down to these two by disabling all other mods being used.

To reproduce, add both mods to the mod folder and launch the game. The game will crash during loading with the following error message:

![image](https://user-images.githubusercontent.com/378681/29555123-770cacca-86d6-11e7-9d7e-e04ec54f9cb7.png)

Crash log is [here](https://gist.github.com/sapid/05e912926bc8eba689c6310b1aa4deaa)

Let me know if you need any additional info.

**Comment by sapid** [comment]
[Crash log](https://gist.github.com/sapid/05e912926bc8eba689c6310b1aa4deaa)

**Comment by ReikaKalseki** [comment]
This is known and because AmmoBox is not using the correct size icons. And you do not need AmmoBox installed anyways, because EGCombat has crated ammo on its own.

**Comment by sapid** [comment]
Duly noted.

Apart from that, the primary draw for myself for using Ammo Box is not the boxed ammo but the logistic slot it adds to turrets. Pretty easy to do manually, but a nice quality of life feature.

**Comment by ReikaKalseki** [comment]
I thought that was a different mod.

**Comment by sapid** [comment]
There may be another mod! If there is, I'd be keen to know about it, especially if it's compatible with Endgame Combat - I'd rather keep Endgame Combat in my pack rather than Ammo Box. 

Ammo Box offers it with some turrets. 

> Gun Turret Mk2: Has a range of 25, does 2x base damage as regular gun turret, has a logistic slot & can request items from storage network

**Comment by ReikaKalseki** [comment]
I might instead be able to add a research that adds logistic slots to *all* ammo turrets, which to me is more gameplay-friendly than a special turret type.

**Comment by ReikaKalseki** [comment]
Done.

**Comment by sapid** [comment]
Sweet!

**Comment by ReikaKalseki** [comment]
It will be released once #29 is fixed.
