### ISSUE TITLE
Crashes on Factorio v 1.0

### ISSUE THREAD

**Issue by shda5582** [ReikaKalseki/Reika_FactorioMods_Issues#289]
Ever since upgrading to v1.0, I've been receiving a crash when I try to start this up, same as [#285](url) for reference.  I do have the Electric Train .18.1 mod installed.  In troubleshooting, I disabled the Train mod and enabled Endgame Combat, and it loaded up just fine with no error or crashes.  Hope this info helps for a debug.

**Comment by ReikaKalseki** [comment]
#276 is the actual one.
