### ISSUE TITLE
[Shield dome circuit persistence] I cant destroy this entity and my bot stuck reparing it

### ISSUE THREAD

**Issue by sader22** [ReikaKalseki/Reika_FactorioMods_Issues#29]
http://imgur.com/a/9bS5p

**Comment by ReikaKalseki** [comment]
It persisted after removing the dome?

**Comment by sader22** [comment]
Yes removing or destroying a dome leave this

24 Ağu 2017 08:16 tarihinde "Reika" <notifications@github.com> yazdı:

**Comment by sader22** [comment]
I can upload the save if its helps @ReikaKalseki

**Comment by ReikaKalseki** [comment]
It is working fine for me. Are you on the latest version?

**Comment by sader22** [comment]
yes Im on the latest version let me pass you my save file

**Comment by sader22** [comment]
http://www120.zippyshare.com/v/rBqnERtw/file.html here @ReikaKalseki  I think in order to use it you have to unzip then zip again because I used 7zip for compression 
edit:
or simply use that original file
http://www20.zippyshare.com/v/AVUTtMod/file.html

**Comment by sader22** [comment]
btw newly placed domes doesnt leave its circuit connection

**Comment by ReikaKalseki** [comment]
> btw newly placed domes doesnt leave its circuit connection

Then the problem is with a cache update, and is already fixed.

**Comment by sader22** [comment]
so how can I fix am I have to begin a new game

**Comment by ReikaKalseki** [comment]
Well, you can get rid of it by editing the prototype file to allow it to be mineable, then just break it.

**Comment by sader22** [comment]
ist it true because I still cant remove it from map
