### ISSUE TITLE
Endgame Combat Fails to load.

### ISSUE THREAD

**Issue by mkiplm** [ReikaKalseki/Reika_FactorioMods_Issues#292]
32.057 Mods to disable:Failed to load mods: __EndgameCombat__/data-updates.lua:6: __EndgameCombat__/prototypes/overrides.lua:95: attempt to perform arithmetic on field 'effectivity' (a nil value)
stack traceback:
	__EndgameCombat__/prototypes/overrides.lua:95: in main chunk
	[C]: in function 'require'
	__EndgameCombat__/data-updates.lua:6: in main chunk
stack traceback:
	[C]: in function 'require'
	__EndgameCombat__/data-updates.lua:6: in main chunk

Mods to be disabled:
• EndgameCombat (1.18.18)

did some digging its electric trains >.<

**Comment by ReikaKalseki** [comment]
#276 #282
