### ISSUE TITLE
Logistic interface didnt get removed

### ISSUE THREAD

**Issue by sesmidat** [ReikaKalseki/Reika_FactorioMods_Issues#295]
![Screenshot_20](https://user-images.githubusercontent.com/45059046/96310221-ec7c8900-0fd4-11eb-9602-c9646f0a15a9.png)
Normally I would just ignore but obviously is in a rather troublesome place. Seems to only happen when I remove the turrets with  construction bots.

**Comment by ReikaKalseki** [comment]
I already fixed this for the next release.
