### ISSUE TITLE
Crash on load (NauvisDay)

### ISSUE THREAD

**Issue by Delta4Phoenix** [ReikaKalseki/Reika_FactorioMods_Issues#299]
![grafik](https://user-images.githubusercontent.com/36764081/97549314-89c1bf00-19d0-11eb-9881-e100e1c027d1.png)

No idea why. I do have a lot of other mods, but given what it tells me, those don't seem to interact with this... still:
[mod-list.txt](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/5457308/mod-list.txt)

I am sad, I wanted to make my life into a biter hell with this mod mix xD

**Comment by ReikaKalseki** [comment]
This should already be fixed for the next release.
