### ISSUE TITLE
[Endgame Combat] Error on Deconstruct an Building

### ISSUE THREAD

**Issue by hasezoey** [ReikaKalseki/Reika_FactorioMods_Issues#3]
Error while running event EndgameCombat::on_player_mined_entity (ID 65)
__EndgameCombat__/control.lua:396: attempt to index field '?' (a nil value)

Reconstruct:
Build and Building (testet with 'Shokwave Turret) and Deconstruct it

**Comment by ReikaKalseki** [comment]
It is working fine for me - including for shockwave turrets - and the line of code referenced has little obvious means of causing an error. Try removing other mods.

**Comment by hasezoey** [comment]
Testet with only this mod, and it still crashes

Error while running event EndgameCombat::on_player_mined_entity (ID 65)
__EndgameCombat__/control.lua:396: attempt to index field '?' (a nil value)

Testet on 2 PCs with both seperatet downlaoded

always testet with Cheat Mode and Research all Technologis

- Windows 10 x64

**Comment by ReikaKalseki** [comment]
I have no idea what to tell you, given that it is not happening for me. Are you using the latest version?

**Comment by hasezoey** [comment]
yes, multiple checked the update button, but no reaction to update 

Factorio Version: (Steam) 0.15.x (Factorio Started) 0.15.32
Version 0.0.25

**Comment by hasezoey** [comment]
newest update changed to an other line:

Error while running event EndgameCombat::on_player_mined_entity (ID 65)
__EndgameCombat__/control.lua:476: attempt to index field '?' (a nil value)

- Version 0.0.27

**Comment by ReikaKalseki** [comment]
That line of code is [here](https://github.com/ReikaKalseki/EndgameCombat/blob/master/control.lua#L476). The only thing I can see being null is `game.entity_prototypes[basename]`, but that makes no sense whatsoever, as that would be the vanilla turret.

**Comment by hasezoey** [comment]
yeah i saw this line already, i dont know much about lua, but this can be the problem too

"and #game.entity_prototypes[getTurretBaseName(entity)].mineable_properties.products > 0 then"

i already try it in standalone, and with other mods, like 5dim, both the same issue, but like 5dims turrets work, ... can it be that this 'Range Boost(/ed)' could be the problem?

**Comment by ReikaKalseki** [comment]
No, because I already check that `game.entity_prototypes[getTurretBaseName(entity)].mineable_properties` exists, and if `game.entity_prototypes[getTurretBaseName(entity)].mineable_properties.products` was null, the error would be "tried to get the size of nil", not "indexed ?", which is an error received when attempting to index a nonexistent object (eg table[a][b] where table[a] does not exist).

**Comment by hasezoey** [comment]
is in the EndGame Combat mod any debug option?, when yes i would try to make more info ...

**Comment by ReikaKalseki** [comment]
No, though I am not against adding such things. What information should be debugged?

Also, you can simply extract the mod and start editing the .lua files. `game.print(string/number)` is the typical output method.

**Comment by hasezoey** [comment]
okey, i try to get more info

**Comment by hasezoey** [comment]
... i tryed it yet, added 3 lines of 'game.print' with the 3 'ifs' and got the problem at the first if

```lua
game.print("(if 1) string.find: " .. string.find(entity.name, "rangeboost"))
```
(with the exactly the same error)

(or do i think wrong because of other languages string makeing?)

**Comment by ReikaKalseki** [comment]
`entity` *cannot* be null, as it is used prior (which would throw an error earlier) and supplied by the event. Nor can `name` be null because that is impossible; the game would not even load.

**Comment by hasezoey** [comment]
... Im Really sorry, sometimes (yet) im really stupid, and forget to replace the files, the thing i wrote above was wrong, not the game.print it was still the if

yet i really testet it and
```lua
game.print("(if 1) string.find: " .. string.find(entity.name, "rangeboost"))
```
was "(if 1) string.find: 18", sorry
the second was the problem
```lua
game.print("if 2" .. game.entity_prototypes[getTurretBaseName(entity)].mineable_properties)
```

Im Really Sorry >w<

**Comment by ReikaKalseki** [comment]
Print `getTurretBaseName(entity)`.

**Comment by hasezoey** [comment]
```lua
game.print("getTurretBaseName(entity): " .. getTurretBaseName(entity))
```
gave "getTurretBaseName(entity): shockwave-turret-"

its confusing, or?

**Comment by ReikaKalseki** [comment]
...With the dash on the end? Because I can easily see that causing this error, but it would also be happening for me. And indeed, the obvious fix - changing the substring index from -2 to -3, to clip off the last "-", actually *causes* an error for me.

I am now wondering if Lua [string.substring](https://github.com/ReikaKalseki/EndgameCombat/blob/master/functions.lua#L232) is OS dependent or something...

**Comment by hasezoey** [comment]
changed
```lua
name = string.sub(name, 1, -string.len("-rangeboost-")-2)
//to
name = string.sub(name, 1, -string.len("-rangeboost-")-3) 
```

and yet 
"attempt to concatenate field 'mineable_properties' (a table value)"
(changeing when replaceing with original code)

**Comment by hasezoey** [comment]
changed it, and yet all is function (-2 to -3)

- thanks that it is working now, like it ^^

**Comment by ReikaKalseki** [comment]
I want to know what is causing this discrepancy. What OS are you on?

**Comment by hasezoey** [comment]
Windows 10 x64 Home, and Pro

**Comment by ReikaKalseki** [comment]
I am on Win7, which should not be different. Do we perhaps have different Lua parsers or versions?

**Comment by hasezoey** [comment]
only info i could get:

Version: 0.15.32 (build 30820, win64, steam)
Binary Version: 64
Map input version: 0.12.0-0
Map output version: 0.15.32-3

with Commandline execute "factorio.exe --version"

and with "/c game.player.print(_VERSION)"
i got "Lua 5.2"

**Comment by ReikaKalseki** [comment]
I have no idea what is going on.
