### ISSUE TITLE
Subgroup of Geothermal wells

### ISSUE THREAD

**Issue by Arcitos** [ReikaKalseki/Reika_FactorioMods_Issues#30]
Would you mind putting geothermal wells (the item) into the extraction-machine group? They are affected by the miner productivity bonus as well, producing a resource and are not immediately related to energy production. What do you think?

**Comment by ReikaKalseki** [comment]
Sure. What is the actual name of that subgroup?

**Comment by Arcitos** [comment]
This item subgroup is called "extraction-machine", at least this is the group of the pumpjack item.

**Comment by ReikaKalseki** [comment]
Done.
