### ISSUE TITLE
Endgame Combat incompatibility with Titanium

### ISSUE THREAD

**Issue by Trimethylaluminium** [ReikaKalseki/Reika_FactorioMods_Issues#300]
![Снимок экрана (11)](https://user-images.githubusercontent.com/74516916/99202284-98291c80-27bf-11eb-8700-f142f7b43087.png)

**Comment by brevven** [comment]
Sorry I just noticed this after opening another issue: https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/issues/320

I've linked a PR that solves this incompatibility, in that issue.

**Comment by brevven** [comment]
Note -- I've developed a workaround in Titanium for the incompatibility at the moment.
