### ISSUE TITLE
Think is incompatibility with other mods

### ISSUE THREAD

**Issue by syntxx-error** [ReikaKalseki/Reika_FactorioMods_Issues#302]
Maybe can someone help me with this issue...
If u want a Full list of my mods write me!

  27.001 Error ModManager.cpp:1514: Failed to load mod "EndgameCombat": __EndgameCombat__/data-updates.lua:6: __EndgameCombat__/prototypes/overrides.lua:95: attempt to perform arithmetic on field 'effectivity' (a nil value)
stack traceback:
	__EndgameCombat__/prototypes/overrides.lua:95: in main chunk
	[C]: in function 'require'
	__EndgameCombat__/data-updates.lua:6: in main chunk
stack traceback:
	[C]: in function 'require'
	__EndgameCombat__/data-updates.lua:6: in main chunk
  27.003 Loading mod core 0.0.0 (data.lua)
  27.184 Checksum for core: 3692526182
  27.315 Error ModManager.cpp:1514: Error in assignID: recipe-category with name 'crafting' does not exist.

Source: default (utility-sprites).
  27.401 Initial atlas bitmap size is 16384
  27.402 Created atlas bitmap 2048x560 [icon, not-compressed, mipmap, linear-minification, linear-magnification, linear-mip-level]
  27.402 Created virtual atlas pages 4096x4096x0
  27.442 Texture processor created (2048). GPU accelerated compression Supported: yes, Enabled: yes/yes. Test passed. YCoCgDXT PSNR: 35.83, BC3 PSNR: 33.82
  27.543 Parallel Sprite Loader initialized (threads: 3)
  27.926 Sprites loaded
  27.975 Generated mipmaps (5) for atlas [0] of size 2048x560   
  27.975 Custom mipmaps uploaded.
  27.980 Factorio initialised
  27.986 Mods to disable:Failed to load mods: __EndgameCombat__/data-updates.lua:6: __EndgameCombat__/prototypes/overrides.lua:95: attempt to perform arithmetic on field 'effectivity' (a nil value)
stack traceback:
	__EndgameCombat__/prototypes/overrides.lua:95: in main chunk
	[C]: in function 'require'
	__EndgameCombat__/data-updates.lua:6: in main chunk
stack traceback:
	[C]: in function 'require'
	__EndgameCombat__/data-updates.lua:6: in main chunk

Mods to be disabled:
• EndgameCombat (1.18.24)

**Comment by ReikaKalseki** [comment]
#276 #282 #292
