### ISSUE TITLE
[Question] Update to 1.1?

### ISSUE THREAD

**Issue by Piglit** [ReikaKalseki/Reika_FactorioMods_Issues#304]
Hey,

do you plan to update your Mods to Factorio Version 1.1 soon?

Since my [AgeOfFlintAndStone](https://mods.factorio.com/mod/AgeOfFlintAndStone) Mod depends on your EarlyExtensions mod, I would be happy to see both of them be playable with the newest Factorio Version.

Regards, Pithlit

**Comment by jrlester70** [comment]
From 1.1 onwards, they're not supporting the backwards compatibility for 0.18. I think in most cases it just needs the json updated, but means I can't use any of your 0.18 mods either :( Shame, since there are some really great mods in your library

**Comment by MPeti1** [comment]
I'm using Geothermal along a lot of other mods, and only this one was left. I can't just remove it temporarily because my power production is based on this :/

**Comment by MPeti1** [comment]
@ReikaKalseki I've just tested the coremod and Geothermal, for now they seem to be fine, only needing changes in info.json.
They didn't crash the game, and both geothermal wells and heat exchangers are working as intended, both before and after rebuilding them.  
It's ok if you don't have enough time to test them properly, just wanted to let you know that it looks promising

**Comment by ReikaKalseki** [comment]
Geothermal and a DI for it have been updated; a few others are ready to go soon. The bigger mods will take some more time.
