### ISSUE TITLE
Turret Logistic Interface remains

### ISSUE THREAD

**Issue by generalsnipe** [ReikaKalseki/Reika_FactorioMods_Issues#31]
When removing turrets, the interface seems to remain. 
![image](https://user-images.githubusercontent.com/31417148/29786715-db04f78a-8bf1-11e7-98ee-cf1c3544f46f.png)

No way to remove.

**Comment by ReikaKalseki** [comment]
It is not doing that for me, and the large maximum health means you are using an old version. Also see #29.

**Comment by generalsnipe** [comment]
Sadly, I am on the latest version according to the Mods.factorio.com website:
![image](https://user-images.githubusercontent.com/31417148/29832556-39c00f64-8cae-11e7-9824-85220b1a7366.png)

![image](https://user-images.githubusercontent.com/31417148/29832628-7387a946-8cae-11e7-970a-e7510ae0f760.png)

**Comment by ReikaKalseki** [comment]
Did 1.0.40 not get uploaded?

Well, I am uploading 1.0.42 now.

**Comment by generalsnipe** [comment]
I manually pulled your files from here, and it seems to have moved the chest to the bottom right corner of the turret. Still can not delete chest. Will get snapshot in a bit.

**Comment by generalsnipe** [comment]
ReikaKalseki, Thank you for the help. Looks like the mod has been updated to 1.0.42.
