### ISSUE TITLE
cannot research tech with Industrial Revolution 2

### ISSUE THREAD

**Issue by Gforce4u** [ReikaKalseki/Reika_FactorioMods_Issues#311]
Although prelimanary techs are researched, geothermal research cannot be researched. It stays red.
![afbeelding](https://user-images.githubusercontent.com/36045825/112717058-64d36880-8eea-11eb-98ca-d0885ccd532e.png)

**Comment by ReikaKalseki** [comment]
Does this happen with no other mods? It works for me.

**Comment by Gforce4u** [comment]
It is with IR2 only loaded also. Maybe need to force the tech if installed later? Same is happening with distribution centers if you add it later. I did it with this mod also so could be a solution if i knew what the command is.

If you need a savegame i can send it.

Grtz Gerrit



Verzonden vanuit Mail voor Windows 10

Van: Reika
Verzonden: maandag 29 maart 2021 03:13
Aan: ReikaKalseki/Reika_FactorioMods_Issues
CC: Gforce4u; Author
Onderwerp: Re: [ReikaKalseki/Reika_FactorioMods_Issues] cannot research techwith Industrial Revolution 2 (#311)

Does this happen with no other mods? It works for me.

**Comment by ReikaKalseki** [comment]
I think I see what is going on. Geothermal tech depends on *five* prereqs, but your image only shows four:

```lua

    prerequisites =
    {
		"fluid-handling",
		"flammables",
		"electric-engine",
		"advanced-electronics",
		"concrete",
    },
```

He is removing the 'flammables' tech from the tree (the `hidden` property) and making it unobtainable but not removing it from other mods' tech prereqs. This is a bug/design error on his end. For now you can just use the console to give yourself that missing tech and then the research should work normally.

After speaking with others on the Factorio discord, where they mentioned the hidden property, part of me wonders if this is a botched attempt at removing the tech and working around the fact that doing so normally (without doing the above mentioned correction) will crash a whole litany of mods. That is, I wonder if the author of IR initially tried outright deleting the tech, saw the crashes, and went to `hidden` as a "backup" plan without really realizing what he was doing.
