### ISSUE TITLE
Breaks upon smart belt tunneling

### ISSUE THREAD

**Issue by Garr890354839** [ReikaKalseki/Reika_FactorioMods_Issues#312]
Whenever I attempt to use the new smart tunneling feature, it breaks...

**Comment by ReikaKalseki** [comment]
What?

**Comment by Garr890354839** [comment]
It being the EasyCreative mod. I didn't realize that all the mods had the same issues page.

**Comment by Garr890354839** [comment]
The smart tunneling feature I am talking about is part of the base game. While placing belts in a straight line, if there is an obstacle in the way, the game will place underground belts spanning the gap automatically.

**Comment by ReikaKalseki** [comment]
Fixed.
