### ISSUE TITLE
Geothermal water filter, "no recipe" ---- FIXED it just needs "Alien Biomes" Mod to also be running

### ISSUE THREAD

**Issue by Taurondir** [ReikaKalseki/Reika_FactorioMods_Issues#313]
Oh no someone just told me it might only be enabled when Alien Biomes is active (I was having a convo in Discord telling someone I'd ask the mod author) so sorry for wasting your time :/

We were running a game on 1.1.30 with a lot of mods and when I put down Geothermal water filter and clicked it, it came up with an empty box for "usable recipes". I thought maybe our game was the issue, so I called up a clean 1.1.32 with only your mod and the support mod of yours, then did a "/cheat" to unlock everything, and it still showed "no avaliable recipies" on the box that opens.

I'm not sure what is happening or if I'm missing something so I thought I'd ask here.

Thank you.
Marco.

**Comment by Taurondir** [comment]
Well now I feel silly.

**Comment by ReikaKalseki** [comment]
Geothermal does *not* depend on AlienBiomes.
