### ISSUE TITLE
Behemoth size category not spawning (BiterBias)

### ISSUE THREAD

**Issue by Vexxel** [ReikaKalseki/Reika_FactorioMods_Issues#314]
BiterBias version 1.105.1

Having an issue when it comes to the evolution factor of spitters from spawners; it seems like the mod disables the behemoth category from spawning at all. My evolution factor is currently 0.96 and there is a 0% chance for behemoth spitters spawning from their spawner at all. (Usually it would be around 15-20%)

This issue also comes into effect if you have the setting "Increased probability of larger biters" enabled as well, causing even biter spawners to not ever spawn the behemoth category (0.96 evolution factor just says "Big biter: 100%".

**Comment by ReikaKalseki** [comment]
I am pretty sure green spitters only appear at 9**9**%, unless that changed in some version since 0.12 (which is when BiterBias was written). I do remember biters appearing earlier than spitters.

**Comment by ReikaKalseki** [comment]
OK, here is the lua data:

Biter spawner:
    result_units = (function()
                     local res = {}
                     res[1] = {"small-biter", {{0.0, 0.3}, {0.6, 0.0}}}
                     if not data.is_demo then
                       -- from evolution_factor 0.3 the weight for medium-biter is linearly rising from 0 to 0.3
                       -- this means for example that when the evolution_factor is 0.45 the probability of spawning
                       -- a small biter is 66% while probability for medium biter is 33%.
                       res[2] = {"medium-biter", {{0.2, 0.0}, {0.6, 0.3}, {0.7, 0.1}}}
                       -- for evolution factor of 1 the spawning probabilities are: small-biter 0%, medium-biter 1/8, big-biter 4/8, behemoth biter 3/8
                       res[3] = {"big-biter", {{0.5, 0.0}, {1.0, 0.4}}}
                       res[4] = {"behemoth-biter", {{0.9, 0.0}, {1.0, 0.3}}}
                     end
                     return res
                   end)()

Spitter spawner:
    result_units = (function()
                     local res = {}
                     res[1] = {"small-biter", {{0.0, 0.3}, {0.35, 0}}}
                     res[2] = {"small-spitter", {{0.25, 0.0}, {0.5, 0.3}, {0.7, 0.0}}}
                     res[3] = {"medium-spitter", {{0.4, 0.0}, {0.7, 0.3}, {0.9, 0.1}}}
                     res[4] = {"big-spitter", {{0.5, 0.0}, {1.0, 0.4}}}
                     res[5] = {"behemoth-spitter", {{0.9, 0.0}, {1.0, 0.3}}}
                     return res
                   end)()

Indeed it does look like both should be at 90%, and that BiterBias is just outdated.
