### ISSUE TITLE
Can't load Fast Furnaces

### ISSUE THREAD

**Issue by Legowaffles** [ReikaKalseki/Reika_FactorioMods_Issues#315]
First off, this is an issue people have apparently had in the [past](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/issues/278).

The major difference here is, I quite literally do NOT have the file in question. I have verified the integrity of the game files, I have uninstalled and reinstalled Factorio. The file is still nowhere in the graphics folder.

For reference, I have just updated Factorio from version 0.18.18 after not having played since May of last year. Perhaps I missed the file at some point because of that?

Some potentially relevant information:
Factorio Version: 1.1.32 (build 58364, win64)
Fast Furnaces Version: 1.105.1
Dragon Industries - Nauvis Division Version: 1.105.1
Bobmining: Uninstalled
Bobpower: Uninstalled

Image of Error: 
![20210504130123_1](https://user-images.githubusercontent.com/83663853/117042124-930e4a00-acd9-11eb-9e02-e40935e275a0.jpg)

Image of __Base__/Graphics/Technology Folder:
![Graphics Technology Folder](https://user-images.githubusercontent.com/83663853/117042643-3b241300-acda-11eb-8ea7-16124b24b344.png)

What do I do? What CAN I do?

**Comment by ReikaKalseki** [comment]
They renamed the tech sprites again. I updated FF, but until then you will need to either make the images (ie just copy a vanilla one and rename it) or edit the FF prototype definitions to refer to one of the three images that actually exist.

**Comment by Legowaffles** [comment]
Alright, thank you.

**Comment by Avakining** [comment]
> I updated FF

It still seems to not load, for the same reason. Did the patch ever get published?
