### ISSUE TITLE
EndgameCombat Bug - train override crashes for trains with void energy source  

### ISSUE THREAD

**Issue by PreLeyZero** [ReikaKalseki/Reika_FactorioMods_Issues#316]
Hi there,
When playing with 248k Endgame Combat will crash trying to override my train. Since trains with void energy source dont have fuel effectivity: 
[factorio-previous.log](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/6447291/factorio-previous.log)

**Comment by ReikaKalseki** [comment]
Can I see the train's prototype data?

**Comment by PreLeyZero** [comment]
There you go

[gr_train.zip](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/6501400/gr_train.zip)

**Comment by ReikaKalseki** [comment]
Fixed.
