### ISSUE TITLE
Another update, another bug.

### ISSUE THREAD

**Issue by Mandarman** [ReikaKalseki/Reika_FactorioMods_Issues#32]
![12345632capture](https://user-images.githubusercontent.com/30988568/29991650-ee7bc5a4-8f58-11e7-840b-147106115439.PNG)

**Comment by ReikaKalseki** [comment]
This should be impossible. This looks like the cache of turrets was not converted properly, but that should have happened the moment you loaded the save. Or is bobplates firing off the researched finish event during onConfigurationChanged (which strikes me as wrong)?

**Comment by Mandarman** [comment]
Not sure.

**Comment by ReikaKalseki** [comment]
Open the control.lua in his zip and check the onConfigurationChanged function.

**Comment by Mandarman** [comment]
![dungkeksscapture](https://user-images.githubusercontent.com/30988568/29999375-b0b1f570-9013-11e7-8ac6-a45dcaf9430b.PNG)

**Comment by ReikaKalseki** [comment]
And that apparently calls the event at some point. OK, I need to find an alternate way of updating the cache.

**Comment by ReikaKalseki** [comment]
OK, I think this is fixed.

**Comment by Mandarman** [comment]
Its not fixed.

**Comment by ReikaKalseki** [comment]
I just uploaded the fix now. Stop being impatient.

And if it still fails to work, try adding a call to `convertTurretCache()` at line 394 of my control.lua.

**Comment by Aerospacesmith** [comment]
I'm not sure if this is related to this issue, but I wasn't having this problem before the update 30 minutes ago.
![image](https://user-images.githubusercontent.com/5132118/30007988-6dbe7f6e-90df-11e7-8a3d-b6954b594488.png)

**Comment by Aerospacesmith** [comment]
This occurs when attempting to load a saved game.

**Comment by Aerospacesmith** [comment]
The problem is with the convertTurretCache() function, so I'd say this may have fixed one issue, but is causing another. Version 1.0.44 does not give any errors.

**Comment by ReikaKalseki** [comment]
Fixed and uploaded.
