### ISSUE TITLE
Mod conflict.

### ISSUE THREAD

**Issue by NoNameISNoMan** [ReikaKalseki/Reika_FactorioMods_Issues#321]
![image](https://user-images.githubusercontent.com/85317599/120713784-0d91db80-c4cb-11eb-8594-75a3bd9cb4d5.png)

That's it. Encountered while playing Seablock.

**Comment by ReikaKalseki** [comment]
The hell?

So CircuitProcessing removes techs added by other mods, and expects those mods to work?

This is not on my end, and I cannot make mods that continue to work if other mods delete random parts of them, especially when that part is already disableable in a setting whose value *must* remain a safe indicator of whether that part is present.

You can just disable the setting and should be able to load, but CircuitProcessing has a *serious* design error.
