### ISSUE TITLE
Game not loading

### ISSUE THREAD

**Issue by Garr890354839** [ReikaKalseki/Reika_FactorioMods_Issues#322]
![image](https://user-images.githubusercontent.com/10093603/121791159-dbf8ce80-cbb4-11eb-8b86-425d768c89e5.png)

**Comment by ghost** [comment]
Interesting that the windows version of factorio gives less information than the linux build.

![Screenshot_20210613_142445](https://user-images.githubusercontent.com/4485158/121822300-3ba5b700-cc53-11eb-8168-869fdb533b38.png)

Either way this seems to be a duplicate of #315

**Comment by ReikaKalseki** [comment]
It is.
