### ISSUE TITLE
Turret logistic chest persistence

### ISSUE THREAD

**Issue by dispare76** [ReikaKalseki/Reika_FactorioMods_Issues#328]
When a turret is destroyed by a player or alien sometimes the logistics box that is connected to it (blue box in the bottom corner) remains, it cannot be damaged or destroyed through normal means, a command code must be used to remove it from the game, which is a bummer if you're attempting to get achievements.

**Comment by ReikaKalseki** [comment]
This is still happening?

**Comment by dispare76** [comment]
Yes, it happens on and off, normally once a turret gets ammo / stuck in an endless "ammo critical/low" state. or is destroyed, though the second method is a bit hit and miss of when it happens.

**Comment by Xcystence** [comment]
Can confirm, It's happening with every turret I place regardless if it gets ammo or not. I came here to report this if it was not already in. looks like it may be a possible conflict with Combat Mechanics Overhaul? The only other mod the chests report interacting with is squeakthrough.

**Comment by DropTree** [comment]
same here aswell  also with combat mechanics overhaul and sqeakthrough 

also for everoyne who sees this you can delete the bugged boxes with waterfill and then just landfill the resulting hole :)

**Comment by MortisLegati** [comment]
Turret destruction causes this: removal by logistics bots causes this reliably.

**Comment by NaleshSA** [comment]
Can confirm this is happening with combat mechanics overhaul and squeakthrough for me too. Would it be possible to do like, a check whenever a turret is getting low on ammo if its logistic box is still attached? Or even better, just having it interact with any adjacent logistic chests without requiring an inserter would be more stable. Would make it play nicer with some of the bigger modded turrets also.

**Comment by qwcane** [comment]
Can confirm that this is still happening.

**Comment by Heresy-Edward** [comment]
Yup still a thing, I reset the mod just to get arid of the turret logi research

**Comment by ReikaKalseki** [comment]
Fixed.
