### ISSUE TITLE
mod failed to load on startup

### ISSUE THREAD

**Issue by Fubiki-Tania** [ReikaKalseki/Reika_FactorioMods_Issues#329]
Failed to load mod "EndgameCombat": __EndgameCombat__/prototypes/overrides.lua:95: attempt to index field 'burner' (a nil value)
stack traceback:
	__EndgameCombat__/prototypes/overrides.lua:95: in main chunk
	[C]: in function 'require'
	__EndgameCombat__/data-updates.lua:6: in main chunk

**Comment by Fubiki-Tania** [comment]
sorry, this is my first time using GitHub to report a bug, I forgot to use the bug tag to the issue.

**Comment by ReikaKalseki** [comment]
#316
