### ISSUE TITLE
Nauvis Day incompatible with Artisanal Reskins: Bob's Mods

### ISSUE THREAD

**Issue by LennyIndustries** [ReikaKalseki/Reika_FactorioMods_Issues#335]
When I try to load Nauvis Day it throws an error:
![Error_NauvisDay](https://user-images.githubusercontent.com/10868197/133266331-84a719a7-9910-45f0-b6d7-f7e713af035c.PNG)
At first I had an issue with [Artisanal Reskins: Bob's Mods](https://mods.factorio.com/mod/reskins-bobs/discussion/613f5e81633b6de40ab04d66) but [as the author suggested](https://mods.factorio.com/mod/reskins-bobs/discussion/613f5e81633b6de40ab04d66) I disabled the lines in the mod.
It seems that the issue is related to [Bob's Greenhouse mod](https://mods.factorio.com/mod/bobgreenhouse) but this might be because of the reskin mod. If I disable the reskin mod it loads fine.
Is it posible to add compatibility with the reskin mod?

**Comment by kirazy** [comment]
I'll handle this. I have the sprites to be able to replicate the dead Greenhouse using the new visual. I'll push the bugfix to enable Nauvis Day to work in the short term, then an update to AR Compatibility for the visuals. 

Commit kirazy/reskins-bobs@2f95a4b69b9f1e32e8c76ae3434ddc5e768ea8d4 resolves the startup errors.

**Comment by kirazy** [comment]
This is now resolved on my end with version 2.0.2.
