### ISSUE TITLE
Crash for lab tiles

### ISSUE THREAD

**Issue by saaadel** [ReikaKalseki/Reika_FactorioMods_Issues#339]
How to reproduce:
- Enable an Editor
- Add a new layer/floor
- Switch to this floor
- Set "Fill with lab tiles", regenerate tiles
- Try to move out of a center spot (move a person with WSAD)
- Crash.

===
The mod Geothermal (1.105.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Geothermal::on_chunk_generated (ID 12)
LuaTile API call when LuaTile was invalid.
stack traceback:
	[C]: in function '__index'
	__Geothermal__/control.lua:174: in function 'getSpawnData'
	__Geothermal__/control.lua:217: in function 'controlChunk'
	__Geothermal__/control.lua:237: in function <__Geothermal__/control.lua:236>

**Comment by ReikaKalseki** [comment]
#369 #281
