### ISSUE TITLE
"Effectivity" Loading Error Supersonic Trains 

### ISSUE THREAD

**Issue by Redstone551** [ReikaKalseki/Reika_FactorioMods_Issues#341]
I get this error every time I try to load Endgame Combat, and Supersonic Trains. Looked at errors #276 and the fix for it, however the code is different I could not get the fix to work. 
Thank you

Log below
[factorio-current.log](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/7272227/factorio-current.log)

**Comment by shadoxxhd** [comment]
go to EndgameCombat/prototypes/overrides.lua and replace the following line:
`proto.burner.effectivity = proto.burner.effectivity*f2`
with
`if proto.burner then proto.burner.effectivity = f2*(proto.burner.effectivity or 1) end`

**Comment by Redstone551** [comment]
Thank you! that fixed one error now ive got another to figure out ;-;

**Comment by ReikaKalseki** [comment]
This is already fixed in the other similar reports.
