### ISSUE TITLE
Update mod on mod portal

### ISSUE THREAD

**Issue by TGODiamond** [ReikaKalseki/Reika_FactorioMods_Issues#346]
The issue #329 is still present on mods.factorio.com. (I had the same problem today and I'm running the lastest version of the mod from the mod portal) 

I can see that you have fixed the issue in Update 107 but it's missing on the portal.

Are you able to update the mod on the portal so the fix is present there?

**Comment by ReikaKalseki** [comment]
This issue tracker is not for asking for updates.
