### ISSUE TITLE
Turret logistics interface remains

### ISSUE THREAD

**Issue by MistHelix** [ReikaKalseki/Reika_FactorioMods_Issues#347]
https://gist.github.com/MistHelix/24f903ade809623059845b87a4e45c30
for my modlist the issue i am experiencing is turret logistics interface are remaining after turrets are removed and cant be destroyed.
<img width="1131" alt="Screen Shot 2021-10-22 at 9 38 13 PM" src="https://user-images.githubusercontent.com/88747182/138542879-d22d4ea6-d589-44c1-81e4-dffc65bfd0df.png">

**Comment by MistHelix** [comment]
This only occurs when picked up by construction robots.

**Comment by ReikaKalseki** [comment]
#328
