### ISSUE TITLE
Orbital cannon manual pointer works in really small radius.

### ISSUE THREAD

**Issue by yobaNGE** [ReikaKalseki/Reika_FactorioMods_Issues#348]
Hello, just set satellite to space and when tried to shoot some biters at the distence figured out that i can only use manual target pointer near me, like in reach distance.

**Comment by ReikaKalseki** [comment]
Use it from the map.

That too requires visibility - back in 0.16 or 0.17 they made it so that you cannot use items outside of the "view distance" (including that of radar). I do not know how to fix this.
