### ISSUE TITLE
Line 24

### ISSUE THREAD

**Issue by MBandoch** [ReikaKalseki/Reika_FactorioMods_Issues#35]
Any ideas of what could be this?

I'm using full Bob's and Angels.

Thanks :D

![screenshot 1](https://user-images.githubusercontent.com/19311092/30071345-bc71fa06-923c-11e7-8155-c00a559ccf8a.png)

**Comment by ReikaKalseki** [comment]
This was fixed weeks ago.

**Comment by MBandoch** [comment]
But the version on Factorio Mod portal still has the bug :(

**Comment by ReikaKalseki** [comment]
Try again.

**Comment by MBandoch** [comment]
Working now, thanks :D Keep your good work !
