### ISSUE TITLE
Napalm and Neutron bomb are unlocked early

### ISSUE THREAD

**Issue by Power-President** [ReikaKalseki/Reika_FactorioMods_Issues#350]
Hey i was just playing and wondering why do i get the napaml and the nuke so early in the game (like as soon as i start) until i decided to look it up on the research/skill tree and saw that i should not have napalm and definitely not neutron bomb unlocked. idk how i didnt realize this 1 world ago. also i looking at the cost of the napalms i think they should be higher like 300 science both atleast

**Comment by ReikaKalseki** [comment]
Neither one is unlocked from the beginning, and they cost extremely high numbers of science packs. If that is not the case for you, some mod is changing something.

**Comment by FoilHatGuy** [comment]
Had the same issue. Seems to be mod interactions. Rampant arsenal is the main suspect.
