### ISSUE TITLE
Crash on Launch (Endgame Combat)

### ISSUE THREAD

**Issue by Murdermancer** [ReikaKalseki/Reika_FactorioMods_Issues#352]
Launching with my giant messy mod pile, I ran into the below error. I suspect this is due to a mod adding electric or nuclear trains not having an appropriate value there, but I'm unsure which one it might be.

My lazy solution was to comment out line 95, which allowed the mod to launch, and will _definitely have no other consequences I'm sure._

Thanks for all your work on all your mods! (I know your work from Minecraft, and was surprised and pleased to find more of the same for Factorio.)

Factorio 1.1.46, Endgame Combat 1.105.1

```
  25.949 Error ModManager.cpp:1577: Failed to load mod "EndgameCombat": __EndgameCombat__/prototypes/overrides.lua:95: attempt to perform arithmetic on field 'effectivity' (a nil value)
stack traceback:
	__EndgameCombat__/prototypes/overrides.lua:95: in main chunk
	[C]: in function 'require'
	__EndgameCombat__/data-updates.lua:6: in main chunk
  25.952 Loading mod core 0.0.0 (data.lua)
  26.190 Checksum for core: 1381136629
  26.298 Error ModManager.cpp:1577: Error in assignID: recipe-category with name 'crafting' does not exist.
```

**Comment by ReikaKalseki** [comment]
Fixed.
