### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Void586** [ReikaKalseki/Reika_FactorioMods_Issues#355]
it says it has an error with creating "Derived Capsules"

**Comment by Void586** [comment]
Mods that I think could conflict with this are:
1x1 equipment
Big Brother
Big Brother Bob Plugin
Black Market 2
Bob's Warfare
Bob's Personal Equipment
Bob's Vehicle Equipment
Combat Mechanics Overhaul
Deep Pockets
Grappling Gun
Hover Car
Light Artillery
Power Armor MK3
Rampant
Shield Projector
Solar Walls

**Comment by ReikaKalseki** [comment]
Could this be #354, perhaps?
