### ISSUE TITLE
Range Upgraded turrets lose "Base Mod" and most damage upgrades.

### ISSUE THREAD

**Issue by FantasticChimni** [ReikaKalseki/Reika_FactorioMods_Issues#356]
About what the title said, I just upgraded the range and the damage lowered on every turret I placed going forward. The only other change I could see was it not being listed under the Base Mod for the game anymore, if that has something weird to do with it?

The turrets show up on all the damage researches, including one for each range buff for the gun turrets.
![image](https://user-images.githubusercontent.com/71201572/144800033-af17c88c-6cce-4e9b-a474-16faebbe0d34.png)

**Comment by FantasticChimni** [comment]
Upon further testing the damage mod actually increases past the base turrets at higher levels of damage research. It was just weird that it dropped the damage at the start.

**Comment by ReikaKalseki** [comment]
See #385
