### ISSUE TITLE
FTweaks mod is incompatible with Bob's personal equipment

### ISSUE THREAD

**Issue by jokru** [ReikaKalseki/Reika_FactorioMods_Issues#359]
The mod assumes that `solar-panel-equipment` requires `solar-panel`, however this is not the case when [Bob's personal equipment is installed](https://mods.factorio.com/mod/bobequipment). The erroring line is 453 of `prototypes/overrides.lua`.

Log here: [https://pastebin.com/Bk2SmnfG](https://pastebin.com/Bk2SmnfG)

Relevant-seeming lines: [https://pastebin.com/Er4PgQxU](https://pastebin.com/Er4PgQxU)

**Comment by ReikaKalseki** [comment]
Fixed.
