### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by raiyuza** [ReikaKalseki/Reika_FactorioMods_Issues#36]
Step 1. Start factorio normaly (0.15.39)
Step 2. Let it load normaly
Following error appears
http://imgur.com/a/rS17D

Modlist: https://pastebin.com/pG7EhRdP
Mod settings: https://pastebin.com/dJxpcTNZ

Have tried going back 2 versions. Keep having the same problem.

**Comment by raiyuza** [comment]
I am a idiot close this.

**Comment by APolarBaer** [comment]
whats the fix for this....

**Comment by ReikaKalseki** [comment]
Same issue but different mods as #28.
