### ISSUE TITLE
Endgame combat: issues with shield projector/space exploration 

### ISSUE THREAD

**Issue by Mernom** [ReikaKalseki/Reika_FactorioMods_Issues#360]
Shield projectors should probably be added to the list of technical turrets, as the range upgrade technologies break their functionality.
Also, atm looks like your code is only running on nauvis, this probably means that it won't effect any other planets or spaceships when playing with Space Exploration.

**Comment by ReikaKalseki** [comment]
What is the projectors' internal name?

**Comment by wretlaw120** [comment]
the projector's internal name is "shield-projector"

**Comment by ReikaKalseki** [comment]
Done.
