### ISSUE TITLE
failed to load (Nauvis Day)

### ISSUE THREAD

**Issue by KalebSorcyubi** [ReikaKalseki/Reika_FactorioMods_Issues#363]
![Capture factorio](https://user-images.githubusercontent.com/82905994/152640302-5c068ec4-d800-4ed9-ae44-16a107de05f8.JPG)

seems to be incompatable with 
FactorioExtended Plus-Machines by jimmyjon711

not sure if theres anything that i can to do get this fixed im really interested in using this, but i dont wanna give up all my mk3 machines

**Comment by ReikaKalseki** [comment]
This is not actually my doing - I just copy his entity, which seems to have invalid properties.
