### ISSUE TITLE
Mod Pheromones - pheromones recipes are available without research, which is not good.

### ISSUE THREAD

**Issue by keysivi** [ReikaKalseki/Reika_FactorioMods_Issues#364]
Good day! There is no Pheromones mod topic on your forum, so I have to post here. Please forgive me for this.

Your mod is very interesting! But it has one drawback.

Pheromone recipes are available initially, although the resources for them are only available towards the middle of the game. It doesn't look very nice.

I suggest adding research on these recipes to the game. It will be much more interesting and logical.

Thanks!

**Comment by ReikaKalseki** [comment]
I assume you mean the intermediary fluids, not the pheromones themselves (as these are and always have been gated behind the appropriate tech).

I have since added some tech dependencies to these fluids.
