### ISSUE TITLE
Non-Recoverable Error When entering EE Lab Mode

### ISSUE THREAD

**Issue by adugaue** [ReikaKalseki/Reika_FactorioMods_Issues#369]
![image](https://user-images.githubusercontent.com/60800071/161366243-ad4451f9-1afc-4834-b4c6-9a1cb9710313.png)

This is the non-recoverable error that occurs when entering the special Lab surface from Editor Extensions. You can do this by entering either the Personal or Shared Lab surface while on your nauvis surface.

**Comment by nickrrichmond** [comment]
I received a similar error when using Blueprint Sandboxes, and there seemed to be some potentially relevant information in this discussion post on that mod.
https://mods.factorio.com/mod/blueprint-sandboxes/discussion/62537c9d19e3da2ada72b6d3

No fix for users, but potentially something to look into for the dev.

**Comment by cleger-decentrix** [comment]
It's not this exact issue, but there is another issue with Blueprint Sandboxes, and I have a fix pull-request open for it now: https://github.com/ReikaKalseki/Geothermal/pull/8

https://mods.factorio.com/mod/blueprint-sandboxes/discussion/625fd38f0983e164f5dc25f7

**Comment by cameronleger** [comment]
It's not this exact issue, but there is another issue with Blueprint Sandboxes, and I have a fix pull-request open for it now: https://github.com/ReikaKalseki/Geothermal/pull/8

https://mods.factorio.com/mod/blueprint-sandboxes/discussion/625fd38f0983e164f5dc25f7

**Comment by ReikaKalseki** [comment]
Fixed.
