### ISSUE TITLE
Uranium Ore

### ISSUE THREAD

**Issue by ralle030583** [ReikaKalseki/Reika_FactorioMods_Issues#37]
Miners dont work with Dirty Uranium Ore.. Copper working without Problem
Uranium Tiles also get converted to dirty Uranium but miners placed on it just refuse to work until i convert it back to normal uranium (so in gerneral uranium mining with acid is working)

P.S. Speed of Wasching Maschine is awesome (0 crafting time?) i useing loaders.. i can just use an loader for input and 2 loaders on the output and its just go through. is that intended (red belt speed and red laoders tested so far)

**Comment by ReikaKalseki** [comment]
Convert it, then place the miner. It works fine for me. And yes, the Ore Washing is not supposed to be a throughput bottleneck, just another logistics step.
