### ISSUE TITLE
No more water bypassing?

### ISSUE THREAD

**Issue by BloodyRain2k** [ReikaKalseki/Reika_FactorioMods_Issues#370]
I don't know what or why it happened, but I've had two problems with this mod after updating it a short while ago.

First was that the ore washers were rotated for some reason, which broke the water connections.
Worse though is that even after I fixed that, I noticed that they no longer seem to output water to the other side after having filled themselves, which broke my setup even more.

This is with 1.105.1 but I sadly have no idea what version I was using before...

**Comment by ReikaKalseki** [comment]
Ore washers never had "water bypass" like boilers do.
