### ISSUE TITLE
Geothermal patches going nuts.

### ISSUE THREAD

**Issue by TYoung86** [ReikaKalseki/Reika_FactorioMods_Issues#373]
Make this adjustable or adjust it to something less insane when we get further from (0,0) please.

https://forums.factorio.com/viewtopic.php?p=558982#p558982

https://github.com/ReikaKalseki/Geothermal/blob/master/control.lua#L219

It'd be nice to give an option to remove or adjust the minimum distance (dd < 300) too.

**Comment by ReikaKalseki** [comment]
All of these options have been added.
