### ISSUE TITLE
turret logistics chest is sometimes left  turret is mined, leaving an invulnerable chest that cannot be broken (not resolved despite tag)

### ISSUE THREAD

**Issue by alexx110550** [ReikaKalseki/Reika_FactorioMods_Issues#375]
![image](https://user-images.githubusercontent.com/103965709/171078357-cece766d-b16a-44c0-8bb0-9c7c2bbc8294.png)

**Comment by alexx110550** [comment]
upon further inspection, this bug only occurs when the affected turret is placed down before auto logistics and turret logistics are researched

**Comment by ReikaKalseki** [comment]
The issue here seems to be several duplicated chests.

**Comment by ReikaKalseki** [comment]
Also #357
