### ISSUE TITLE
Geothermal crash I guess?

### ISSUE THREAD

**Issue by trikop** [ReikaKalseki/Reika_FactorioMods_Issues#377]
This error consistently pops up a little while after loading my autosave, thankfully its just a random blueprint testing world, but I guess this might be useful?

The mod Geothermal (1.105.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Geothermal::on_chunk_generated (ID 12)
LuaTile API call when LuaTile was invalid.
stack traceback:
	[C]: in function '__index'
	__Geothermal__/control.lua:174: in function 'getSpawnData'
	__Geothermal__/control.lua:217: in function 'controlChunk'
	__Geothermal__/control.lua:237: in function <__Geothermal__/control.lua:236>

**Comment by ttyler3** [comment]
I get the same error with just Geothermal and Blueprint Sandboxes installed when I attempt to open the blueprint sandbox.

The mod Geothermal (1.105.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Geothermal::on_chunk_generated (ID 12)
LuaTile API call when LuaTile was invalid.
stack traceback:
	[C]: in function '__index'
	__Geothermal__/control.lua:174: in function 'getSpawnData'
	__Geothermal__/control.lua:217: in function 'controlChunk'
	__Geothermal__/control.lua:237: in function <__Geothermal__/control.lua:236>

**Comment by ReikaKalseki** [comment]
#281
