### ISSUE TITLE
FTweaks won't load with Island Spawn mod

### ISSUE THREAD

**Issue by Sleeeper** [ReikaKalseki/Reika_FactorioMods_Issues#38]
[Island Spawn](https://mods.factorio.com/mods/joshinils/island_spawn)

48.430 Loading mod FTweaks 1.0.44 (data-updates.lua)
48.475 Error ModManager.cpp:957: Unable to load "FTweaks": __FTweaks__/data-updates.lua:1: __FTweaks__/prototypes/overrides.lua:540: attempt to index field 'selection_box' (a nil value)
48.478 Loading mod core 0.0.0 (data.lua)
48.596 Checksum for core: 2985821474
48.890 Error ModManager.cpp:957: Error in assignID, recipe-category with name 'crafting' does not exist.`

[Full log](https://pastebin.com/ZgjQuMMT)
[mods used](https://pastebin.com/k7D3fggu)

Probably doesn't matter much since that mod is new and I just disabled it.

**Comment by ReikaKalseki** [comment]
Fixed.
