### ISSUE TITLE
FTweaks Cargo Ships Incompatibility Fix

### ISSUE THREAD

**Issue by Pixelguru26** [ReikaKalseki/Reika_FactorioMods_Issues#380]
[FTweaks](https://mods.factorio.com/mod/FTweaks) is incompatible with [Cargo Ships](https://mods.factorio.com/mod/cargo-ships) due to a modification performed on rail signals in line 30-31 of prototypes/overrides.lua removing the "rail-layer" collision mask.
Adding "rail-layer" back into the list fixes the incompatibility, however I don't know if that's a viable option as I do not know the reasoning behind changing the rail signal collision mask at all.

**Comment by ReikaKalseki** [comment]
The reasoning behind the change was to make the signals useful alongside rail bridge mods. I can remove that line, though, as its benefit is small.
