### ISSUE TITLE
Endgame combat 1.105.1 loading error

### ISSUE THREAD

**Issue by SpypigDev** [ReikaKalseki/Reika_FactorioMods_Issues#383]
After transferring factorio saves between computers and syncing my mod list i encountered this

```
Error loading mods

Failed to load mods: EndGameCombatFixed/prototypes/overrides.lua:95: attempt to index field 'burner' (a nil value)

stack traceback:

-EndGameCombatFixed/prototypes/overrides.lua:95: in main chunk

[C]: in function 'require'

EndGameCombatFixed/data-updates.lua:6: in main chunk
```

After doing some testing, I discovered that this error only comes up when I install the mods _Space Exploration Menu Simulations_ and _Simulation Helper_ (both newly added dependencies for Space Exploration)

**Comment by Switcherooo** [comment]
I can confirm I have the same issue. As far as I can tell this is also Factorio Version independent (tried to launch all versions from 1.1.59 to 1.1.65

**Comment by Goldiloxx** [comment]
I am also suffering from this issue

**Comment by ReikaKalseki** [comment]
#285 #381 #382
