### ISSUE TITLE
Endgame Combat + Space exploration + AAI Containers = Problem

### ISSUE THREAD

**Issue by ogdru999** [ReikaKalseki/Reika_FactorioMods_Issues#384]
![20220809155532_1](https://user-images.githubusercontent.com/110915915/183668481-a9f1a411-b95c-4b32-adb1-53c0b9952d07.jpg)

After doing some testing, I discovered that this error only comes up when I install the mods Space Exploration and AAI Containers & Warehouses (both needed for Space Exploration).

Independent from each other it works with Endgame Combat but not together.

I couldn't find anything online to fix this problem myself.

**Comment by ReikaKalseki** [comment]
"Could not find anything"? When the *last three issues* are all this error?

#285 #381 #382 #383
