### ISSUE TITLE
Crash on ammo item using 'icons' instead of 'icon'

### ISSUE THREAD

**Issue by More-Wrong** [ReikaKalseki/Reika_FactorioMods_Issues#387]
Specifically an incompatibility with True-Nukes 0.3, originally raised:
https://mods.factorio.com/mod/True-Nukes/discussion/6338637c04d88ebe799301f4
The code to create the crates doesn't accommodate the possibility of the items using 'icons' to specify the appearance rather than using 'icon'.

**Comment by ReikaKalseki** [comment]
Fixed.
