### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by ToxicMeeseeks** [ReikaKalseki/Reika_FactorioMods_Issues#388]
Anyone else receiving this error and or know how to fix it?

![Screenshot (6)](https://user-images.githubusercontent.com/115328990/194680359-c7b21ec2-59ec-46fa-b11a-25469eedd138.png)

Thank you

**Comment by ReikaKalseki** [comment]
This is a duplicate of #285 #381 #382 #383 #384 and many others, and has already been fixed.
