### ISSUE TITLE
Error When Loading

### ISSUE THREAD

**Issue by rockinsect** [ReikaKalseki/Reika_FactorioMods_Issues#389]
when loading the game it brings up several errors, even when reinstalling

*Failed to load mod "EndgameCombat": __EndgameCombat__/functions.lua:405: attempt to perform arithmetic on local 'num' (a string value)
stack traceback:
	__EndgameCombat__/functions.lua:405: in function 'Modify_Power'
	__EndgameCombat__/prototypes/overrides.lua:102: in main chunk
	[C]: in function 'require'
	__EndgameCombat__/data-updates.lua:6: in main chunk*

even with my mess of mods in the previous version it didnt bring up this error so i dont know how to fix it

**Comment by ReikaKalseki** [comment]
Fixed.
