### ISSUE TITLE
[Endgame Combat] Turret Range Research issues with "Additional Turrets" mod

### ISSUE THREAD

**Issue by EchelonRed** [ReikaKalseki/Reika_FactorioMods_Issues#39]
Hello, I noticed that someone had posted about the same issue on the Factorio Mods portal discussion section for your Endgame Combat mod but failed to post it on Github. Figured I throw a blurb on here.

It seems as though whatever esoteric code the author of the Additional Turrets has used to mass generate their Turret Damage Research entries is not playing well with having the turrets names modified by the range upgrades.  For example, it is still applying the damage bonus to cannon-turret, as opposed to cannon-turret [range+1] etc. At least that is my best guess as to what is going on. I took a look at the code to try and fix it myself, however... it is way beyond me lol.  

Here is the way the Turret Damage Research is handled for the Additional Turrets mod:
        https://pastebin.com/f4SUQaPS

Not sure if this helps at all or if this is technically even a fix on your end if the other mod is at fault given it's rather... avant-garde approach at handling the research. Thanks for any insight on this!

**Comment by ReikaKalseki** [comment]
The issue is that he is hardcoding the damage boost to a turret ID, which obviously changes as it upgrades.

Though this *can* theoretically be fixed from my end, the only way to do so would be to iterate over every research in the game, inspect their effects list, and if they have a turret ID type damage boost, add a bunch of new entries. However, while this is likely to fix the issue, it would be very slow due to the sheer number of required iterations.

A better fix would be for his research to be coded to an ammo type rather than a turret ID; this would automatically include the range boosted - and any other derivative - turrets.

**Comment by EchelonRed** [comment]
Oh wow, thanks for the quick response! I see. No worries then. I've noticed the vanilla turrets seem to be working. How are the vanilla turrets handled just out of curiosity?  Do you think I would be able to do a copy paste of the vanilla research and just replace the turret names, or would there be more required? Thanks again.

**Comment by ReikaKalseki** [comment]
Vanilla researches *are* ammo-based.

**Comment by EchelonRed** [comment]
Well yes, you are correct, they do benefit from ammo research but there is a separate turret damage research that compounds with the ammo bonus. The laser turrets are a bit different iirc. This vanilla gun-turret specific research does reference the turret names. Upon further pecking through code, this does not appear to be handled for the vanilla turrets through EndgameCombat. This turret damage bonus is lost as soon as the first level of increased range is researched. I ended up doing this but it is ridiculous and messy on the research screen:
https://pastebin.com/CHr0xxBr

I think the biggest issue that could arise with this would be, say a player is at a point in the game where they are barley holding back some of the more armored biters with a respectable 120%-160%, bonus to their turret damage on top of the ammo damage bonus. The player decides to install this mod as the biters are slowly wearing down their defenses and they have had enough of their bs. They research increased range level 1. All of the sudden, their turrets are replaced and now doing half of the damage that they previously were, and the biters overwhelm them. An unlikely scenario, I know. Plus they should have just switched to laser turrets anyway lol. 

 Sorry to be a nuisance about this. If anything I suppose this is more of a "just so you are aware" sort of thing as an all encompassing, more elegant, solution would be a lot of work. I would help more if I could.

**Comment by ReikaKalseki** [comment]
I suppose I should just go and implement the slow-but-probably-functional idea above.

**Comment by ReikaKalseki** [comment]
OK, this looks like it should work:

	for _,tech in pairs(data.raw.technology) do
		if tech.effects then
			local effectsToAdd = {}
			for _,effect in pairs(tech.effects) do
				if effect.type == "turret-attack" and effect.turret_id then
					local base = data.raw["ammo-turret"][effect.turret_id]
					if not base then
						base = data.raw["fluid-turret"][effect.turret_id]
					end
					if not base then
						base = data.raw["electric-turret"][effect.turret_id]
					end
					if not base then error("Tech set to boost turret '" .. effect.turret_id .. "', which does not exist?!") end
					if shouldCreateRangeTurret(base) then
						for i=1,10 do
							table.insert(effectsToAdd, {type="turret-attack", turret_id=base.name .. "-rangeboost-" .. i})
						end
					end
				end
			end
			for _,effect in pairs(effectsToAdd) do
				table.insert(tech.effects, effect)
			end
		end
	end
