### ISSUE TITLE
Suggestions for Geothermal 

### ISSUE THREAD

**Issue by Arcitos** [ReikaKalseki/Reika_FactorioMods_Issues#4]
Hi Reika, i really appreciate your geothermal mod. Here just a few questions/suggestions:

I noticed that the output of geothermal wells is limited to three units per second - this feels a bit odd, given that oil wells produce at least 10 units. Would it be possible to increase this amount? A bigger amount of geothermal heated water would also make shipping it per rail tanker much more interesting. 

Another thing is the crafting speed of the heat exchangers. They're so fast that the crafting sound is compressed to some kind of annoying crackling. Would it be possible to increase input requirements and output amounts in order to lenghten the crafting time? For instance by a factor of 5?

**Comment by hasezoey** [comment]
to the first thing: an option to change it in the configs ingame?

**Comment by ReikaKalseki** [comment]
> I noticed that the output of geothermal wells is limited to three units per second - this feels a bit odd, given that oil wells produce at least 10 units. Would it be possible to increase this amount? A bigger amount of geothermal heated water would also make shipping it per rail tanker much more interesting.

If I increase it, it will start depleting, and I would rather not change the overall balance regarding the well/exchanger/turbine ratio.

> They're so fast that the crafting sound is compressed to some kind of annoying crackling.

Not for me. It sounds like bubbling. Is it starting and stopping continuously?

**Comment by Arcitos** [comment]
> > I noticed that the output of geothermal wells is limited to three units per second - this feels a bit odd, given that oil wells produce at least 10 units. Would it be possible to increase this amount? A bigger amount of geothermal heated water would also make shipping it per rail tanker much more interesting.
> 
> If I increase it, it will start depleting, and I would rather not change the overall balance regarding the well/exchanger/turbine ratio.

Oh, i wasn't aware that changing the output will make geothermal heated water a depleatable resource. 

> > They're so fast that the crafting sound is compressed to some kind of annoying crackling.> 
> Not for me. It sounds like bubbling. Is it starting and stopping continuously?

The exchanger i heard was apparently not running on full capacity but only ~ 80%. After my steam turbines increased their demand the crackling was not audible any more. On heat exchangers not working on full capacity, the effect i mentioned seem to be created by small pauses between crafting of steam.

**Comment by ReikaKalseki** [comment]
> The exchanger i heard was apparently not running on full capacity but only ~ 80%. After my steam turbines increased their demand the crackling was not audible any more. On heat exchangers not working on full capacity, the effect i mentioned seem to be created by small pauses between crafting of steam.

So, yes, it was. I can do nothing about that.
