### ISSUE TITLE
Hi, Nauvis Day mod conflict on Custom biter

### ISSUE THREAD

**Issue by GimoXagros** [ReikaKalseki/Reika_FactorioMods_Issues#40]
Nauvis Day mod conflict on Custom biter.

If the biter breaks func, the game is crush.

Error while running event NauvisDay::on_tick (ID 0)
LuaEntity API call when LuaEntity was invalid.
stack traceback:
	__NauvisDay__/fans.lua:33: in function 'func'
	__NauvisDay__/control.lua:111: in function <__NauvisDay__/control.lua:84>

![00000](https://user-images.githubusercontent.com/30635204/30777751-1a6b8d4c-a0fd-11e7-91ea-3648b9609e90.JPG)

**Comment by ReikaKalseki** [comment]
This error does not look to have to do anything with biters, but instead the pollution fans.

**Comment by GimoXagros** [comment]
I hope this error is fixed. Please tell me if there is anything I can help you with. :)

**Comment by ReikaKalseki** [comment]
What triggered the crash?

**Comment by GimoXagros** [comment]
Probably it seems to be an issue with AAI or NE.

**Comment by ReikaKalseki** [comment]
That is not what I asked. What happened right before the crash?

**Comment by GimoXagros** [comment]
It happens just randomly when the fan is operating and the pollution value is nil.

**Comment by ReikaKalseki** [comment]
...This looks like the fan entity being nil, not pollution (which is an integer and should never be null).

**Comment by ReikaKalseki** [comment]
#57
