### ISSUE TITLE
`You cannot key a null itemstack!` caused by mod/item removal

### ISSUE THREAD

**Issue by cleverca22** [ReikaKalseki/Reika_FactorioMods_Issues#41]
https://gist.github.com/cleverca22/540b0d952916453aaab1ff7599f1042f

i believe the problem, is that an item from a deleted mod is in the whitelist of my inventory warp (the ItemInventoryLinker), and every time i pick up an item, the server kicks me due to the exception

**Comment by ReikaKalseki** [comment]
Wrong tracker.
