### ISSUE TITLE
What does your modpack look like?

### ISSUE THREAD

**Issue by Baughn** [ReikaKalseki/Reika_FactorioMods_Issues#42]
I'm tempted to start another Factorio game, and from experience I'm pretty sure including your mods will be fun, but they don't cover the entire range.

So I'm curious. What does your game look like?

If you don't want to spend time describing, I'll be happy with just the json mod list.

**Comment by ReikaKalseki** [comment]
I change my pack every time, but here was my last modlist:

https://pastebin.com/PMcn2Ypj
