### ISSUE TITLE
Can't disable auto-deconstruct loot.

### ISSUE THREAD

**Issue by teckton** [ReikaKalseki/Reika_FactorioMods_Issues#43]
I've tried nearly everything. The settings apply when I change them, but they don't take affect. I've unchecked the button, snooped around with other mods I'm using to see if it's a compatibility issue, and I've looked everywhere in the config files and disabled the settings from there, and the auto-deconstruct still takes place.
It's very annoying, and I can't even use personal roboports out in the open because robots will pick tissue up randomly. I'm always having to wait for my robots, and I tend to lose tons of them because they randomly fly right into enemy fire trying to get a single alien tissue, or occasionally I might leave without my robots and they'll randomly come into view, slowly flying towards me hours later.
I don't really even need or want this feature, since I already have mods that do this job better. It acts as more of an annoyance rather than a helping tool.
I just can't disable it. It doesn't work, and I believe I'm on the latest update for this mod.

**Comment by ReikaKalseki** [comment]
The option is not doing anything? Try setting the timer to some very large value as a fallback.

**Comment by teckton** [comment]
Just tested that. Doesn't work either for some reason. I don't think the mod options work for me, even for some other mods. It's like the changes I make don't do anything in the config, only visually to the mod settings window. I found a temporary workaround, using equipment hotkeys to disable the personal roboports by control without removing them from the grid. If the settings are working for everyone but not for me, then it's probably a minor compatibility issue with some other mod that I have, so I'll do some testing to see if I can dig out the issue.

**Comment by ReikaKalseki** [comment]
And I can confirm the settings work for me.

**Comment by ayeso** [comment]
Im also not able to change the settings. Everytime I change it and click apply, the factorio doesnt reload the option. I hit apply and it takes me back to the game. No matter what I do I cannot get it to disable deconstructing. If I change the config.lua same thing, doesnt apply.

**Comment by ReikaKalseki** [comment]
...Even changing the actual mod code has no effect?! Are you sure you are editing the right files (eg in case of multiple modpack instances)?
