### ISSUE TITLE
[Request] Angel ores configuration

### ISSUE THREAD

**Issue by Baughn** [ReikaKalseki/Reika_FactorioMods_Issues#45]
Inside the config.lua for Oreverhaul, you comment that it's pointless to combine the mod with Angel's, seeing as they have different principles for creating ore tiering.

This is true, so long as advanced ores exist, but Angel's has a lesser-known configuration where if none of its optional dependencies exist it'll stick to spawning Saphirite and Stiratite, both of which are mixtures of copper and iron.

Editing config.lua to swap out iron/copper spawns for those was easy enough, but it'd be nice if it happened by default. Angel's Refining is entirely useless without them, after all.

(In my particular configuration, I left iron and copper on for the spawn zone and had Oreverhaul generate saphirite/stiratite further out. It's been fun... but I won't ask you to support *that* config.)

**Comment by ReikaKalseki** [comment]
> Editing config.lua to swap out iron/copper spawns for those was easy enough

That is what config files are *for*. Just add or remove the desired ores. I am not going to make a bunch of different configs for different desired game states.

**Comment by Baughn** [comment]
The problem with factorio's config files is they're overwritten when the mod updates. But w/e.

**Comment by ReikaKalseki** [comment]
If you autoupdate it, yes, but you can back them up first. But there is currently no reasonable alternative.
