### ISSUE TITLE
Repository pinning

### ISSUE THREAD

**Issue by Baughn** [ReikaKalseki/Reika_FactorioMods_Issues#47]
It'd be helpful if your two -issues repositories were pinned to https://github.com/ReikaKalseki, so they show up on the list there. Right now only the source code repos (which don't have issues enabled) are pinned.

**Comment by ReikaKalseki** [comment]
There is a limit to six or eight pinnable repositories; I picked the most important.

**Comment by Baughn** [comment]
Right, precisely. I'd argue that the 'issues' repositories are the two most important.

In the end it's your choice, I guess.
