### ISSUE TITLE
Is the Tier-3 power armor meant to have no fire resistance?

### ISSUE THREAD

**Issue by zebediah49** [ReikaKalseki/Reika_FactorioMods_Issues#48]
The vanilla armors (as of 0.15) have fire resistances of:

* Light: 10%
* Heavy: 30%
* Modular: 40%
* Power I: 60%
* Power II: 70%

While Power 3 has nothing for fire.  Is dropping that fire resistance entry an intentional balance choice, a modding limitation, or an oversight (the armor looks vaguely unfinished)?

**Comment by ReikaKalseki** [comment]
This is an oversight; was the fire resistance added recently?

**Comment by ReikaKalseki** [comment]
Done.,
