### ISSUE TITLE
(NauvisDay) Error in assingID

### ISSUE THREAD

**Issue by hypraman** [ReikaKalseki/Reika_FactorioMods_Issues#49]
here is my story:
(world was already created/generated)
-Feels like pollution is not punishing me enough, I download the mod directly from the 'mods' tab within the game main menu
-**It loads all okay**, immediately getting an invasion from a nearby monster camp due to pollution (get achievement), finally some action yay!
-Starts looking at the new recipes... but can't find the steam-powered furnace. I do have the tech for it... but i admit i already had it BEFORE installing the mod.
-I verify the option is checked to enable, It is on by default, so I simply restart the game... but the recipe simply never appears, probably because I already had the tech? I don't know
-Decides trying a 'full refresh' by turning off the setting, restart the game, then turn them back on, then restarting again.
-Turns off the setting, restarts... crash

>Error loading mods
Failed to load mods: Error in assignID, recipe-category with name 'steam-smelting' does not exist.
Source: copper-plate-steam (recipe).

-Disable the mod so the game loads, delete it from the 'list'( the only other mod being "Pollution Control"), restart the game, and reinstall the mod... but gives the same error... even tho' **it was loading** that 1st time. I guess the options saved?

End of story: can't load the mod anymore.

**Comment by ReikaKalseki** [comment]
Did you have another mod adding steam smelting? NauvisDay (optionally) adds that and it is possible there is a conflict.

And yes, options are saved in a file; you can edit that if you wish.

**Comment by hypraman** [comment]
Like i said, the ONLY other mod i had installed is called "pollution control", simply showing me the global pollution.
I bought the game fresh on steam last Saturday, so it is very likely to be up to date.
I even went as far as trying to put my language in english (since I usually play in french)... but nothing worked... i don't know what to do anymore.
Again, it loaded fine the very 1st time I installed the mod... but now it's no longer working...

I'm also not sure where is that option file.

**Comment by ReikaKalseki** [comment]
Your options file is in the same folder as your mods are, but I do not offhand know where that is for a steam installation.

**Comment by hypraman** [comment]
Found it in AppData/Roaming/Factorio/mods, nowhere near where I originally installed the game, took me some time to find.
Managed to enable back the settings for both the gas-boiler and the steam furnace.
This make the game (and the mod) loadable again without errors... but again, the recipes are nowhere to be seen. I see the greenhouse and the water-to-wood recipe in the inventory GUI... but nothing else is new. ( I don't have all the techs tho' ) 
Pollution factors and tweaks works as intended tho', i guess.

**Comment by ReikaKalseki** [comment]
If you are willing to run commands, try the following:

/c game.player.force.reset_technologies()
/c game.player.force.reset_recipes()
/c game.player.force.reset_technology_effects()

**Comment by hypraman** [comment]
Yup, Now i can see both recipes. No idea which one of the 3 command did the trick tho'
But now the completionist that I am is achievement-less X3

**Comment by ReikaKalseki** [comment]
You could have installed FTweaks to get the same effect.
