### ISSUE TITLE
[Endgame Combat] Often Replaceing / is Replaceing / is Replaceable

### ISSUE THREAD

**Issue by hasezoey** [ReikaKalseki/Reika_FactorioMods_Issues#5]
Item: Plasma Turret

Main: it is replaceable with the same type what is placed, what makes when it is placed, it makes it replace

- "Graphical Bug / Glitch"
- not Important
- no Item Duplicating / Loosing

Reproduce:
get (at least) 2 Plasma Turrets place one and "hold" sometimes it is replaceing it when another is set and it is still replaceable with exactly the same item

**Comment by ReikaKalseki** [comment]
That is because it is replacing the range-boosted version with the basic one (which becomes the range boosted one when placed). This cannot be fixed unless the modding API adds the ability to modify turret ranges directly.

**Comment by hasezoey** [comment]
Oh, ok, thanks for the Info ^^
