### ISSUE TITLE
Nauvis Day: Game crashes while using pollution well on borehole

### ISSUE THREAD

**Issue by chris-tier** [ReikaKalseki/Reika_FactorioMods_Issues#51]
After boring a hole with the drill there is a borehole on which a pollution well can be placed. After connecting the well to pipes containing polluted sludge, the sludge is being pumped into the well but soon after the game crashes showing this ![crash message](https://user-images.githubusercontent.com/35078436/34537931-a55121ca-f0ca-11e7-81de-28e43aedb342.png).

[factorio-current.log](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/1601570/factorio-current.log)

**Comment by ReikaKalseki** [comment]
Fixed.
