### ISSUE TITLE
productivity

### ISSUE THREAD

**Issue by judos** [ReikaKalseki/Reika_FactorioMods_Issues#53]
Is it intentional that I can put beacon tier5 into accelerated beacons II and get +600% productivity on recipes which usually don't even allow any productivity bonus? :)

**Comment by ReikaKalseki** [comment]
....Did you read any of the settings?

**Comment by judos** [comment]
did you mean this option? I have it disabled...
![grafik](https://user-images.githubusercontent.com/5525810/34587895-8cffa1ba-f1aa-11e7-82f7-be50eff1f28a.png)

**Comment by ReikaKalseki** [comment]
Yes, that is the setting. *That* is not supposed to be possible. And should be fixed.

**Comment by judos** [comment]
cool thanks 👍
