### ISSUE TITLE
Cannot create new game in multiplayer headless

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_FactorioMods_Issues#54]
When game is created on headless server, i got this error : 

  27.129 Error MainLoop.cpp:1013: Exception at tick 0: Error while running event EndgameCombat::on_tick (ID 0)
__EndgameCombat__/control.lua:388: bad argument #2 to 'random' (interval is empty)
  27.129 Error ServerMultiplayerManager.cpp:95: MultiplayerManager failed: "Error while running event EndgameCombat::on_tick (ID 0)
__EndgameCombat__/control.lua:388: bad argument #2 to 'random' (interval is empty)"

If I do those steps, it works : 
1/ Create the game on headless without the mod 
2/ Connect once to the game server from a client 
3/ Stop the server
4/ Install the mod
5/ Restart the server

My guess is that at the game creation moment on headless, there is something trying to run on a non-existing (yet) player.

**Comment by ReikaKalseki** [comment]
It was not init code, but once-a-second code that was never built with MP in mind. Fixed.
