### ISSUE TITLE
Gas boiler gas pipe connectivity placement order dependent in 0.16

### ISSUE THREAD

**Issue by Baughn** [ReikaKalseki/Reika_FactorioMods_Issues#55]
As you can (not quite) see in http://i.imgur.com/IhUWL1g.png, it's not taking any fuel. It's supposed to use petroleum gas, right?

I'm noticing overlapping icons on the lower side. Wonder if that's related...

This is on 0.16.16. I was going to try it on .17, but then I discovered that .17 has a link error and crashes on startup. :3

**Comment by Baughn** [comment]
I don't see an obvious reason, but it works on .18 now so... *shrug*.

**Comment by Baughn** [comment]
Okay, it's a little more complicated.

The gas boiler doesn't work when placed (on .18), but does work after a save or reload, as you can see here: https://i.imgur.com/sRLjNL4.jpg

The bottom-left two boilers were placed prior to saving. After another save and reload (and power connection), all six work fine.

**Comment by ReikaKalseki** [comment]
Very very odd.... Does direction influence anything? What about pipe/boiler placement order?

**Comment by Baughn** [comment]
Direction of placement appears to be irrelevant, but placing the pipe before the boiler does make it work.

**Comment by ReikaKalseki** [comment]
I noticed something like this when I was testing my 0.16 update, though it was not reliable. I tried calling the manual update_connections() functions, but they had no effect.

**Comment by ReikaKalseki** [comment]
Is this still a thing in 0.17?

**Comment by Baughn** [comment]
No idea. We don't play 1.7-based packs anymore.

EDIT: ...d'oh, this isn't Minecraft. Still no idea; that playthrough died a *loong* time ago, and I haven't tried your factorio mods recently.

**Comment by ReikaKalseki** [comment]
The change I just made, converting the steam furnaces and gas boilers to fluid power source, fixes this.
