### ISSUE TITLE
Error loading game, unknown layer name

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_FactorioMods_Issues#56]
0.16.20, single client, no other mods : 

![image](https://user-images.githubusercontent.com/34961300/35470474-6f02d162-034a-11e8-80c6-76ad62b901b7.png)

Was working previously in 0.16.16, not sure exactly which release broke it.

**Comment by ghost** [comment]
https://forums.factorio.com/viewtopic.php?f=3&t=57181
Dev changed names in 0.16.20.

**Comment by ReikaKalseki** [comment]
I know; this will be fixed in the next update.
