### ISSUE TITLE
[NauvisDay] Crash in fans.lua

### ISSUE THREAD

**Issue by Baughn** [ReikaKalseki/Reika_FactorioMods_Issues#57]
I'm not sure what to do with this one, but hopefully you do. The game outright crashed -- that is, it paused while showing an error, and then returned to the main menu.

```
 170.969 Error MainLoop.cpp:1016: Exception at tick 3356760: Error while running event NauvisDay::on_tick (ID 0)
LuaEntity API call when LuaEntity was invalid.
stack traceback:
	__NauvisDay__/fans.lua:32: in function 'func'
	__NauvisDay__/control.lua:111: in function <__NauvisDay__/control.lua:84>
```

It may have been caused by adding FTweaks (somehow), or possibly it's been lying under the surface in .20; this is the first time I've run the world for more than half a minute, as I'm waiting for an EndgameCombat update.

The problem wasn't there in .18, which is the last time I played this world for more than a minute. I've left the game running now *without* FTweaks, so I'll be able to tell you whether that mattered in a few hours.

(By which time my base will be destroyed, because all the turrets disappeared due to a missing EndgameCombat. No worries though, it's just an alien invasion destroying all mankind holds dear... :P)

**Comment by Baughn** [comment]
Naruto-style ninja edit: Nope. It's not FTweaks, this happened again almost instantly and before I managed to leave the house.

**Comment by ReikaKalseki** [comment]
This should not have happened; a technical entity was either deleted or never created, neither of which should be possible. Does it happen reliably?

**Comment by Baughn** [comment]
It happened repeatedly. As for "reliably", well, I can't check right now. I'll report back after the FTweaks bug is fixed.

**Comment by Baughn** [comment]
I don't believe I'll be able to test this, at least not for a while. Something happened, and I became unable to continue... ahem: https://imgur.com/a/ntA28

But for the few minutes until power crashed completely, the fans worked. It's possible that something in the upgrade process broke them earlier.
