### ISSUE TITLE
[Dirty Mining] Recepies in Assembler

### ISSUE THREAD

**Issue by hasezoey** [ReikaKalseki/Reika_FactorioMods_Issues#6]
The Recepies from the 'Ore Washing Plant' are able to set in an Assembling machine

**Comment by ReikaKalseki** [comment]
This is intentional.

**Comment by hasezoey** [comment]
really? i saw other mods using it, and the recepies were only able to craft them in the maschine for it ...

**Comment by ReikaKalseki** [comment]
What other mods choose to do is neither my concern nor any metric of how things should be.

**Comment by hasezoey** [comment]
okey.
