### ISSUE TITLE
Error Loading Recipe with Bob's Power

### ISSUE THREAD

**Issue by JakeRoxs** [ReikaKalseki/Reika_FactorioMods_Issues#60]
"You get a recipe prototype crash if FTweaks loads alongside bob's power, and harder silo is false.

"failed to load mods: Error while loading recipe prototype "large-accumulator-satellite" recipe): Difficulty normal: key "ingredients" not found in property tree at ROOT.recipe.large-accumulator-satellite 
Modifications: FTWeaks"

reference lines 33,34,35 and following code of bridge.lua."
https://mods.factorio.com/mod/FTweaks/discussion/5a77045547619e000bbc3e8b

**Comment by ReikaKalseki** [comment]
Hopefully fixed.
