### ISSUE TITLE
Endgame Combat: Tissue marked for deconstruction even when option is disabled

### ISSUE THREAD

**Issue by gctypo** [ReikaKalseki/Reika_FactorioMods_Issues#61]
Alien Tissue is always marked for deconstruction, even when the option "Mark alien drops for deconstruction" is unchecked. This causes bots to go out and pick it up in the middle of combat when a personal roboport is installed in the player's armor, which often gets the bots destroyed.

Current workaround is setting the "Alien drop deconstruction delay" to something extremely high, but this very quickly causes a massive performance hit from all the tissue on the ground. Perhaps if there was a config option to disable Alien Tissue altogether there wouldn't be as many problems.

This bug was reported on the mod portal [here](https://mods.factorio.com/mod/EndgameCombat/discussion/5a5f1b0dadcc441024d76eac) and [here](https://mods.factorio.com/mod/EndgameCombat/discussion/5a5f1b0dadcc441024d76fe5) with no dev response. I didn't see it reported here.

**Comment by ReikaKalseki** [comment]
Someone mentioned this to me in the past, but I was not able to reproduce it. They never replied back.

**Comment by ReikaKalseki** [comment]
Go to #43
