### ISSUE TITLE
[NauvisDay] Crash in pollutionfx.lua

### ISSUE THREAD

**Issue by Baughn** [ReikaKalseki/Reika_FactorioMods_Issues#62]
```
 200.344 Error MainLoop.cpp:1019: Exception at tick 658620: Error while running event NauvisDay::on_tick (ID 0)
__NauvisDay__/pollutionfx.lua:37: attempt to index field 'character' (a nil value)
```

This isn't caused by any player action. It happens even if we're standing still.

**Comment by Baughn** [comment]
...and I'm pretty sure it's due to being in multiplayer after a player has logged off.

**Comment by Baughn** [comment]
Seems like. Also, wrapping it with a nil check makes everything work fine. That's probably the right thing to do anyway.

**Comment by ReikaKalseki** [comment]
Fixed.
