### ISSUE TITLE
[NauvisDay] 0.16.24 Fluix box fix-related cleanup

### ISSUE THREAD

**Issue by Baughn** [ReikaKalseki/Reika_FactorioMods_Issues#63]
Context: https://forums.factorio.com/viewtopic.php?t=57753

```
Error while loading entity prototype "polluted-offshore-pump" (offshore-pump): Fluidbox base area must be greater than 0.

At ROOT.offshore-pump.polluted-offshore-pump.fluid_box
Modifications: Nauvis Day
```

The device may not be supposed to be functional, but the fluidbox area still needs to be greater than 0.

**Comment by ReikaKalseki** [comment]
This used to work....

But OK, this is fixed for the next version.
