### ISSUE TITLE
[NauvisDay] LuaEntity API call when LuaEntity was invalid

### ISSUE THREAD

**Issue by Baughn** [ReikaKalseki/Reika_FactorioMods_Issues#64]
Second one of these. At this point it looks like a pattern.

```
6238.790 Error MainLoop.cpp:1019: Exception at tick 6777480: Error while running event NauvisDay::on_tick (ID 0)
LuaEntity API call when LuaEntity was invalid.
stack traceback:
	__NauvisDay__/pollutionfx.lua:16: in function 'tickSpill'
	__NauvisDay__/pollutionfx.lua:50: in function 'tickSpilledFluids'
	__NauvisDay__/control.lua:115: in function <__NauvisDay__/control.lua:88>
```

Possible cause: The biters were breaking pipes, but they'd broken quite a few before this happened.

**Comment by Baughn** [comment]
Here's a savegame which crashes instantly: https://brage.info/factorio/crash.tar.xz

All mods included, so it's a little large.

**Comment by Baughn** [comment]
The bug still happens with every mod but Nauvis Day removed.

**Comment by Baughn** [comment]
And here's a fix:
```
function tickSpilledFluids(nvday, doText)
   for _,entry in pairs(nvday.spills) do
      if entry.entity.valid then
         tickSpill(entry, nvday, doText, false)
      else
         nvday.spills[entry.key] = nil
      end
   end
end
```

Presumably, it was destroyed by a different mod. Given what it's for, you might want to respond by recreating it, but this removes the crash. Going by the documentation, you need to check validity on every ingame entity which you've also kept a reference to in some table.

I wonder if the biters decided to attack a spill? Or maybe it got run over by a train? Hard to say, really.

**Comment by ReikaKalseki** [comment]
I have no idea why a spill would be randomly deleted; the entity type and flags they have make them immune to damage and targeting, meaning the only way for them to be deleted is explicit script code.

**Comment by Baughn** [comment]
This also bit us a lot with logistics turrets. Every use of entry.logistic also needs to check entry.logistic.valid, it seems.

Oh, and the logistics turrets are difficult to use in blueprints, because the 'chest' doesn't rotate if the turrets do. Can that be fixed?

**Comment by ReikaKalseki** [comment]
> Oh, and the logistics turrets are difficult to use in blueprints, because the 'chest' doesn't rotate if the turrets do. Can that be fixed?

Elaborate?

> This also bit us a lot with logistics turrets. Every use of entry.logistic also needs to check entry.logistic.valid, it seems.

The thing is, in cases where it is not valid yet I have no check in place, that is because it never *should* be invalid. The fact it is invalid is actually an indicator of some other error.

**Comment by Baughn** [comment]
The logistics chest you add doesn't seem to work as a target for inserters.

So, imagine you have a blueprint with belt, inserters, turrets and wall--the works. This would still be valuable after getting logistics turrets, in part because bots get killed too easily on an active wall, and in part because the default request is far too high when you need hundreds of turrets.

If you rotate such a blueprint, then for one of the possible rotations the inserters will be inserting into the logistics chest. Which doesn't work.

**Comment by ReikaKalseki** [comment]
> The logistics chest you add doesn't seem to work as a target for inserters.

It is an ordinary logistic chest...I would not know how to disable inserter input if I wanted to.

But you are basically saying that the no matter the original turret orientation, the logi chest is always at the lower right corner?

That is true, but it is because A) it is otherwise inaccessible (it overlaps with one of the four tiles used by the turret, after all (and this might be why inserters cannot access it)) and B) the original rotation of a turret is largely irrelevant.

**Comment by Baughn** [comment]
All right. For now they're causing more trouble than they're worth, so I'm going to undo the research.

The real issue is biters, and I don't see any way to make logistics bots safe while the base is under attack other than keeping them away from the walls.

**Comment by ReikaKalseki** [comment]
This has not been reported in months, so is probably fixed.
