### ISSUE TITLE
Suggestion on a new building

### ISSUE THREAD

**Issue by Luf2K14** [ReikaKalseki/Reika_FactorioMods_Issues#65]
Hi!
i dunno if you still working on your project but its awesome and i would like to see a new upgraded Centrifuge because the ratio of uranium 235 and 238 it is way to unbalanced from vannila and i wanted in the next update to have a better ratio like 50/50 so i can build an efficient uranium weapons or uranium fuel to the reactor without having to build a huge factory (and the kovarex proccess is way to much to config to be efficiently)

thanks in advance ...

**Comment by Luf2K14** [comment]
oh nevermind i found another mod that allows to make only uranium-235/uranium-238 but i wouldnt mind to have it anyways

**Comment by ReikaKalseki** [comment]
> the ratio of uranium 235 and 238 it is way to unbalanced from vannila

It is the *realistic* ratio, and was chosen for a reason.
