### ISSUE TITLE
Geothermal well acting as signal

### ISSUE THREAD

**Issue by WhiskeyWonka** [ReikaKalseki/Reika_FactorioMods_Issues#66]
As you can see the well on the left side is acting as a signal on the rail. If I build a rail spur over it, it stops. 
This only happens when the rail is running north south and the well is on the left hand side.

https://imgur.com/a/tmAnLqE
https://imgur.com/a/m4VFUT0

**Comment by ReikaKalseki** [comment]
This is not a *bug* per se; the glow for the well is done with an invisible rail signal (one of the only entity types that can glow).

**Comment by WhiskeyWonka** [comment]
Ah I had no idea that was how you did the glow. Thank you for your response. I am liking the mod very much.

**Comment by ReikaKalseki** [comment]
> I am liking the mod very much. 

:)

**Comment by ReikaKalseki** [comment]
I just had an idea regarding a possible fix:

https://forums.factorio.com/viewtopic.php?f=6&t=60042
