### ISSUE TITLE
[Endgame Combat] Incompatibility with mexmer's science cost tweaker mod.

### ISSUE THREAD

**Issue by Sacro** [ReikaKalseki/Reika_FactorioMods_Issues#67]
`Error ModManager.cpp:1024: Failed to load mod "EndgameCombat": __EndgameCombat__/data-updates.lua:8: __EndgameCombat__/prototypes/item/compound-ammo.lua:72: Tech set to unlock recipe 'sct-lab-3', which does not exist?!`

Also raised on his side - https://github.com/mexmer/ScienceCostTweakerM/issues/2

**Comment by mexmer** [comment]
just one note, there is same issue with omnimatter pack, you will need to contact emperorzelos to fix that
