### ISSUE TITLE
Bug with Alien Biomes

### ISSUE THREAD

**Issue by Unifire1** [ReikaKalseki/Reika_FactorioMods_Issues#69]
Hi Reika,

I noticed this error while exploring and revealing new chunks
This error exist while using the mod: Alien biomes 0.3.8 and without Alien biomes it works just fine
Tested with Geothermal version 1.0.72 and 1.0.80 same results
No others mods were running

84.687 Checksum for script __alien-biomes__/control.lua: 2144410014
  84.689 Checksum for script __Geothermal__/control.lua: 1379884703
 113.063 Error MainLoop.cpp:1035: Exception at tick 1261: Error while running event Geothermal::on_chunk_generated (ID 12)
LuaTile API call when LuaTile was invalid.
stack traceback:
	__Geothermal__/control.lua:97: in function
<__Geothermal__/control.lua:56>

**Comment by ReikaKalseki** [comment]
Fixed. It does not make sense, but it is fixed.
