### ISSUE TITLE
crash [NauvisDay]

### ISSUE THREAD

**Issue by Evilinex** [ReikaKalseki/Reika_FactorioMods_Issues#70]
https://i.imgur.com/knvXrpZ.png
if disable pollution don`t crash
if enable crash after 2-3 min after start  (not clean start)

how i can help with fix?

**Comment by ReikaKalseki** [comment]
This is with the newest version?

**Comment by Evilinex** [comment]
Factorio 16.51
Nauvis 1.0.80

**Comment by Evilinex** [comment]
tried to find what is problem and found crash was happened if greenhouse (Bob's greenhouse mod) close to pollution and have big pollution value

**Comment by ReikaKalseki** [comment]
I fixed *that* issue a *very* long time ago.

**Comment by Evilinex** [comment]
mb but trouble i have now :)
https://i.imgur.com/HUIQWIs.jpg
https://i.imgur.com/GTeuSuP.png
i can play only with this comments
https://i.imgur.com/UesBvjD.png

**Comment by ReikaKalseki** [comment]
Fixed.
