### ISSUE TITLE
[Endgame Combat]Crash on bot-deconstruct of turret with logistics chest. Repost

### ISSUE THREAD

**Issue by MankoMR** [ReikaKalseki/Reika_FactorioMods_Issues#71]
I posted this here since it is not possible to post/reply on the mod portal. The Bug was first reported by usafphoenix: https://mods.factorio.com/mod/EndgameCombat/discussion/5aa91c0b7bebc3000b8f3467.

I have the same problem as him:

Error while running event: EndgameCombat: on_robot_mined_entity(ID 64) LuaEntity API call when luaEntity was invalid. stack traceback: EndgameCombat/control.lua:108:in function 'removeTurretFromCache'
Endgamecombat/control.lua:525:in function<EndgameCombat/control.lua:509>

crash only occurs once technology research results in turrets having logistic chests, and entity is deconstructed by bots. they can be mined by hand without triggering error. And turrets can be mined by bots prior to researching turret logistics. Factorio Version: 16.30
Endgame Combat version: 1.0.72

**Comment by ReikaKalseki** [comment]
Fixed - the actual issue was the logistics chests getting marked for deconstruction and removed separately from the turret. These chests now cannot be marked for deconstruction.
