### ISSUE TITLE
[Endgame Combat]Wave Defense will not launch now

### ISSUE THREAD

**Issue by bear2312** [ReikaKalseki/Reika_FactorioMods_Issues#72]
Could you please fix what you've changed in the latest EndgameCombat update.  Wave Defense will no longer launch.  Instead the game give this notice.
Error while running on_init:Unknown interface:
silo_script
stack traceback:
[]__EndgameCombat__control.lua.52:in
function'initGlobal'
[]__EndgameCombat__control.lua.76:in
function<__EndgameCombat__/control.lua:75>

**Comment by ReikaKalseki** [comment]
Fixed.
