### ISSUE TITLE
Dirty Mining conflict(s)

### ISSUE THREAD

**Issue by EPSIL0N** [ReikaKalseki/Reika_FactorioMods_Issues#78]
Bob's Metal Chemicals and Intermediate
Bob's Power
Rampant Arsenal

Any of them being enabled with dirty mining causes this error
Mods to disable:Failed to load mods: Error while loading item prototype "dirty-ore-coal" (item): Must have a fuel_value when fuel_acceleration_multiplier, fuel_top_speed_multiplier, fuel_emissions_multiplier, or fuel_glow_color are used.
Modifications: DirtyMining

**Comment by ReikaKalseki** [comment]
Already fixed.
