### ISSUE TITLE
NauvisDay mod conflicts

### ISSUE THREAD

**Issue by EPSIL0N** [ReikaKalseki/Reika_FactorioMods_Issues#79]
With Natural Evolution Enemies getting 
Mods to disable:Failed to load mods: __NauvisDay__/data-updates.lua:115: attempt to perform arithmetic on field 'emissions_per_tick' (a nil value)

NEE 9.0.4

With the combination of Bio Industry, Bob's Green House, NauvisDay and then enabling More Bobs
Mods to disable:Failed to load mods: The given sprite position (left_top = 0x101) is completely outside the actual sprite image (size=113x91).
Sprite name: __NauvisDay__/graphics/entity/treefarm/dead-greenhouse-active.png

**Comment by EPSIL0N** [comment]
I couldn't figure the second one out but I did notice that morebobs is different than ND and BGH as the icon is 113x101 rather than 113x91

**Comment by ReikaKalseki** [comment]
I fixed both, though the second perhaps will now lead to a graphics quirk when a greenhouse is killed by pollution.
