### ISSUE TITLE
Dirty Mining Ore Generation

### ISSUE THREAD

**Issue by LarkinOmega** [ReikaKalseki/Reika_FactorioMods_Issues#8]
Dirty Ores are generated through use of Pretty Fair Resources, and according to that Mod Author, are generated n Vanilla.

https://forums.factorio.com/viewtopic.php?f=94&t=51656&p=301826#p301826

If that is intended, could we get an option to disable generation?

**Comment by ReikaKalseki** [comment]
I do not generate dirty ores; That is not how the mod works. If someone else is generating them, that is not my problem.

**Comment by LarkinOmega** [comment]
![dirty ore generation](https://user-images.githubusercontent.com/30882621/29197399-b4903e74-7e00-11e7-8f42-77a0d92bcf86.png)
You do generate Dirty Ores. Brand New map, Dirty Mining and AutoChart installed. AutoChart only reveals the map.

**Comment by ReikaKalseki** [comment]
It is not happening for me. I have an idea on a last attempt at "enforcement", and have implemented it for the next version.
