### ISSUE TITLE
Is this a fail safe?

### ISSUE THREAD

**Issue by Silvernova115** [ReikaKalseki/Reika_FactorioMods_Issues#82]
33.779 Loading mod bobenemies 0.16.0 (data-updates.lua)
  34.237 Loading mod bobinserters 0.16.8 (data-updates.lua)
  34.679 Loading mod ElectricTrain 0.16.5 (data-updates.lua)
  35.126 Loading mod EndgameCombat 1.0.101 (data-updates.lua)
  35.274 Error ModManager.cpp:1024: Failed to load mod "EndgameCombat": __EndgameCombat__/data-updates.lua:8: __EndgameCombat__/prototypes/item/compound-ammo.lua:72: Tech set to unlock recipe 'filtration-unit-3', which does not exist?!
  35.277 Loading mod core 0.0.0 (data.lua)
  35.422 Checksum for core: 2304860305
  35.442 Error ModManager.cpp:1024: Error in assignID, recipe-category with name 'crafting' does not exist.

Source: enemy-base (noise-layer).
  35.544 Loaded shader file D:/Steam Client/Steam/steamapps/common/Factorio/data/core/graphics/shaders/game.cso
  35.544 Loaded shader file D:/Steam Client/Steam/steamapps/common/Factorio/data/core/graphics/shaders/zoom-to-world.cso
  35.545 Loaded shader file D:/Steam Client/Steam/steamapps/common/Factorio/data/core/graphics/shaders/alpha-mask.cso
  35.578 Initial atlas bitmap size is 16384
  35.578 Created atlas bitmap 192x5 [none]
  35.578 Created atlas bitmap 132x24 [no-crop, trilinear-filtering, icon, light]
  35.745 Sprites loaded
  35.745 Convert atlas 132x24 to: trilinear-filtering 
  35.756 Custom inputs active: 0
  35.761 Factorio initialised
  35.762 Mods to disable:Failed to load mods: __EndgameCombat__/data-updates.lua:8: __EndgameCombat__/prototypes/item/compound-ammo.lua:72: Tech set to unlock recipe 'filtration-unit-3', which does not exist?!

this error has occured with another mod i could identify but now im lost. why does this code exist in compound-ammo.lua

**Comment by ReikaKalseki** [comment]
Exactly as it sounds. Whoever adds the requisite tech has marked it to unloack a nonexistent recipe. You can find out what tech by replacing line 72 of compound-ammo with this: `if not recipe then error("Tech " .. tech.name .. " set to unlock recipe '" .. effect.recipe .. "', which does not exist?! This is a bug in that mod!") end`

**Comment by Silvernova115** [comment]
why is this error showing when the mod engame combat is installed? and it doesnt show when its disabled. it really seems that this code is causing a crash error with with things that have nothing to do with endame itself

**Comment by Silvernova115** [comment]
deleting the entire section in your mod that creates this crash fixes the issue, so whats the point of it.

**Comment by ReikaKalseki** [comment]
EGCombat is validating the technology list as it parses it, as it reads and/or modifies some technologies (namely their recipe unlocks and turret damage boosts, if any). Invalid entries risk a crash later while the game is loaded, so it errors out early with something more clear.

Deleting the code that does this validation does *not* fix a crash. It is akin to ripping out the "Check Engine" light in your car. Sure, the problem goes away at first...until it comes back later, far worse, and more difficult to diagnose.

The correct solution here is for the other mod - whoever it is - to not add a technology that is marked to unlock a nonexistent recipe. Removing my checker does not help with that at all.

**Comment by Silvernova115** [comment]
Well part of me is at a loss then. It says theres problems with Angel's mods.

**Comment by ReikaKalseki** [comment]
Perhaps it is due to the modularity of his mods; tech from mod A may be unlocking a recipe from mod B.
