### ISSUE TITLE
(EndgameCombat)Error Loading Mods

### ISSUE THREAD

**Issue by bear2312** [ReikaKalseki/Reika_FactorioMods_Issues#83]
Just installed your latest update of EndgameCombat and game will not load.  Returning this Error loading mods;
Failed to load mods:Error in assignID, item with name 'electric-energy-accumulator' does not exist.

Source:lightning-turret(recipe).

Mods to be disabled:
-EndgameCombat

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by hasezoey** [comment]
Please update the Repo & Factorio mods too, thanks

**Comment by ReikaKalseki** [comment]
...What?

**Comment by hasezoey** [comment]
i mean [this](https://github.com/ReikaKalseki/EndgameCombat) and [this](https://mods.factorio.com/mod/EndgameCombat)
-> didnt found the fix

**Comment by ReikaKalseki** [comment]
I uploaded the fix to the mod portal. Why does the GitHub being updated immediately matter?

**Comment by hasezoey** [comment]
i thought it will be the first place where the new version will be (because the mods.factorio was not the updated version), and thanks for the fix

**Comment by bear2312** [comment]
Thanks for the quick fixes Reika.  You're always on top of these issues and I truly appreciate it!
