### ISSUE TITLE
Thaumaturgic Mech mod confliction

### ISSUE THREAD

**Issue by Silvernova115** [ReikaKalseki/Reika_FactorioMods_Issues#84]
191.319 Sprites loaded
 191.319 Convert atlas 132x24 to: trilinear-filtering 
 191.333 Custom inputs active: 0
 191.336 Factorio initialised
 191.340 Mods to disable:Failed to load mods: Error while loading recipe prototype "CW-pulse-laser-aspect-extraction" (recipe): Key "icon" not found in property tree at ROOT.recipe.CW-pulse-laser-aspect-extraction.icons[1]
Modifications: Thaumaturgic Machinations

this shows when endgame combat is running with it. i noted this to the other author too

**Comment by ReikaKalseki** [comment]
That is not my doing - it mentions nothing of mine. Also @DaMachinator / @Aivech - you might want to have a look at this.
