### ISSUE TITLE
attempts to unlock non existing recipe

### ISSUE THREAD

**Issue by KorGgenT** [ReikaKalseki/Reika_FactorioMods_Issues#85]
![image](https://user-images.githubusercontent.com/30208401/43775133-a529e5f8-9a19-11e8-9a5e-c0c5dd08d8d5.png)
[factorio-current.log](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/2266303/factorio-current.log)
I have roboports disabled in bob's settings. this may actually be the issue.

Also, when attempting to run it with only vanilla, i get this issue:
![image](https://user-images.githubusercontent.com/30208401/43780387-79f837f4-9a28-11e8-9273-d1299619109b.png)

**Comment by ReikaKalseki** [comment]
The first one is as described - a bug in BobMods; you can either attempt to fix it yourself, temporarily enable the roboports, wait for a fix from him, or edit EGCombat to remove the verification process (which carries its own risks of crashes later). The second is already reported #83.

**Comment by KorGgenT** [comment]
I'm sorry, but what it describes is a bug in your mod. The only fix I would suggest is to check if the item exists before assigning it to a tech.

**Comment by ReikaKalseki** [comment]
I am not the one assigning the nonexistent item to the tech - *he is*. I am the one detecting that error.

**Comment by ReikaKalseki** [comment]
That said, I have added an ability to more simply disable the error, but with a warning that this is asking for a crash later.

**Comment by KorGgenT** [comment]
that seems fine. I have attempted to let bob know about this on his mod page.
