### ISSUE TITLE
[Factor-I-O] Crash when destroying a connected enegery Pole

### ISSUE THREAD

**Issue by hasezoey** [ReikaKalseki/Reika_FactorioMods_Issues#86]
When Destroying a Energy Pole (That is the only one that is connected to this side) it crashes with
![](https://i.imgur.com/JcI4llm.png)

![](https://i.imgur.com/Lc7DBJk.jpg)

**Comment by ReikaKalseki** [comment]
I know what is wrong, though am not entirely sure of a good way to fix it.

**Comment by ReikaKalseki** [comment]
Fixed.
