### ISSUE TITLE
[EndgameCombat] Lightning Turret Crash

### ISSUE THREAD

**Issue by bear2312** [ReikaKalseki/Reika_FactorioMods_Issues#88]
Tried placing Lightning Turrets, but if I do I get the following message and a crash to the main menu. 

Notice

Error while running event
EndgameCombat::on_tick(ID 0)
__EndgameCombat__/functions.lua:306:
attempt to index field '?' (a nil value)

**Comment by ReikaKalseki** [comment]
Fixed.
