### ISSUE TITLE
nauvis day error when place item

### ISSUE THREAD

**Issue by Eind7286** [ReikaKalseki/Reika_FactorioMods_Issues#89]
Got error 
"error while running event
NauvisDay::on_built_entity (ID 6)
entity is not crafting machine.
stack traceback:
nauvisday/control.lua:77:in function
nauvisday/control.lua:66"
i tried place air filter machine from air filtering advanced mod.
![nauvisdayerror](https://user-images.githubusercontent.com/42410353/44149787-7b5480c6-a0c7-11e8-8e30-61f79ab7ac52.jpg)

**Comment by ReikaKalseki** [comment]
I will fix this, but you do realize that NauvisDay has everything AirFiltering does and more, right?

**Comment by ReikaKalseki** [comment]
Done.
