### ISSUE TITLE
Uraninite and Fluorite error messages

### ISSUE THREAD

**Issue by Takatifu** [ReikaKalseki/Reika_FactorioMods_Issues#9]
At the start of the game I had these error messages popping up endlessly:
"Oreverhaul: Ore 'uraninite/fluorite' was specified in tier 5, but that ore does not exist in game. Skipping"
Any idea about how to stop them?

**Comment by ReikaKalseki** [comment]
"Endlessly"? They should print once (specifying a nonexistent ore in the config will do that as a warning), but after that it should stop (until you edit your modlist). Either way, if you remove those two ores from the config, it will stop.
