### ISSUE TITLE
Issue with EndgameCombat

### ISSUE THREAD

**Issue by generalsnipe** [ReikaKalseki/Reika_FactorioMods_Issues#90]
Hello, I have an issue with another mod and this one. 
Here is the screenshot: https://imgur.com/a/bUfjjpJ

**Comment by ReikaKalseki** [comment]
I will fix this, but in the meantime, remove AdditionalTurrets - EGCombat has cannon turrets too.

**Comment by generalsnipe** [comment]
Thanks will do.

**Comment by ReikaKalseki** [comment]
Done.
