### ISSUE TITLE
[Endgame Combat]Turrets not properly grouped in bonuswindows. 

### ISSUE THREAD

**Issue by MankoMR** [ReikaKalseki/Reika_FactorioMods_Issues#91]
Is it possible to cleanup the bonuswindows?

Here is the grouping based on the effects of researches in Factorio:
All Gun- and Concussionturrets together
All Laser- and Plasmaturrets together
All Flamethrowerturrets and Flamethrower ammo together.

It might help to look at the code of the laser- and plasmaturrets as they are already in a group(each type in another).

I tested with only this mod, just to be sure. Modversion:1.0.115

Here's a picture to ilustrate the problem: 
![factoriobonuswindowsissue](https://user-images.githubusercontent.com/16759599/44299390-06d35300-a2f5-11e8-9b04-de9284e8c204.JPG)

Also thanks for solving [the Crash with logistics chest on turrets](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/issues/71) :)

**Comment by ReikaKalseki** [comment]
With some input from Rseding, this cannot be fixed.

**Comment by MankoMR** [comment]
thanks for the cleanup

**Comment by ReikaKalseki** [comment]
I hid them, yes.
