### ISSUE TITLE
[Endgame Combat] "Turret Alert" audio very loud due to overlapping sounds/warnings

### ISSUE THREAD

**Issue by jmrd98** [ReikaKalseki/Reika_FactorioMods_Issues#92]
Hello. I will do my best to explain my issue. As best I can tell the code is confined to turret-alerts.lua, so any line references I make refer there as of the current version.

When using laser turrets, the turret alert seems to be overly sensitive, sounding on normal operation/firing. Specifically, any active firing seems to raise a "Turret Energy Critical" warning, as defined [here](https://github.com/ReikaKalseki/EndgameCombat/blob/273ec5c11f7683041c588efa082136536d426ae0/turret-alerts.lua#L126-L128) on lines 126-128, often with the list of alerts being taller than my screen due to the number of turrets firing.

The issue that results from this is the auditory warning raised due to this is very loud. I have compensated by adding a volume_modifier=0.05 on line 252, which gives then a low hum rather than blowing out my speakers, but this seems a workaround at best. It also is basically going off almost nonstop.

It looks like there is supposed to be a 5 second cooldown in tickTurretAlarms (line 190), and that may be working, but it is hard to tell when I am getting inundated with alerts from raiseTurretAlarm on line 248-254:
```
-- raise immediately no matter what
for _,player in pairs(game.connected_players) do
    if player.force == turret.force then
        player.add_custom_alert(turret, {type = "virtual", name = alarm}, {"virtual-signal-name." .. alarm}, true)
        player.play_sound{path=alerts[alarm].sound,volume_modifier=0.05}
    end
end
```

I don't know which is the issue, the excessive/maybe incorrect alarms, or the excessive sound resulting from the alarms if they are correct.

One suggestion I might offer is a audio percent scalar setting at the very least. 

The mod has been a lot of fun in any case, thank you for thinking it up!!
(I hate markdown, I can never get the syntax right on the first ~~19~~ tries, argh.)

**Comment by ReikaKalseki** [comment]
Energy critical warnings due to normal firing is indeed not intended.

Also, is this due to multiple turrets independently firing alarms, or one turret spamming them?

**Comment by jmrd98** [comment]
I am not in a position to check at the moment, but my suspicion is it is multiple individual alarms. Is there a particular way to test that? I can try to build a creative world or pull down my current save to a minimal working example but probably won't be able to do so until the weekend. 

For what it's worth, I had commented out the quoted block entirely and the problem with the sound went away, along with the alarms. 

So, it certainly involves those lines, but I can't say if it is caused by those lines.

**Comment by ReikaKalseki** [comment]
One way would be to modify the code and make it `game.print` the `turret.unit_number`.

**Comment by ReikaKalseki** [comment]
I had an idea that might solve both issues - if I removed the "always play on first call" code, then there would not likely be spurious energy alarms, as it is very unlikely that a turret will be nearly empty after firing exactly five seconds apart. It would also maybe fix the stacking.

**Comment by jmrd98** [comment]
I've had a chance to stick the ``game.print`` in, and have a closer look at things, at speed = 0.05.

What looks to be happening is each turret that fires results in a energy ~~low~~ critical trigger. This seems particularly amplified when multiple turrets are firing on a wave at the same time for an extended time, that is, more than one volley per biter. (Anywhere from 80-150 turrets with my walls.) 

The normal firing appears to bring the power level to about 1/5 of full, followed by it refilling in 5 steps back to full. So, down to 20% in normal operation.

The game is printing a wall of IDs for each, but they don't appear to repeat. Each one seems to fire a trigger and sleep. If the onslaught is long enough, it may repeat.

I'm looking back at the code. Is the actual alarm threshold correct? I have 
```
local function isEnergyCritical(turret)
	return turret.prototype.electric_energy_source_prototype and turret.energy < turret.prototype.electric_energy_source_prototype.buffer_capacity*0.75
end

local function isEnergyLow(turret)
	return turret.prototype.electric_energy_source_prototype and turret.energy < turret.prototype.electric_energy_source_prototype.buffer_capacity/3
end
```

Does that mean a critical warning trips at 75% of full and a low warning at 33%? One, that seems backwards at least, two, 33>20, so that would seem to fire always? I may be misunderstanding the comparison here.

**Comment by ReikaKalseki** [comment]
> Does that mean a critical warning trips at 75% of full and a low warning at 33%?

No, this does not look correct.

**Comment by ReikaKalseki** [comment]
The energy thresholds were in fact backwards. This has been fixed (and the low one lowered to 67% from 75%).

However, this does not solve the other issues.

**Comment by ReikaKalseki** [comment]
OK, I fixed these issues; sounds will not play spuriously.
