### ISSUE TITLE
[DirtyMining] mod conflict with Dark Matter Replicator

### ISSUE THREAD

**Issue by jodojodo** [ReikaKalseki/Reika_FactorioMods_Issues#93]
Hello Reika,

The DirtyMining mod creates new ore items based on existing ones. The Dark Matter Replicator mod however does have the ore "tenemut", but not the item "tenemut". "tenemut" is listed under tools (I assume because it is used for science).

Therefore if both mods are active, I get the error message "Could not create dirty ore item ...", because data.raw.item[name] is nil.

I added some code as "hotfix" into your ores.lua. With this in place it works. Maybe you know a better solution (Thats why I did not create a pull request).
![dirtyore mod hotfix](https://user-images.githubusercontent.com/7256369/44513366-76628d00-a6bd-11e8-8033-07d8866f94a5.png)

**Comment by ReikaKalseki** [comment]
Fixed.
