### ISSUE TITLE
[NauvisDay] Pollution emission increasing for mods

### ISSUE THREAD

**Issue by jodojodo** [ReikaKalseki/Reika_FactorioMods_Issues#94]
Hi Reika,

I am using many mods in my current game so when I saw the following log entries I thought that the emmision increasing might not allways be intentional:

>   39.711 Script @__NauvisDay__/data-updates.lua:93: "ID'ed polluter 'angels-electric-boiler', increasing emissions 4x"
>   39.711 Script @__NauvisDay__/data-updates.lua:104: "ID'ed 'extra' polluter 'angels-electric-boiler', increasing emissions again 1.2x"

I think the angel electric boiler consumes very much electricity. It shouldn't also produce so much pollution.

>  39.707 Script @__NauvisDay__/data-updates.lua:93: "ID'ed polluter 'steam-furnace', increasing emissions 4x"
>  39.707 Script @__NauvisDay__/data-updates.lua:93: "ID'ed polluter 'chemical-steam-furnace', increasing emissions 4x"

I thought your steam furncaces could be used as a low pollution alternative. Why then increasing its pollution emission?

>  39.711 Script @__NauvisDay__/data-updates.lua:93: "ID'ed polluter 'bi-bio-boiler', increasing emissions 4x"
>  39.711 Script @__NauvisDay__/data-updates.lua:104: "ID'ed 'extra' polluter 'bi-bio-boiler', increasing emissions again 1.2x"

Bio Boiler should be very pollution friendly, shoundn't they?

>  39.709 Script @__NauvisDay__/data-updates.lua:93: "ID'ed polluter 'algae-farm', increasing emissions 4x"
>  39.709 Script @__NauvisDay__/data-updates.lua:93: "ID'ed polluter 'algae-farm-2', increasing emissions 4x"
>  39.709 Script @__NauvisDay__/data-updates.lua:93: "ID'ed polluter 'crop-farm', increasing emissions 4x"
>  39.709 Script @__NauvisDay__/data-updates.lua:93: "ID'ed polluter 'temperate-farm', increasing emissions 4x"
>  39.709 Script @__NauvisDay__/data-updates.lua:93: "ID'ed polluter 'desert-farm', increasing emissions 4x"
>  39.709 Script @__NauvisDay__/data-updates.lua:93: "ID'ed polluter 'swamp-farm', increasing emissions 4x"
>  39.709 Script @__NauvisDay__/data-updates.lua:93: "ID'ed polluter 'bio-press', increasing emissions 4x"
>  39.709 Script @__NauvisDay__/data-updates.lua:93: "ID'ed polluter 'bio-processor', increasing emissions 4x"

I don't think that farms should produce pollution, since they only grow plants. Therefore their pollution emission should not be increased.

I like your mods very much, but Nauvisday in particular is very hard in a heavy modded game, because you need much more buildings of everything (furnaces, assembling machines, miner, etc.). It could use a little tweak in my oppinion. Or at least let the setting for Base pollution factor be smaller than 1 (maybe lower bound at 0.5?).

I append the log entries for all my pollution increasing buildings, so that you can see it yourself.
Thanks in advance for considering :)
[pollution.log](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/2313762/pollution.log)

**Comment by ReikaKalseki** [comment]
The system is automatic - it increases pollution generation based on the root type of the entity (assembling-machine, boiler, inserter, whatever), whether it has a burner power source, and other factors, with manual modifiers applied afterward.

The farms are probably meeting those criteria for technical reasons, but I can add an exception.

Electric devices still emit pollution, and so the the electric boilers still will, too. They are already not being increased as much as normal boilers, as they do not burn fuel for energy.

Steam furnaces *are* low-pollution options, and remain so after the increase. That increase is applied to nearly *everything*.

> Or at least let the setting for Base pollution factor be smaller than 1 (maybe lower bound at 0.5?).

That completely defeats the point of NauvisDay.

**Comment by ReikaKalseki** [comment]
The farms no longer have the 4x pollution increase. Everything else is intended and will stay.
