### ISSUE TITLE
turret nil value error

### ISSUE THREAD

**Issue by smitswil** [ReikaKalseki/Reika_FactorioMods_Issues#95]
Playing with the 3 Natural Evolution Mods and Rampant AI.

Am getting the following error, not sure if the log file attached captured the error shown.   

![image](https://user-images.githubusercontent.com/2762096/44556255-8189dd00-a6fe-11e8-9112-43898b9e626e.png)

[factorio-current.log](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/2316510/factorio-current.log)

**Comment by ReikaKalseki** [comment]
Fixed.
