### ISSUE TITLE
Missing some Items Name and Ammo alert!

### ISSUE THREAD

**Issue by SkiperTheBoss** [ReikaKalseki/Reika_FactorioMods_Issues#96]
Hey there is a few Items that don't show the right name for it.

The Equipments for Acid, Fire, Posion, Radiation show's the the name like Unknown key : "equipment-name.fire-spraying-equipment".

I also realize right now that the Concussion Turret keep giving me alert about having to low Ammo but there is 100 Red and 13 Yellow Magazines in it, i guess it checks only one slot of it or it dosen't count all of different Magazines togther but thats just my feeling.

**Comment by ReikaKalseki** [comment]
Fixed.
