### ISSUE TITLE
Blocked chest on ground

### ISSUE THREAD

**Issue by SilentOwl** [ReikaKalseki/Reika_FactorioMods_Issues#97]
Hello, using natural evolution buildings and endgame combat there is a problem in the item collector from NEB.
The item collector gain the logistic chest from endgame combat but when i deconstruct it the chest remain placed without possibility of remove it or destroy.

**Comment by ReikaKalseki** [comment]
SAGuy needs to not collect entities that are flagged with `"not-blueprintable", "not-deconstructable"`, and/or which have a `nil` value for `minable`.

(@TheSAGuy)

In the meantime, you can delete that chest by mousing over it and running `/c game.player.selected.destroy()`.
