### ISSUE TITLE
Error when launching Endgame Combat 1.0.132 w/ Angel's Petro Chemical Processing

### ISSUE THREAD

**Issue by GaistH** [ReikaKalseki/Reika_FactorioMods_Issues#98]
Failed to load mods: Error in assignID, technology with name 'cobalt-processing-2' does not exist.

Source: acid-turrets (technology).

Mods to be disabled:
* EndgameCombat
* angelspetrochem

![fjiikx2](https://user-images.githubusercontent.com/42808283/44962706-0ab8c500-aef2-11e8-95cb-0de00cb54599.png)

[factorio-current.log](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/2343912/factorio-current.log)

**Comment by ReikaKalseki** [comment]
This makes no sense; the dependency on Co-proc-2 only is registered if that technology exists....

**Comment by ReikaKalseki** [comment]
Alright then...
