### ISSUE TITLE
Error when launching FTweaks 1.0.132 w/ More Science

### ISSUE THREAD

**Issue by GaistH** [ReikaKalseki/Reika_FactorioMods_Issues#99]
Failed to load mods: Error while running setup for technology prototype "power-armor" (technology): Technology prerequisite "military-3" is registered more than once.

Mods to be disabled: 
* base
* MoreScience
* FTweaks
* ShinyBob_Techs

![q9epzmc](https://user-images.githubusercontent.com/42808283/44962931-6421f380-aef4-11e8-8cee-cfb6c063c429.png)

[factorio-current.log](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/files/2343907/factorio-current.log)

**Comment by ReikaKalseki** [comment]
Fixed.
